#!/usr/bin/env python3
"""Rebuild the reconciled sign sequence of Raince to Madame (Dupuy 452 ff.28r-29v) from the line
crops, and check it (rule 7).

  python3 glyphs/build.py           segment -> classify (+ overrides.tsv) -> align both passes ->
                                    write ciphertext.txt, inventory.tsv, glyphs/stats.json,
                                    glyphs/contact_sheet.jpg
  python3 glyphs/build.py --check   rebuild in memory and exit 1 if ciphertext.txt or
                                    inventory.tsv differ from what is committed

Inputs: images/crops/*.jpg + manifest.json, images/gutter/*.jpg, glyphs/cipher_span.json,
glyphs/prototypes.npz, glyphs/overrides.tsv, passA.tsv, passB.tsv. Needs numpy, scipy, opencv,
scikit-image, scikit-learn. Takes about two minutes.

A token is marked uncertain (suffix '?') when it was not settled by eye (overrides.tsv) and
either (a) at least one pass read the sign and no reading of either pass is consistent with the
type (a pass code is consistent with a type when that type takes at least a tenth of the code's
aligned readings, see confusion_A/B.tsv), or (b) no pass read it and the classifier's vote share
is below 0.6 or its nearest-prototype distance is above the 97th-percentile threshold.
"""
import csv
import json
import os
import sys
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.dirname(HERE)
sys.path.insert(0, HERE)

HEADER = """# Nicolas Raince to Madame [Louise de Savoie], Rome, 25 Oct 1525. BnF Dupuy 452 ff.28r-29v,
# Gallica ark:/12148/btv1b10036146c, IIIF canvases f34 (28r), f35 (28v + 29r), f36 (29v).
# Reconciled cipher-sign sequence, 23 Sept 2026 (reconciliation worker; see reconciliation.md).
# Generated by glyphs/build.py from the line crops; `python3 glyphs/build.py --check` exits 1 if
# this file is stale. Do not edit by hand: settle a sign in glyphs/overrides.tsv and rebuild.
#
# The earlier content of this file (the f.20 letter, Alberto Pio de Carpi to Madame, a single
# partial reading of 86 tokens) moved on 23 Sept 2026 to ciphertext_f20_carpi.txt, unchanged.
#
# Format: one physical line of the manuscript per text line: "<page> <line> <band> | tokens".
# <line> is glyphs/segment.py's line index on that page (0 = top margin); <band> is the crop
# band and line within it (images/crops/<page>_Lnn_s1/_s2.jpg, line 1 or 2), which is how
# passA.tsv and passB.tsv are keyed. Tokens are sign-type codes (inventory.tsv; shapes on
# glyphs/contact_sheet.jpg), separated by spaces. A trailing '?' marks an uncertain token (rule in
# glyphs/build.py). Only the cipher block is given: f28r from the sign after "escript /" on line
# 12 to the end of the page; all of f28v and f29r; f29v lines 1-7 to "... K" before "(.".
# Plain French before and after is excluded. No decoding; no key applied.
"""

MEANING = {
    "psi": "trident on a stem (psi)", "l": "cursive l-loop, crossed tail (figure-of-eight / ribbon)",
    "v": "v / check stroke", "arr": "arrowhead on a stem (upward wedge with foot)", "lam": "caret, open (Lambda)",
    "f": "long f with crossbar", "db": "dagger (short cross high on a stem) standing on a small o",
    "o": "small plain o", "I": "I with serifs", "q": "ball on a plain stem (reversed q / lollipop)",
    "rho": "rho: loop with a long tail curling left under the previous sign", "z": "z",
    "box": "small rectangle with a dot inside", "T": "T", "X": "double x / starred X", "n": "n",
    "7": "7", "E": "E / epsilon", "S": "S", "ankh": "ball on a stem with a crossbar (ankh / female sign)",
    "sq": "a-like loop with a diagonal stroke (slashed q)", "th": "theta, o with a horizontal bar",
    "R": "R", "Del": "closed triangle (Delta)", "dbar": "o under a long horizontal bar with a short stem",
    "H": "H (left stem sometimes faint)", "w": "omega / w", "six": "6 (reversed 6 / G-like loop)",
    "lamL": "large lambda with a tail", "m": "m", "A": "A", "L": "script L loop", "cross4": "cross with a loop at three ends",
    "pi": "omega with a bar above (varpi)", "K": "K", "zslash": "z with a long diagonal (lightning)",
    "x": "single curly x (kappa-like)", "plus": "plus sign", "dash_o": "short dash joined to an o (-o)",
    "three": "3", "oplus": "circle with a cross inside", "U": "U with a loop on each arm",
    "Tbox": "tall T over an o (boxed T)", "bz": "b joined to z", "yogh": "tall 3 with a descender (yogh)",
    "heart": "heart", "hash": "triple bar crossed by a stem", "diamond": "diamond with a dot",
    "box3": "three boxes in a row", "y": "y", "?": "unresolved shape (settled as a sign, type unknown)",
}


def lenient_map(pas):
    m = {}
    for x in csv.DictReader(open(os.path.join(HERE, f"confusion_{pas}.tsv")), delimiter="\t"):
        tot = int(x["total"])
        ts = {k: int(v) for k, v in x.items() if k not in ("code", "total")}
        m[x["code"]] = {t for t, v in ts.items() if v >= max(2, 0.1 * tot)}
    return m


def bands():
    man = json.load(open(os.path.join(TARGET, "images", "crops", "manifest.json")))["crops"]
    out = defaultdict(list)
    for c in man:
        if c["crop"].endswith("_s1.jpg") and c["crop"][:4] in ("f28r", "f28v", "f29r", "f29v"):
            out[c["crop"][:4]].append((c["box"][1], c["box"][3], c["crop"][5:8]))
    return out


def compose():
    import classify
    import reconcile
    import segment
    segment.main()
    classify.main()
    reconcile.main()
    cl = list(csv.DictReader(open(os.path.join(HERE, "classified.tsv")), delimiter="\t"))
    al = {r["n"]: r for r in csv.DictReader(open(os.path.join(HERE, "alignment.tsv")), delimiter="\t")}
    lines = {(r["page"], int(r["line"])): float(r["y_centre"])
             for r in csv.DictReader(open(os.path.join(HERE, "lines.tsv")), delimiter="\t")}
    MA, MB = lenient_map("A"), lenient_map("B")
    accept = classify.Model().accept
    bd = bands()
    # band label per line: which crop band holds the line centre, and 1st/2nd line in it
    band_of = {}
    for (page, li), y in lines.items():
        for y0, y1, L in bd.get(page, []):
            if y0 <= y < y1:
                inb = sorted(yy for (p, l), yy in lines.items() if p == page and y0 <= yy < y1)
                band_of[(page, li)] = f"{L}/{inb.index(y) + 1}"
    toks = []
    for r in cl:
        a = al[r["n"]]
        t = r["type"]
        reads = [(c, MA) for c in a["passA"].split("|") if c not in ".-"] + \
                [(c, MB) for c in a["passB"].split("|") if c not in ".-"]
        settled = r["rule"].startswith("override")
        if settled:
            unc = t == "?"
        elif reads:
            unc = not any(t in M.get(c, set()) for c, M in reads)
        else:
            unc = float(r["vote_share"]) < 0.6 or float(r["d1"]) > accept
        toks.append(dict(r, unc=unc, reads=len(reads), pA=a["passA"], pB=a["passB"]))
    out = [HEADER]
    by_line = defaultdict(list)
    for t in toks:
        by_line[(t["page"], int(t["line"]))].append(t)
    for (page, li) in sorted(by_line, key=lambda k: (["f28r", "f28v", "f29r", "f29v"].index(k[0]), k[1])):
        ts = by_line[(page, li)]
        out.append(f"{page} {li:02d} {band_of.get((page, li), '?'):>6} | " +
                   " ".join(t["type"] + ("?" if t["unc"] and t["type"] != "?" else "") for t in ts))
    cipher = "\n".join(out) + "\n"
    # inventory
    cnt = Counter(t["type"] for t in toks)
    unc = Counter(t["type"] for t in toks if t["unc"])
    codes = {"A": defaultdict(Counter), "B": defaultdict(Counter)}
    for t in toks:
        for pas, col in (("A", "pA"), ("B", "pB")):
            for c in t[col].split("|"):
                if c not in ".-":
                    codes[pas][t["type"]][c] += 1
    order = sorted(cnt, key=lambda k: -cnt[k])
    inv = ["# Sign inventory of the reconciled Raince cipher (ciphertext.txt). Generated by glyphs/build.py.",
           "# row = row of glyphs/contact_sheet.jpg (1 = top). passA_codes / passB_codes: the pass codes aligned",
           "# to signs of this type, with counts (codes with at least 2 hits or a tenth of the type's readings).",
           "code\tcount\tuncertain\tsheet_row\tshape\tpassA_codes\tpassB_codes"]
    for i, k in enumerate(order):
        def fmt(c):
            tot = sum(c.values())
            return ", ".join(f"{x} {n}" for x, n in c.most_common() if n >= 2 and n >= 0.1 * tot or n == c.most_common(1)[0][1]) or "-"
        inv.append(f"{k}\t{cnt[k]}\t{unc[k]}\t{i + 1}\t{MEANING.get(k, '')}\t{fmt(codes['A'][k])}\t{fmt(codes['B'][k])}")
    inventory = "\n".join(inv) + "\n"
    return cipher, inventory, toks


def main():
    check = "--check" in sys.argv
    cipher, inventory, toks = compose()
    fc, fi = os.path.join(TARGET, "ciphertext.txt"), os.path.join(TARGET, "inventory.tsv")
    if check:
        stale = [f for f, new in ((fc, cipher), (fi, inventory)) if not os.path.exists(f) or open(f).read() != new]
        if stale:
            print("STALE:", ", ".join(os.path.basename(f) for f in stale))
            sys.exit(1)
        print("ciphertext.txt and inventory.tsv are current")
        return
    open(fc, "w").write(cipher)
    open(fi, "w").write(inventory)
    import montage
    import cv2
    png = os.path.join(HERE, "_sheet.png")
    montage.sheet(png)
    cv2.imwrite(os.path.join(HERE, "contact_sheet.jpg"), cv2.imread(png, 0), [cv2.IMWRITE_JPEG_QUALITY, 80])
    os.remove(png)
    st = dict(tokens=len(toks), types=len({t["type"] for t in toks}),
              uncertain=sum(t["unc"] for t in toks),
              overridden=sum(t["rule"].startswith("override") for t in toks),
              by_page=Counter(t["page"] for t in toks))
    json.dump(st, open(os.path.join(HERE, "stats.json"), "w"), indent=1)
    print(json.dumps(st))


if __name__ == "__main__":
    main()
