#!/usr/bin/env python3
"""Rebuild the reconciled sign sequence of f.24 (Raince to Robertet, Dupuy 452 ff.24r-24v) from the
line crops and the two blind passes, and check it (rule 7).

  python3 glyphs_f24/build_f24.py           segment + classify (../glyphs pipeline, patched by f24.py)
                                            -> align passA_f24.tsv / passB_f24.tsv -> settle -> write
                                            ciphertext_f24.txt, inventory_f24.tsv, glyphs_f24/*.tsv
  python3 glyphs_f24/build_f24.py --check   rebuild in memory, exit 1 if ciphertext_f24.txt or
                                            inventory_f24.tsv differ from the files on disk

Same method as the ff.28-29 reconciliation (reconciliation.md), with one change forced by the shared
legend: both passes now read in the 50 type codes, so a pass code is compared with the type directly.
Settlement of each segmented sign, in order:
  1. overrides_f24.tsv (settled by eye on the crops) wins;
  2. else, both passes read the sign with the same code and it differs from the classifier: the
     passes' code (rule "AB");
  3. else the classifier's type.
A token is uncertain ('?' suffix) when it is not settled by eye and (a) no pass reading equals the
final type, or (b) the passes disagree with each other, or (c) no pass read it and the classifier is
unsure (vote share < 0.6 or nearest-prototype distance above the 97th percentile). A reader's own '?'
counts as a reading of that code for (a) but not for rule 2.
"""
import csv
import json
import math
import os
import sys
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import f24  # noqa: E402

PAGES = ["f24r", "f24v"]
ROUNDS = 3
GAP = -2.5
OV_TOL = 6

HEADER = """# Nicolas Raince to Monseigneur [Florimond Robertet], Rome, 24 Oct 1525. BnF Dupuy 452 ff.24r-24v,
# Gallica ark:/12148/btv1b10036146c, IIIF canvases f29 (24r) and f30 (24v, left page).
# Reconciled cipher-sign sequence, 24 Sept 2026 (f.24 transcription worker; see reconciliation_f24.md).
# Generated by glyphs_f24/build_f24.py from the line crops, the gutter strip and passA_f24.tsv /
# passB_f24.tsv; `python3 glyphs_f24/build_f24.py --check` exits 1 if this file is stale. Do not edit
# by hand: settle a sign in glyphs_f24/overrides_f24.tsv and rebuild.
#
# Codes are the 50 sign types of the Raince-to-Madame letter (inventory.tsv, glyphs/contact_sheet.jpg);
# a code not in that list is new to f.24 and is described in inventory_f24.tsv.
# Format: one physical line per text line: "<page> <line> <band> | tokens". <line> is the segmenter's
# line index on that page (0 = top); <band> is the crop band and line within it (images/crops/
# <page>_Lnn_s1/_s2.jpg, line 1 or 2). A trailing '?' marks an uncertain token (rule in build_f24.py).
# Only the cipher block is given: f24r lines 9-40 (after the plain opening that ends "... au pape /
# qm. Sa S[ainte]te. /."); f24v lines 1-12 up to the last sign before "(." and "Monseigneur, il n'y a ...".
# No decoding; no key applied.
"""


def boxes():
    man = json.load(open(os.path.join(TARGET, "images", "crops", "manifest.json")))["crops"]
    out = {c["crop"]: c["box"] for c in man if c["crop"][:4] in PAGES}
    for c in json.load(open(os.path.join(TARGET, "images", "gutter", "f24v_s3_manifest.json"))):
        out[c["crop"]] = c["box"]
    return out


def load_overrides():
    fn = os.path.join(HERE, "overrides_f24.tsv")
    if not os.path.exists(fn):
        return {}
    return {(o["page"], int(o["line"]), int(o["x"])): o for o in
            csv.DictReader((l for l in open(fn) if not l.startswith("#")), delimiter="\t")}


def load_pass(pas):
    fn = os.path.join(TARGET, f"pass{pas}_f24.tsv")
    seqs = defaultdict(list)
    for line in open(fn, encoding="utf-8"):
        if line.startswith("#") or line.startswith("crop_file"):
            continue
        f = line.rstrip("\n").split("\t")
        if len(f) < 4 or f[0][:4] not in PAGES:
            continue
        t = f[3].strip().strip('"')
        if not t or t.startswith("["):
            continue
        try:
            ln = int(f[1])
        except ValueError:
            continue
        seqs[(f[0], ln)].append(t)
    return seqs


def base(code):
    return code[:-1] if code.endswith("?") and len(code) > 1 else code


def align(codes, sigs, score):
    """Global on codes, free end gaps on sigs; returns [(code_index|None, sig_index|None)]."""
    n, m = len(codes), len(sigs)
    NEG = -1e9
    D = [[NEG] * (m + 1) for _ in range(n + 1)]
    B = [[None] * (m + 1) for _ in range(n + 1)]
    for j in range(m + 1):
        D[0][j] = 0.0
    for i in range(1, n + 1):
        D[i][0] = D[i - 1][0] + GAP
        B[i][0] = "u"
        ci = codes[i - 1]
        for j in range(1, m + 1):
            best, b = D[i - 1][j - 1] + score(ci, sigs[j - 1]["type"]), "d"
            if D[i - 1][j] + GAP > best:
                best, b = D[i - 1][j] + GAP, "u"
            if D[i][j - 1] + GAP > best:
                best, b = D[i][j - 1] + GAP, "l"
            D[i][j], B[i][j] = best, b
    j = max(range(m + 1), key=lambda k: D[n][k])
    total = D[n][j]
    i, out = n, []
    tail = [(None, k) for k in range(m - 1, j - 1, -1)]
    while i > 0 or j > 0:
        if i == 0:
            out.append((None, j - 1)); j -= 1; continue
        b = B[i][j]
        if b == "d":
            out.append((i - 1, j - 1)); i -= 1; j -= 1
        elif b == "u":
            out.append((i - 1, None)); i -= 1
        else:
            out.append((None, j - 1)); j -= 1
    return list(reversed(out)) + list(reversed(tail)), total


def make_score(conf, ntypes):
    def score(c, t):
        c = base(c)
        v = conf.get(c) if conf else None
        if not v:
            return 3.0 if c == t else -1.5
        tot = sum(v.values())
        return math.log((v.get(t, 0) + 0.2) / (tot + 0.2 * ntypes) * ntypes)
    return score


def run_pass(seqs, bx, line_y, by_line, ntypes):
    """Each (crop, line_no) is aligned to the best-scoring physical line whose centre lies in the
    crop's band (the crop-cutter and the segmenter count lines independently), inside the crop's
    x-window."""
    conf = None
    for _ in range(ROUNDS):
        score = make_score(conf, ntypes)
        newconf = defaultdict(Counter)
        results = []
        for (crop, ln), codes in sorted(seqs.items()):
            box = bx.get(crop)
            if box is None:
                continue
            page = crop[:4]
            cands = sorted((y, li) for (p, li), y in line_y.items() if p == page and box[1] - 30 <= y < box[3] + 30)
            # prefer the line_no-th line of the band, but take a neighbour if it aligns much better
            best = None
            for rank, (y, li) in enumerate(cands):
                sigs = [r for r in by_line.get((page, li), []) if box[0] <= r["xc"] < box[2]]
                if not sigs:
                    continue
                al, tot = align(codes, sigs, score)
                tot -= 0 if rank == ln - 1 else 5.0
                if best is None or tot > best[0]:
                    best = (tot, li, sigs, al)
            if best is None:
                continue
            _, li, sigs, al = best
            results.append((crop, ln, li, codes, sigs, al))
            for a, b in al:
                if a is not None and b is not None:
                    newconf[base(codes[a])][sigs[b]["type"]] += 1
        conf = newconf
    return results, conf


def band_label(page, y, bx):
    for name, box in bx.items():
        if name.startswith(page) and name.endswith("_s1.jpg") and box[1] <= y < box[3]:
            return name[5:8]
    return "?"


def compose():
    final, model = f24.cl.run()
    # overrides by eye
    ov = load_overrides()
    target, missing = {}, []
    for k, o in ov.items():
        page, line, x = k
        cand = [(abs(s["line"] - line), abs(s["x"] - x), j) for j, s in enumerate(final)
                if s["page"] == page and abs(s["line"] - line) <= 1 and abs(s["x"] - x) <= OV_TOL]
        if not cand:
            missing.append(k)
            continue
        target[min(cand)[2]] = o
    rows = []
    for j, s in enumerate(final):
        o = target.get(j)
        if o is None:
            rows.append(dict(s, settled=""))
            continue
        if o["type"] == "DROP":
            continue
        parts = o["type"].split(",")
        for i, t in enumerate(parts):
            w = s["w"] // len(parts)
            rows.append(dict(s, x=s["x"] + i * w, w=w if len(parts) > 1 else s["w"], type=t, cls=s["type"],
                             settled="eye" + ("-split" if len(parts) > 1 else "")))
    for n, r in enumerate(rows):
        r["n"] = n
        r["xc"] = r["x"] + r["w"] / 2
        r.setdefault("cls", r["type"])
    by_line = defaultdict(list)
    for r in rows:
        by_line[(r["page"], r["line"])].append(r)
    line_y ={k: float(sorted(r["y"] + r["h"] / 2 for r in v)[len(v) // 2]) for k, v in by_line.items()}
    bx = boxes()
    types = sorted({r["cls"] for r in rows})
    reads = {"A": defaultdict(list), "B": defaultdict(list)}
    covered = {"A": set(), "B": set()}
    extra, confs = [], {}
    for pas in "AB":
        seqs = load_pass(pas)
        results, conf = run_pass(seqs, bx, line_y, by_line, len(types))
        confs[pas] = conf
        for crop, ln, li, codes, sigs, al in results:
            idx = [b for a, b in al if a is not None and b is not None]
            if idx:
                for k in range(min(idx), max(idx) + 1):
                    covered[pas].add(sigs[k]["n"])
            prev = ""
            for a, b in al:
                if b is not None:
                    prev = sigs[b]["n"]
                if a is not None and b is not None:
                    reads[pas][sigs[b]["n"]].append(codes[a])
                elif a is not None:
                    extra.append((pas, crop, ln, a + 1, codes[a], li, prev))
    toks = []
    for r in rows:
        A, B = reads["A"].get(r["n"], []), reads["B"].get(r["n"], [])
        t, rule = r["cls"], r["settled"]
        firm = lambda L: {c for c in L if not c.endswith("?") and c != "?"}
        fa, fb = firm(A), firm(B)
        if not rule and len(fa) == 1 and fa == fb and next(iter(fa)) != t:
            t, rule = next(iter(fa)), "AB"
        allr = {base(c) for c in A + B if c != "?"}
        if rule.startswith("eye"):
            unc = t == "?"
        elif A or B:
            unc = t not in allr or (bool(A) and bool(B) and not ({base(c) for c in A} & {base(c) for c in B}))
        else:
            unc = r["share"] < 0.6 or r["d1"] > model.accept
        toks.append(dict(r, type=t, rule=rule, unc=unc, pA="|".join(A) or ("-" if r["n"] in covered["A"] else "."),
                         pB="|".join(B) or ("-" if r["n"] in covered["B"] else ".")))
    # ciphertext
    out = [HEADER]
    by = defaultdict(list)
    for t in toks:
        by[(t["page"], t["line"])].append(t)
    for (page, li) in sorted(by, key=lambda k: (PAGES.index(k[0]), k[1])):
        ts = sorted(by[(page, li)], key=lambda t: t["x"])
        y = line_y[(page, li)]
        L = band_label(page, y, bx)
        inb = sorted(yy for (p, l), yy in line_y.items() if p == page and band_label(p, yy, bx) == L)
        out.append(f"{page} {li:02d} {L}/{inb.index(y) + 1} | " +
                   " ".join(t["type"] + ("?" if t["unc"] and t["type"] != "?" else "") for t in ts))
    cipher = "\n".join(out) + "\n"
    # inventory
    raince = {}
    for x in csv.DictReader((l for l in open(os.path.join(TARGET, "inventory.tsv")) if not l.startswith("#")),
                            delimiter="\t"):
        raince[x["code"]] = x
    cnt = Counter(t["type"] for t in toks)
    unc = Counter(t["type"] for t in toks if t["unc"])
    codes = {p: defaultdict(Counter) for p in "AB"}
    for t in toks:
        for p, col in (("A", "pA"), ("B", "pB")):
            for c in t[col].split("|"):
                if c not in ".-":
                    codes[p][t["type"]][c] += 1
    newdesc = {}
    fn = os.path.join(HERE, "new_signs_f24.tsv")
    if os.path.exists(fn):
        for x in csv.DictReader((l for l in open(fn) if not l.startswith("#")), delimiter="\t"):
            newdesc[x["code"]] = x["shape"]
    inv = ["# Sign inventory of f.24 (ciphertext_f24.txt). Generated by glyphs_f24/build_f24.py.",
           "# shared_code: the Raince-to-Madame type (inventory.tsv) this sign is; 'NEW' = not among those 50.",
           "# count_f28_29: the same type's count in ciphertext.txt. passA_codes / passB_codes: the codes each",
           "# f.24 pass gave to signs settled as this type (codes with at least 2 hits or a tenth of the readings).",
           "sign\tcount\tuncertain\tshared_code\tcount_f28_29\tshape\tpassA_codes\tpassB_codes"]

    def fmt(c):
        tot = sum(c.values())
        return ", ".join(f"{x} {n}" for x, n in c.most_common() if (n >= 2 and n >= 0.1 * tot) or n == c.most_common(1)[0][1]) or "-"
    for k in sorted(cnt, key=lambda k: -cnt[k]):
        shared = k if k in raince else "NEW"
        shape = raince[k]["shape"] if k in raince else newdesc.get(k, "")
        inv.append(f"{k}\t{cnt[k]}\t{unc[k]}\t{shared}\t{raince[k]['count'] if k in raince else 0}\t{shape}\t"
                   f"{fmt(codes['A'][k])}\t{fmt(codes['B'][k])}")
    inventory = "\n".join(inv) + "\n"
    side = dict(toks=toks, extra=extra, confs=confs, types=types, missing=missing)
    return cipher, inventory, side


def write_side(side):
    with open(os.path.join(HERE, "alignment_f24.tsv"), "w") as f:
        f.write("n\tpage\tline\tx\ty\tw\th\tclassifier\td1\tshare\tpassA\tpassB\tfinal\trule\tuncertain\n")
        for t in side["toks"]:
            f.write(f"{t['n']}\t{t['page']}\t{t['line']}\t{t['x']}\t{t['y']}\t{t['w']}\t{t['h']}\t{t['cls']}\t"
                    f"{t['d1']:.3f}\t{t['share']:.2f}\t{t['pA']}\t{t['pB']}\t{t['type']}\t{t['rule']}\t{int(t['unc'])}\n")
    with open(os.path.join(HERE, "pass_extra_f24.tsv"), "w") as f:
        f.write("pass\tcrop\tline_no\ttoken_no\tcode\tpage_line\tafter_sign_n\n")
        for e in side["extra"]:
            f.write("\t".join(str(v) for v in e) + "\n")
    for p, conf in side["confs"].items():
        ts = sorted({t for v in conf.values() for t in v})
        with open(os.path.join(HERE, f"confusion_{p}_f24.tsv"), "w") as f:
            f.write("code\ttotal\t" + "\t".join(ts) + "\n")
            for c in sorted(conf, key=lambda c: -sum(conf[c].values())):
                f.write(f"{c}\t{sum(conf[c].values())}\t" + "\t".join(str(conf[c].get(t, 0)) for t in ts) + "\n")


def main():
    check = "--check" in sys.argv
    cipher, inventory, side = compose()
    if side["missing"]:
        print("overrides not matched:", side["missing"])
    fc, fi = os.path.join(TARGET, "ciphertext_f24.txt"), os.path.join(TARGET, "inventory_f24.tsv")
    if check:
        stale = [f for f, new in ((fc, cipher), (fi, inventory)) if not os.path.exists(f) or open(f).read() != new]
        if stale:
            print("STALE:", ", ".join(os.path.basename(f) for f in stale))
            sys.exit(1)
        print("ciphertext_f24.txt and inventory_f24.tsv are current")
        return
    open(fc, "w").write(cipher)
    open(fi, "w").write(inventory)
    write_side(side)
    toks = side["toks"]
    st = dict(tokens=len(toks), types=len({t["type"] for t in toks}), uncertain=sum(t["unc"] for t in toks),
              by_eye=sum(t["rule"].startswith("eye") for t in toks), by_AB=sum(t["rule"] == "AB" for t in toks),
              by_page=Counter(t["page"] for t in toks))
    json.dump(st, open(os.path.join(HERE, "stats_f24.json"), "w"), indent=1)
    print(json.dumps(st))


if __name__ == "__main__":
    main()
