#!/usr/bin/env python3
"""Write solver/signs_full.txt (all 900 reconciled signs, first reading per sign) from ciphertext.txt.

24 Sept 2026. seg_homophonic.py scores lines that share the prefix before '_L' as one continuous passage, so the
line ids are renamed here to group signs by unbroken cipher run, in reading order:
  f8a  f8_left_L1-L2 (left page, up to the clear 'et mi causa ...')
  f8b  f8_left_L3-L4 (after the clear 'ne leterne', up to the clear 'il cardinale nostro fratello ...')
  f8   f8_L2-L11 + f8_right_L12 (right page; L12 continues L11)
  f9a  f9_top_L1 pos 1-7 (before the clear 'et mi');  f9b  f9_top_L1 pos 8-32 + f9_top_L2-L3
  f9   f9_L6;  f10  f10_L2-L7   (old ids, unchanged)
  python3 make_signs_full.py [--check]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RENAME = {'f8_left_L1': 'f8a_L1', 'f8_left_L2': 'f8a_L2', 'f8_left_L3': 'f8b_L3', 'f8_left_L4': 'f8b_L4',
          'f8_right_L12': 'f8_L12', 'f9_top_L2': 'f9b_L2', 'f9_top_L3': 'f9b_L3'}
ORDER = ['f8_left_L1', 'f8_left_L2', 'f8_left_L3', 'f8_left_L4', 'f8_L2', 'f8_L3', 'f8_L4', 'f8_L5', 'f8_L7',
         'f8_L8', 'f8_L9', 'f8_L10', 'f8_L11', 'f8_right_L12', 'f9_top_L1', 'f9_top_L2', 'f9_top_L3', 'f9_L6',
         'f10_L2', 'f10_L3', 'f10_L4', 'f10_L5', 'f10_L6', 'f10_L7']


def build():
    lines = {}
    for l in open(os.path.join(HERE, '..', 'ciphertext.txt')):
        if l.startswith('#') or l.startswith('line\t'):
            continue
        r = l.rstrip('\n').split('\t')
        lines.setdefault(r[0], []).append(r[2])
    assert sorted(lines) == sorted(ORDER), 'ciphertext.txt lines changed; update ORDER'
    out = ['# Generated by make_signs_full.py from ciphertext.txt (900 reconciled signs, first reading per sign).'
           ' line_id<TAB>signs']
    for k in ORDER:
        s = ''.join(lines[k])
        if k == 'f9_top_L1':
            out += ['f9a_L1\t' + s[:7], 'f9b_L1\t' + s[7:]]
        else:
            out.append(RENAME.get(k, k) + '\t' + s)
    return '\n'.join(out) + '\n'


if __name__ == '__main__':
    t, p = build(), os.path.join(HERE, 'signs_full.txt')
    if '--check' in sys.argv:
        ok = os.path.exists(p) and open(p).read() == t
        print('ok' if ok else 'stale: signs_full.txt')
        sys.exit(0 if ok else 1)
    open(p, 'w').write(t)
    print('wrote signs_full.txt')
