#!/usr/bin/env python3
"""Decode the Raince letter of 25 Oct 1525 (Dupuy 452 ff.28r-29v) from ciphertext.txt + key.tsv.

Writes reading.txt (one manuscript line per line, letters run together as in the cipher) and
reading_tokens.tsv (one row per cipher token with its grade). --check regenerates both in memory and
exits 1 if either committed file is stale (CLAUDE.md rule 7).

Grades per token (CLAUDE.md rule 4):
  H  sign matched by shape to a glyph of the 1526 key (Tomokiyo; Bourdeau's measured table), key value
  C  value confirmed from known plaintext (Jacqueton 1892, P.J. XXXIII, printed from the f.31 decipherment)
  S  value assigned from decoded context (sign absent from the 1526 key, or a different value)
  M  an H or S sign whose transcription is uncertain (token marked '?' in ciphertext.txt)
  U  open sign, no value (shown as <code>)
Nulls are graded like letters (their identification is part of the reading) and print nothing.
No I (nothing repaired). Solver worker, 24 Sept 2026.
"""
import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))


def load_key():
    key = {}
    for line in open(os.path.join(HERE, "key.tsv"), encoding="utf-8"):
        if line.startswith("#") or line.startswith("code\t") or not line.strip():
            continue
        f = line.rstrip("\n").split("\t")
        key[f[0]] = (f[1], f[2], f[3])
    return key


def build():
    key = load_key()
    lines, rows, grades = [], ["page\tline\tpos\tcode\tuncertain\tvalue\tgrade"], Counter()
    for raw in open(os.path.join(HERE, "ciphertext.txt"), encoding="utf-8"):
        if raw.startswith("#") or "|" not in raw:
            continue
        head, toks = raw.split("|", 1)
        page, ln = head.split()[:2]
        out = []
        for i, t in enumerate(toks.split(), 1):
            unc = t.endswith("?") and t != "?"
            code = t[:-1] if unc else t
            value, kind, source = key[code]
            if kind == "open":
                g, shown = "U", value
            else:
                g = {"key": "H", "print": "C"}.get(source, "S")
                if unc:
                    g = "M"
                shown = "" if kind == "null" else value
            grades[g] += 1
            out.append(shown)
            rows.append(f"{page}\t{ln}\t{i}\t{code}\t{int(unc)}\t{value}\t{g}")
        lines.append(f"{page} {ln} | {''.join(out)}")
    total = sum(grades.values())
    summ = " ".join(f"{g} {grades[g]}" for g in "HCSMU")
    header = [
        "# Raince to Madame [Louise de Savoie], Rome, 25 Oct 1525. BnF Dupuy 452 ff.28r-29v.",
        "# Generated by decode.py from ciphertext.txt + key.tsv (python3 decode.py --check). Do not edit.",
        "# Letters run together as in the cipher; nulls dropped; word signs in [ ]; open signs as <code>.",
        "# E is shown as y but stands for the key's y and h (merged by the transcription): read 'cy' as ch.",
        f"# Tokens: {total}. Grades: {summ}. No I.",
        "",
    ]
    return "\n".join(header + lines) + "\n", "\n".join(rows) + "\n", grades


def main():
    reading, tokens, grades = build()
    files = {"reading.txt": reading, "reading_tokens.tsv": tokens}
    if "--check" in sys.argv:
        bad = [n for n, c in files.items()
               if not os.path.exists(os.path.join(HERE, n)) or open(os.path.join(HERE, n), encoding="utf-8").read() != c]
        if bad:
            print("STALE:", ", ".join(bad))
            sys.exit(1)
        print("OK", dict(grades))
        return
    for n, c in files.items():
        open(os.path.join(HERE, n), "w", encoding="utf-8").write(c)
    print("wrote", ", ".join(files), dict(grades))


if __name__ == "__main__":
    main()
