#!/usr/bin/env python3
"""VERIFY-F61-V6 (29 Sept 2026) task 1: the bowl question re-run blind on the verifier's own crops. Written before any vision call.
 tiles SCRATCH  cuts every item in a framing different from the runner's (narrower window, larger scale, BLUE marker, own seeds) and writes
                items_v6.tsv (item -> call, set, leaf, position, code, letter where one exists). Letters never appear on a sheet.
   call 1: control K01-K20 = the runner's own H193 anchor strips, cut out of <SCRATCH>/h193/sheet_0*.jpg (regenerated by h193_attr.py
           tiles, h193_items.tsv reproduced byte-identical) on a sheet of their own;
           plus, mixed and shuffled (seed 606): the same 20 f.176v anchors re-cut in the verifier's framing (set FA), H193's 40 f.176r targets
           re-cut (set RT), and 40 fresh f.176r 4-family columns of ANY reader code paired with c/p (20) or a/n (20) under the runner's
           alignment (key v4, whose 4TRI set a/c/n/p/t cannot favour c/p over a/n), H193 targets excluded (set RN, seed 606).
   call 2: K01-K20 again; FA again (reshuffled, seed 607) mixed with f.108v's 74 H199 columns (set V8) and f.108r's 20 H202 gloss positions
           (set R8), each re-cut (f.108v from the native, marker ABOVE because the leaf's gloss sits below; f.108r from images/f108sheetB).
   call 3: K01-K20 again; FA again (seed 608); the six f.61 span lines (L01 L03 L05 L07 L08 L11) re-cut by the verifier from the native
           region (slope fits from tools/iiif_lines.py, two halves per line with no overlap, 1.3x), the reader lists every figure-4-shaped
           sign left to right and answers the bowl question for each (H194's list method; a line whose listed count differs from its
           4-family code count is left out).
 score (score_v6.py) GATE per call: K >= 17/20 (the runner's gate on the runner's strips) AND FA >= 17/20; else that call's targets are
   not scored.
  python3 tiles_v6.py tiles SCRATCH"""
import os, random, sys
HERE = os.path.dirname(os.path.abspath(__file__)); FAMD = os.path.abspath(f"{HERE}/../family"); IM = os.path.abspath(f"{HERE}/../images")
sys.path.insert(0, HERE); sys.path.insert(0, FAMD); sys.path.insert(0, os.path.abspath(f"{HERE}/../scripts"))
from PIL import Image, ImageDraw
TW, TH = 370, 230
BLUE = (0, 70, 220)
def tile(win, label, marker_x, above=False):
    c = Image.new("RGB", (TW, TH), "white"); top = 22 if above else 0; c.paste(win, (5, top)); d = ImageDraw.Draw(c); mx = 5 + marker_x
    if above: d.polygon([(mx - 9, 3), (mx + 9, 3), (mx, 19)], fill=BLUE)
    else:
        y = win.height; d.polygon([(mx - 9, y + 17), (mx + 9, y + 17), (mx, y + 2)], fill=BLUE)
    d.text((6, TH - 14), label, fill=(0, 0, 0)); return c
def band_win(path, x, half=110, scale=1.6):
    im = Image.open(path).convert("RGB"); x0 = max(0, min(im.width - 2 * half, x - half)); w = im.crop((x0, 0, x0 + 2 * half, im.height))
    s = min(scale, 360 / w.width, 190 / w.height); return w.resize((int(w.width * s), int(w.height * s))), int((x - x0) * s)
def sheets(ims, prefix, scratch):
    out = []
    for s in range(0, len(ims), 20):
        sh = Image.new("RGB", (4 * TW, 5 * TH), "white")
        for k, c in enumerate(ims[s:s + 20]): sh.paste(c, ((k % 4) * TW, (k // 4) * TH))
        f = f"{scratch}/v6/{prefix}_{s // 20 + 1:02d}.jpg"; sh.save(f, quality=90); out.append(f)
    return out
def main(scratch):
    import h193_attr as H, h199_bowl_108v as h199, h202_bowl_108r as h202, json
    from align_check import fam
    os.makedirs(f"{scratch}/v6", exist_ok=True); g = H.g
    key = ["item\tcall\tset\tleaf\tline\tsegment\tx_px\tcode\tletter\tsource"]
    h193 = list(g.rd(f"{FAMD}/h193_items.tsv"))
    # K: runner's anchor strips cut out of the runner's sheets (Qnn at sheet (n-1)//20, cell (n-1)%20 of a 4x5 grid of 370x190)
    ks = [r for r in h193 if r["group"] in ("CP", "AN")]; random.Random(605).shuffle(ks); kims = []
    for n, r in enumerate(ks, 1):
        q = int(r["item"][1:]) - 1; sh = Image.open(f"{scratch}/h193/sheet_{q // 20 + 1:02d}.jpg"); k = q % 20
        t = sh.crop(((k % 4) * 370, (k // 4) * 190, (k % 4) * 370 + 370, (k // 4) * 190 + 172)); c = Image.new("RGB", (370, 190), "white"); c.paste(t, (0, 0))
        ImageDraw.Draw(c).text((6, 174), f"K{n:02d}", fill=(0, 0, 0)); kims.append(c)
        key.append(f"K{n:02d}\tall\tK\t176v\t{r['line']}\t{r['segment']}\t{r['x_px']}\t-\t{r['letter']}\t{r['group']} (runner strip {r['item']})")
    sh = Image.new("RGB", (4 * 370, 5 * 190), "white")
    for k, c in enumerate(kims): sh.paste(c, ((k % 4) * 370, (k // 4) * 190))
    sh.save(f"{scratch}/v6/control_K.jpg", quality=90)
    def fa_items():
        return [dict(set="FA", leaf="176v", line=r["line"], segment=r["segment"], x=int(r["x_px"]), code="-", letter=r["letter"], src=r["group"],
                     path=f"{scratch}/f176v/f176v_{r['line']}_{r['segment']}.jpg") for r in h193 if r["group"] in ("CP", "AN")]
    # call 1: f.176r
    import glob
    lines = {}
    for f in sorted(glob.glob(f"{H.b.P}/f177v_clearA_*.tsv")):
        for r in g.rd(f): lines.setdefault("V" + r["line"].lstrip("LV"), r["text"])
    sr, orr = H.cons_origin(H.rows_full("f176r_signsA_*.tsv"), H.rows_full("f176r_signsB_*.tsv"), [f"L{k:02d}" for k in range(1, 48)])
    tr = H.v.clear177r() + "".join(g.fold(lines[f"V{k:02d}"]) for k in range(1, 6)); tr = tr[:len(sr)]
    pr = H.paired(sr, orr, tr); tset = {(r["line"], r["segment"], int(r["x_px"])) for r in h193 if r["group"] == "T"}
    rt = [dict(set="RT", leaf="176r", line=r["line"], segment=r["segment"], x=int(r["x_px"]), code="4TRI", letter=r["letter"], src=r["item"],
               path=f"{scratch}/f176r/f176_{r['line']}_{r['segment']}.jpg") for r in h193 if r["group"] == "T"]
    pool = [(s, o, L) for s, o, L in pr if fam(s) and o not in tset and L in "cpan"]; rng = random.Random(606)
    cp = rng.sample([p for p in pool if p[2] in "cp"], 20); an = rng.sample([p for p in pool if p[2] in "an"], 20)
    rn = [dict(set="RN", leaf="176r", line=o[0], segment=o[1], x=o[2], code=s, letter=L, src="fresh", path=f"{scratch}/f176r/f176_{o[0]}_{o[1]}.jpg") for s, o, L in cp + an]
    def build(call, items, seed, prefix, pre):
        random.Random(seed).shuffle(items); ims = []
        for n, it in enumerate(items, 1):
            lab = f"{pre}{n:03d}"
            if it.get("win") is not None: w, mx, ab = it["win"]
            else: (w, mx), ab = band_win(it["path"], it["x"]), False
            ims.append(tile(w, lab, mx, above=ab))
            key.append(f"{lab}\t{call}\t{it['set']}\t{it['leaf']}\t{it['line']}\t{it['segment']}\t{it['x']}\t{it['code']}\t{it['letter']}\t{it['src']}")
        return sheets(ims, prefix, scratch)
    f1 = build(1, fa_items() + rt + rn, 606, "c1", "A")
    # call 2: f.108v (native, marker above) and f.108r (sheet B bands)
    nat = Image.open(f"{FAMD}/images/3983_f108v.jpg").convert("RGB"); B = {}
    for j in ("f108v3y_bands.json", "f108v3z_bands.json"): B.update(json.load(open(f"{FAMD}/sheets/{j}"))["boxes"])
    v8 = []
    for t in h199.targets():
        bx = B[os.path.basename(h199.crop(t["line"], t["segment"]))]; x = bx[0] + int(t["x_px"]) // 3; y0, y1 = bx[1] + 10, bx[3] + 40
        w = nat.crop((x - 95, y0, x + 95, y1)); s = min(1.8, 360 / w.width, 185 / w.height); w = w.resize((int(w.width * s), int(w.height * s)))
        v8.append(dict(set="V8", leaf="108v", line=t["line"], segment=t["column"], x=t["x_px"], code=f"{t['rec']}|{t['A']}|{t['B']}", letter="-", src="H199", win=(w, int(95 * s), True)))
    r8 = []
    for t in h202.pairs():
        im = Image.open(f"{IM}/f108sheetB_{t['row']}.jpg").convert("RGB"); st = (im.height + 12) // 4; y0 = (t["seg"] - 1) * st; y1 = y0 + st - 12
        x0 = max(0, min(im.width - 240, t["x"] - 120)); w = im.crop((x0, y0, x0 + 240, y1)); s = min(1.5, 360 / w.width, 190 / w.height)
        w = w.resize((int(w.width * s), int(w.height * s)))
        r8.append(dict(set="R8", leaf="108r", line=t["row"], segment=t["pos"], x=t["x"], code=t["code"], letter=t["letter"], src="H202", win=(w, int((t["x"] - x0) * s), False)))
    f2 = build(2, fa_items() + v8 + r8, 607, "c2", "B")
    # call 3: f.61 lines, verifier's cut
    f3 = build(3, fa_items(), 608, "c3", "C")
    src = Image.open(f"{IM}/src_ark_12148_btv1b52509819x_f137_500_1880_3320_1420.jpg").convert("L"); slopes = {}
    for l in open(f"{scratch}/f61_slopes.txt"):
        a, b, c = l.split(); slopes[a] = (float(b), float(c))
    import numpy as np
    A = np.array(src); f61 = []
    for ln in ("L01", "L03", "L05", "L07", "L08", "L11"):
        a, b = slopes[ln]; H0 = 150; strip = np.full((H0, A.shape[1]), 255, np.uint8)
        for x in range(A.shape[1]):
            yc = int(round(a + b * x)); ya, yb = max(0, yc - 75), min(A.shape[0], yc + 75); strip[(ya - (yc - 75)):(yb - (yc - 75)), x] = A[ya:yb, x]
        halves = [Image.fromarray(strip[:, :1660]), Image.fromarray(strip[:, 1660:])]
        halves = [h.resize((int(h.width * 1.3), int(h.height * 1.3)), Image.LANCZOS) for h in halves]
        sh = Image.new("RGB", (halves[0].width, halves[0].height * 2 + 14), "white"); d = ImageDraw.Draw(sh)
        sh.paste(halves[0].convert("RGB"), (0, 0)); d.rectangle((0, halves[0].height, sh.width, halves[0].height + 13), fill=(0, 0, 0))
        sh.paste(halves[1].convert("RGB"), (0, halves[0].height + 14)); d.text((6, 4), "part 1", fill=(200, 0, 0)); d.text((6, halves[0].height + 18), "part 2", fill=(200, 0, 0))
        f = f"{scratch}/v6/f61_{ln}.jpg"; sh.save(f, quality=90); f61.append(f)
    open(f"{HERE}/items_v6.tsv", "w").write("\n".join(key) + "\n")
    print("call 1:", f1, "\ncall 2:", f2, "\ncall 3:", f3, f61, "\ncontrol:", f"{scratch}/v6/control_K.jpg")
    from collections import Counter
    print(Counter(r.split("\t")[1] + ":" + r.split("\t")[2] for r in key[1:]))
if __name__ == "__main__": main(sys.argv[2])
