#!/usr/bin/env python3
"""Trial of the letter-symbol alphabet of George Lasry's Sabran (1631) key (BnF fr.4134 / Baluze 155 f.79, via
Cryptiana GL.htm) on the letter-symbol tokens of Baluze 156 f.157r (DC8), with matched controls. 24 Sept 2026.
--key2 switches to key_sabran2_letters.tsv (Lasry's second Sabran-circle key, Baluze 156 f.40, the Farnese-to-
Sabran break, fetched and matched 25 Sept 2026) and writes letters_trial2.tsv instead, same method.

Inputs: ciphertext_draft.tsv (reconciled two-pass transcription) and a key_*_letters.tsv, whose `dc8_token`
column records which DC8 transcription token each key glyph was matched to by shape (eye comparison of the key
image with images/dc8_f157r.jpg). Tokens with no shape match stay unmapped and break the run.

Scores (period French 5-gram model, tools/french16_ngram.py), mean bits/char over the mapped letters:
  real      the key-derived mapping applied to DC8
  shuffle   1000 draws: the same mapping's letter values permuted over the same token classes
  positive  synthetic French text of the same letter count (random corpus windows), enciphered with the key's
            homophones under the same token classes, same share of unmapped breaks, decoded with the mapping
  pos_shuf  the positive text decoded with 1000 shuffled mappings (the detection margin at this length)

  python3 letters_trial.py           # print and rewrite letters_trial.tsv (first Sabran key)
  python3 letters_trial.py --check   # exit 1 if letters_trial.tsv is stale
  python3 letters_trial.py --key2 [--check]   # same, for the second (Farnese-to-Sabran) key
"""
import csv, os, sys, random, itertools
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', 'tools'))
from french16_ngram import load

def read_tsv(fn):
    with open(os.path.join(HERE, fn), encoding='utf-8') as f:
        return list(csv.DictReader((l for l in f if not l.startswith('#')), delimiter='\t'))

KEY2 = '--key2' in sys.argv
key_fn = 'key_sabran2_letters.tsv' if KEY2 else 'key_sabran_1631_letters.tsv'
out_fn = 'letters_trial2.tsv' if KEY2 else 'letters_trial.tsv'
key = read_tsv(key_fn)
MAP = {}
for r in key:
    t = r['dc8_token'].strip()
    if t and t != '-':
        if t in MAP and MAP[t] != r['letter']:
            sys.exit(f'token {t} matched to two letters')
        MAP[t] = r['letter']
rows = read_tsv('ciphertext_draft.tsv')
lines = [[r['sign'] for r in g] for _, g in itertools.groupby(rows, key=lambda r: r['line'])]

def runs(tokens_lines, mp):
    out = []
    for toks in tokens_lines:
        cur = ''
        for t in toks:
            if t in mp: cur += mp[t]
            else:
                if cur: out.append(cur)
                cur = ''
        if cur: out.append(cur)
    return out

M = load()
def bpc(rs):
    n = sum(len(r) for r in rs)
    return -sum(M.logp(r) for r in rs) / n if n else float('nan')

def shuffled(mp, rng):
    ks = list(mp); vs = [mp[k] for k in ks]; rng.shuffle(vs)
    return dict(zip(ks, vs))

rng = random.Random(1636)
real_runs = runs(lines, MAP)
n_letters = sum(len(r) for r in real_runs)
n_tokens = sum(len(l) for l in lines)
real = bpc(real_runs)
shuf = sorted(bpc(runs(lines, shuffled(MAP, rng))) for _ in range(1000))
pct = sum(s <= real for s in shuf) / len(shuf)          # share of shuffles scoring as well or better

# positive control: synthetic French, same letter count, same run structure, enciphered with the key's
# homophones (every token class that maps to the letter), decoded with MAP
inv = {}
for t, l in MAP.items(): inv.setdefault(l, []).append(t)
text = ''.join(M._held)                                   # held-out period French, not used to train the model
lens = [len(r) for r in real_runs]
start = rng.randrange(0, len(text) - 5 * n_letters)
plain = ''
i = start
for L in lens:
    plain += text[i:i + L]; i += L + 7                   # gaps stand in for the unmapped breaks
syn_lines, cov = [], 0
for L, seg in zip(lens, [plain[sum(lens[:k]):sum(lens[:k + 1])] for k in range(len(lens))]):
    toks = []
    for ch in seg:
        if ch in inv: toks.append(rng.choice(inv[ch])); cov += 1
        else: toks.append('?' + ch)                      # key letter with no DC8 shape class: an unmapped break
    syn_lines.append(toks)
pos = bpc(runs(syn_lines, MAP))
pos_shuf = sorted(bpc(runs(syn_lines, shuffled(MAP, rng))) for _ in range(1000))
pos_pct = sum(s <= pos for s in pos_shuf) / len(pos_shuf)

counts = {}
for r in real_runs:
    for ch in r: counts[ch] = counts.get(ch, 0) + 1
vowels = sum(counts.get(v, 0) for v in 'AEIOVY') / n_letters
long_words = sorted({w for r in real_runs for a in range(len(r)) for b in range(a + 4, len(r) + 1)
                     if (w := r[a:b]) in M.words and M.words[w] >= 20})
syn_vowels = sum(ch in 'AEIOVY' for ch in plain) / len(plain)

out = [(f'# {out_fn} -- regenerated by letters_trial.py{" --key2" if KEY2 else ""} (24 Sept 2026); French 5-gram bits/char, lower = more French', ''),
       ('token_classes_mapped', len(MAP)), ('dc8_tokens', n_tokens), ('dc8_letters_mapped', n_letters),
       ('real_bpc', f'{real:.3f}'), ('shuffle_draws', 1000), ('shuffle_median_bpc', f'{shuf[500]:.3f}'),
       ('shuffle_best_bpc', f'{shuf[0]:.3f}'), ('real_share_of_shuffles_as_good_or_better', f'{pct:.3f}'),
       ('positive_control_letters', len(plain)), ('positive_control_bpc', f'{pos:.3f}'),
       ('positive_shuffle_median_bpc', f'{pos_shuf[500]:.3f}'),
       ('positive_share_of_shuffles_as_good_or_better', f'{pos_pct:.3f}'),
       ('real_vowel_share_AEIOVY', f'{vowels:.3f}'), ('synthetic_vowel_share_AEIOVY', f'{syn_vowels:.3f}'),
       ('real_words_ge4_in_decode', ' '.join(long_words) or '(none)'),
       ('real_decode_runs', ' '.join(real_runs)),
       ('verdict', 'reads' if pct < 0.01 and real < pos + 0.5 else 'does not read (negative, matched)')]
body = '\n'.join(f'{k}\t{v}' if v != '' else k for k, v in out) + '\n'
fn = os.path.join(HERE, out_fn)
if '--check' in sys.argv:
    old = open(fn, encoding='utf-8').read() if os.path.exists(fn) else ''
    if old != body:
        print('letters_trial.tsv is stale'); sys.exit(1)
    print('letters_trial.tsv up to date'); sys.exit(0)
open(fn, 'w', encoding='utf-8').write(body)
print(body)
