#!/usr/bin/env python3
"""Re-score of Baluze 156 f.157r (DC8) under the merged Sabran 1636 table (fr.4140 f.146r key + f.247r key),
on the 3 Oct 2026 re-read transcription (GAPS35, account-4). Pre-registered in PREREG_reread.md before any token of
the re-read was scored.

Merged key: images/fr4140/key_f146.tsv and images/f247/key_f247.tsv, 'kept' rows only. A sign in one key only keeps
that value; a sign in both keys keeps it when the letters agree and is dropped when they differ. Aliases: f.146r's
'P' and f.247's 'Pc' are the same looped a-sign (FT4d), so both names map to it.
Rows scored (same scorer as f247_trial.py / fr4140_trial.py: French 5-gram bits/char, tools/french16_ngram.py,
unmapped token breaks a run):
  A  the 24 Sept draft (ciphertext_draft.tsv) under the merged key        (old transcription, for comparison)
  B  the 3 Oct re-read (ciphertext_reread.tsv) under the merged key       (the pre-registered test)
Control for each row: 200 shuffled merged keys (the key's letters permuted over its signs) -- the decode's letters,
hence bits/char, change with every permutation, so the control can differ from the target on the statistic.
Positive control: held-out French of row B's run lengths enciphered with the merged key, decoded with it.
Gate (as FT4b/FT4d): 'reads' only if share of shuffles as good < 0.01 AND real bpc < positive + 0.5.

  python3 reread_trial.py           # print and rewrite reread_trial.tsv, reread_decode.txt
  python3 reread_trial.py --check   # exit 1 if stale
"""
import csv, os, sys, random, itertools
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', 'tools'))
from french16_ngram import load

N_SHUF = 200


def read_tsv(fn):
    with open(fn, encoding='utf-8') as f:
        return list(csv.DictReader((l for l in f if not l.startswith('#')), delimiter='\t'))


def kept(fn):
    return {r['sign']: r['letter'].upper().replace('U', 'V').replace('J', 'I')
            for r in read_tsv(fn) if r['status'] == 'kept'}


k146 = kept(os.path.join(HERE, 'images', 'fr4140', 'key_f146.tsv'))
k247 = kept(os.path.join(HERE, 'images', 'f247', 'key_f247.tsv'))
if 'P' in k146: k146['Pc'] = k146.pop('P')
key, conflicts = {}, []
for s in sorted(set(k146) | set(k247)):
    vals = {k[s] for k in (k146, k247) if s in k}
    if len(vals) == 1: key[s] = vals.pop()
    else: conflicts.append(f"{s}:{'/'.join(sorted(vals))}")
key['P'] = key.get('Pc', 'A')

M = load()
_cache = {}
def lp(s):
    if s not in _cache: _cache[s] = M.logp(s)
    return _cache[s]

def runs(tl, mp):
    out = []
    for toks in tl:
        cur = ''
        for t in toks:
            if t in mp: cur += mp[t]
            else:
                if cur: out.append(cur)
                cur = ''
        if cur: out.append(cur)
    return out

def bpc(rs):
    n = sum(len(r) for r in rs)
    return -sum(lp(r) for r in rs) / n if n else float('nan')

signs, vals = list(key), [key[s] for s in key]

def score(fn, rng):
    rows = read_tsv(os.path.join(HERE, fn))
    lines = [[r['sign'] for r in g] for _, g in itertools.groupby(rows, key=lambda r: r['line'])]
    rr = runs(lines, key)
    real = bpc(rr)
    sh = []
    for _ in range(N_SHUF):
        vs = vals[:]; rng.shuffle(vs)
        sh.append(bpc(runs(lines, dict(zip(signs, vs)))))
    sh.sort()
    words = sorted({w for r in rr for a in range(len(r)) for b in range(a + 4, len(r) + 1)
                    if (w := r[a:b]) in M.words and M.words[w] >= 20})
    return dict(rows=rows, n=sum(map(len, lines)), cov=sum(t in key for l in lines for t in l), runs=rr, real=real,
                med=sh[N_SHUF // 2], best=sh[0], pct=sum(s <= real for s in sh) / N_SHUF, words=words)

rng = random.Random(1636157)
A = score('ciphertext_draft.tsv', rng)
B = score('ciphertext_reread.tsv', rng)
inv = {}
for s, v in key.items(): inv.setdefault(v, []).append(s)
text = ''.join(M._held)
i = rng.randrange(0, len(text) - 5 * max(1, sum(map(len, B['runs']))))
segs = []
for L in [len(r) for r in B['runs']]: segs.append(text[i:i + L]); i += L + 7
syn = [[rng.choice(inv[ch]) if ch in inv else '?' for ch in seg] for seg in segs]
pos = bpc(runs(syn, key))
pos_sh = []
for _ in range(N_SHUF):
    vs = vals[:]; rng.shuffle(vs)
    pos_sh.append(bpc(runs(syn, dict(zip(signs, vs)))))
pos_pct = sum(s <= pos for s in pos_sh) / N_SHUF
verdict = 'reads' if B['pct'] < 0.01 and B['real'] < pos + 0.5 else 'does not read (negative, matched)'

out = [('# reread_trial.tsv -- regenerated by reread_trial.py (3 Oct 2026); bits/char lower = more French', ''),
       ('merged_key_signs', len(key)), ('merged_key', ' '.join(f'{s}={v}' for s, v in sorted(key.items()))),
       ('conflicts_dropped', ' '.join(conflicts) or '(none)')]
for tag, R in (('A_draft', A), ('B_reread', B)):
    out += [(f'{tag}_tokens', R['n']), (f'{tag}_covered', R['cov']), (f'{tag}_letters', sum(map(len, R['runs']))),
            (f'{tag}_real_bpc', f"{R['real']:.3f}"), (f'{tag}_shuffle_median_bpc', f"{R['med']:.3f}"),
            (f'{tag}_shuffle_best_bpc', f"{R['best']:.3f}"), (f'{tag}_share_shuffles_as_good', f"{R['pct']:.3f}"),
            (f'{tag}_words_ge4', ' '.join(R['words']) or '(none)'), (f'{tag}_decode_runs', ' '.join(R['runs']))]
out += [('positive_control_bpc', f'{pos:.3f}'), ('positive_share_shuffles_as_good', f'{pos_pct:.3f}'),
        ('verdict_B', verdict)]
body = '\n'.join(f'{k}\t{v}' if v != '' else k for k, v in out) + '\n'
dec = []
for l, g in itertools.groupby(B['rows'], key=lambda r: r['line']):
    dec.append(l + '\t' + ' '.join(f"{r['sign']}={key.get(r['sign'], '?')}" for r in g))
files = {os.path.join(HERE, 'reread_trial.tsv'): body, os.path.join(HERE, 'reread_decode.txt'): '\n'.join(dec) + '\n'}
if '--check' in sys.argv:
    stale = [f for f, b in files.items() if not os.path.exists(f) or open(f, encoding='utf-8').read() != b]
    if stale: print('stale:', ' '.join(map(os.path.basename, stale))); sys.exit(1)
    print('reread trial files up to date'); sys.exit(0)
for f, b in files.items(): open(f, 'w', encoding='utf-8').write(b)
print(body)
