#!/usr/bin/env python3
"""Mechanical trial of the published Sabran (1631) nomenclator (key_sabran_1631.tsv) against this
target's own blind transcription (passA.tsv), with a shuffled-key control (rule 3: no negative
without a matched control). Reproducible: regenerates trial.tsv from the two inputs each run.

This only tests the KEY'S NOMENCLATOR NUMBERS (two-digit word/syllable codes) against the numeric
cipher tokens in passA.tsv -- it does not attempt the separate hand-drawn letter-symbol alphabet,
which cannot be matched mechanically from a plain-text transcription (see NOTES.md).

Usage: python3 trial.py [--check]
--check: exit non-zero if trial.tsv is stale (rule 7).
"""
import csv
import random
import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
PASSA = HERE / "passA.tsv"
KEY = HERE / "key_sabran_1631.tsv"
OUT = HERE / "trial.tsv"

random.seed(24092026)  # reproducible shuffle, dated per rule 6 convention


def load_key_numbers():
    nums = []
    with open(KEY, encoding="utf-8") as f:
        lines = [l for l in f if not l.startswith("#")]
        for row in csv.DictReader(lines, delimiter="\t"):
            if row.get("kind") == "nomenclator":
                code = row["code_or_sign"].strip()
                if code.isdigit():
                    nums.append(int(code))
    return sorted(set(nums))


def load_cipher_tokens():
    """Pull numeric substrings out of passA.tsv's non-[PLAIN] groups."""
    tokens = []
    with open(PASSA, encoding="utf-8") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            g = (row.get("group") or "").strip()
            if not g or g.startswith("[PLAIN:") or g.startswith("#"):
                continue
            for m in re.finditer(r"\d+", g):
                if len(m.group()) <= 2:
                    tokens.append(int(m.group()))
    return tokens


def main():
    check = "--check" in sys.argv
    if not PASSA.exists():
        print(f"{PASSA} missing -- run the transcription pass first", file=sys.stderr)
        return 2

    key_numbers = load_key_numbers()
    tokens = load_cipher_tokens()
    n_key = len(key_numbers)
    n_tok = len(tokens)

    real_hits = sum(1 for t in tokens if t in key_numbers)
    real_rate = real_hits / n_tok if n_tok else 0.0

    # Shuffled-key control: draw n_key distinct random values in [0,99] (excluding the real key's
    # own numbers is not required -- the control asks "how often would an unrelated set of this
    # size hit these tokens by chance", not "a permutation of the same key"), 1000 draws, report
    # the mean and the max (the strongest control run) alongside the real rate.
    draws = 1000
    control_rates = []
    universe = list(range(0, 100))
    for _ in range(draws):
        shuffled = set(random.sample(universe, k=min(n_key, 100)))
        hits = sum(1 for t in tokens if t in shuffled)
        control_rates.append(hits / n_tok if n_tok else 0.0)
    control_mean = sum(control_rates) / len(control_rates)
    control_max = max(control_rates)

    lines = []
    lines.append("# trial.tsv -- mechanical trial of key_sabran_1631.tsv's nomenclator numbers against")
    lines.append("# passA.tsv's numeric cipher tokens, with a shuffled-key control (1000 draws of a")
    lines.append("# same-size random subset of 0-99), regenerated by trial.py, 24 Sept 2026.")
    lines.append("metric\tvalue")
    lines.append(f"n_key_numbers\t{n_key}")
    lines.append(f"n_cipher_tokens\t{n_tok}")
    lines.append(f"real_hits\t{real_hits}")
    lines.append(f"real_hit_rate\t{real_rate:.4f}")
    lines.append(f"control_draws\t{draws}")
    lines.append(f"control_mean_hit_rate\t{control_mean:.4f}")
    lines.append(f"control_max_hit_rate\t{control_max:.4f}")
    verdict = "ABOVE control (candidate match, needs follow-up)" if real_rate > control_max else "NOT above control (negative, matched)"
    lines.append(f"verdict\t{verdict}")
    new_content = "\n".join(lines) + "\n"

    if check:
        if not OUT.exists() or OUT.read_text() != new_content:
            print("trial.tsv is stale (committed file does not match a fresh run)", file=sys.stderr)
            return 1
        print("trial.tsv is up to date")
        return 0

    OUT.write_text(new_content)
    print(f"key numbers: {n_key}, cipher tokens: {n_tok}, real hits: {real_hits} ({real_rate:.1%})")
    print(f"control mean {control_mean:.1%}, control max {control_max:.1%} over {draws} draws")
    return 0


if __name__ == "__main__":
    sys.exit(main())
