#!/usr/bin/env python3
"""WV2 build (LANE R2 W1, 24 Sept 2026): per letter, reconcile pass A/B page files with tools/reconcile_passes.py into
wv2/recon/<nr>/, join the pages' drafts into ciphertext_<nr>.tsv (target root), apply settled rows from
wv2/settle_<nr>.tsv (line, position, sign, why: settled on the image by W1), and write decode_wv2.json for
tools/decode_key.py --config decode_wv2.json.   python3 wv2/build.py [nr ...]
"""
import sys, os, csv, glob, json, subprocess
H = os.path.dirname(os.path.abspath(__file__)); T = os.path.dirname(H)
REC = os.path.join(T, '..', '..', 'tools', 'reconcile_passes.py')
DATES = {'04503': '15 Apr 1574', '05194': '24 June 1572', '05797': '22 Oct 1573', '05799': '3 Apr 1573',
         '05810': '6 Jan 1574', '05811': '13 Apr 1574'}
def build(nr):
    allp = sorted({os.path.basename(p) for p in glob.glob(f'{H}/pass[AB]/{nr}_p*.tsv')})
    if not allp: return False
    rows = []
    for pg in allp:
        if not (os.path.exists(f'{H}/passA/{pg}') and os.path.exists(f'{H}/passB/{pg}')):
            # one pass only (pass A stopped at its cap): every sign M, why 'single pass'
            src = f'{H}/passA/{pg}' if os.path.exists(f'{H}/passA/{pg}') else f'{H}/passB/{pg}'
            for r in csv.DictReader(open(src), delimiter='\t'):
                s = r['sign']; q = s.endswith('?')
                rows.append({'line': r['line'], 'position': r['pos'], 'sign': s.rstrip('?') if q and s != '?' else s,
                             'confidence': 'M', 'alt': '', 'why': 'single pass ' + src.split('/')[-2]})
            continue
        out = f'{H}/recon/{nr}/{pg[:-4]}'; os.makedirs(out, exist_ok=True)
        pa, pb = f'{H}/passA/{pg}', f'{H}/passB/{pg}'
        lm = {}
        if os.path.exists(f'{H}/linemap.tsv'):
            lm = {(r['pass'], r['from_line']): r['to_line'] for r in csv.DictReader(open(f'{H}/linemap.tsv'), delimiter='\t')
                  if r['page'] == pg[:-4]}
        if lm:   # renumber a pass's lines (wv2/linemap.tsv) before aligning; the raw pass files stay untouched
            for x in 'AB':
                src = pa if x == 'A' else pb
                if any(k[0] == x for k in lm):
                    rr = list(csv.DictReader(open(src), delimiter='\t')); fn = rr and list(rr[0].keys())
                    for r in rr: r['line'] = lm.get((x, r['line']), r['line'])
                    dst = f'{out}/pass{x}_mapped.tsv'
                    with open(dst, 'w', newline='') as fo:
                        w = csv.DictWriter(fo, fn, delimiter='\t', lineterminator='\n'); w.writeheader(); w.writerows(rr)
                    if x == 'A': pa = dst
                    else: pb = dst
        subprocess.run([sys.executable, REC, pa, pb, '--out-dir', out], check=True,
                       stdout=subprocess.DEVNULL)
        rows += list(csv.DictReader(open(f'{out}/ciphertext_draft.tsv'), delimiter='\t'))
    st = f'{H}/settle_{nr}.tsv'
    if os.path.exists(st):
        fix = {(r['line'], r['position']): r for r in csv.DictReader(open(st), delimiter='\t')}
        for r in rows:
            f = fix.get((r['line'], r['position']))
            if f: r.update(sign=f['sign'], confidence='H', why='settled on image by W1: ' + f['why'])
    with open(f'{T}/ciphertext_{nr[1:]}.tsv', 'w', newline='') as fo:
        w = csv.DictWriter(fo, ['line', 'position', 'sign', 'confidence', 'alt', 'why'], delimiter='\t', lineterminator='\n')
        w.writeheader(); [w.writerow({k: r.get(k, '') for k in w.fieldnames}) for r in rows]
    return True
def job(nr):
    n = nr[1:]
    return {"ciphertext": f"ciphertext_{n}.tsv", "key": "key.tsv", "format": "tsv", "style": "concat", "clear_prefix": "=",
            "nonsign": ["[blank]", "[blot]", "[spot]", "[sym]"], "null_values": ["NULL"], "unknown_values": ["", "?", "-"],
            "default_grade": "C", "reading": f"reading_{n}.txt", "tokens": f"reading_{n}_tokens.tsv",
            "header": [f"# Generated by tools/decode_key.py --config decode_wv2.json from ciphertext_{n}.tsv + key.tsv (W1, 24 Sept 2026); do not edit.",
                       f"# WV2 letter {n} ({DATES[nr]}), two blind Sonnet passes reconciled by wv2/build.py; key R18's (4613/4615). tokens {{total}}: {{HCSMIU}}"],
            "token_columns": [["line", "line"], ["idx", "pos"], ["sign", "raw"], ["value", "value"], ["grade", "grade"]]}
# letters whose numeral runs read as French under key.tsv (wv2/table_test.py, k=0 near the siblings' 3.1 b/c);
# only these get a graded reading; the others keep ciphertext_<nr>.tsv only.
KEYED = {'05811', '05810', '04503'}
if __name__ == '__main__':
    nrs = sys.argv[1:] or sorted(DATES)
    done = [nr for nr in nrs if build(nr)]
    have = [nr for nr in sorted(KEYED) if os.path.exists(f'{T}/ciphertext_{nr[1:]}.tsv')]
    json.dump({"target": "ciphers/lodewijk-van-nassau-1573-74", "jobs": [job(nr) for nr in have]},
              open(f'{T}/decode_wv2.json', 'w'), indent=1)
    print('built', done, 'config jobs', have)
