#!/usr/bin/env python3
"""MS18-R5: file the ten ms18_r5_entries.txt rows X1-X10 into ../ciphertext.txt (Cipher No. 1) as E351-E360. Usage: ms18_r5_file.py [--dry]  Idempotent.
All ten pages image-read at 2400 px (whole page, own entry). X11, X12 (spares) are not filed. Trailing lines that are the next entry's label/time (X3, X5, X7, X8) are dropped."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
def d(page, ptr, row, pp, rest, chk="image-read at 2400 px"): return f"Page {page} | {ptr} | mssEC 18 (obj 10074, pointer {ptr}; printed page {pp}), {rest} (MS18-R5; row {row}; {chk})"
DROP = {"X3": ["No 2  730 Pm"], "X5": ["No 2  1020 Pm"], "X7": ["(No 1)  3 PM"], "X8": ["no 1  1030 am"]}
MAP = {
 "X1": ("E351", d(405, 10065, "10065/2", 399, "2 Dec 1865 Washington, to Bodle at Baltimore for Maj. Gen. Hancock, signed Ed. Townsend, Asst Adjt Genl: yours of this date received; the Secretary of War says the habeas corpus in case of minors is not to be resisted; defend the case as well as possible without counsel unless there is some peculiar point; report the names of the officers by whom the minors discharged were illegally enlisted; acknowledge receipt"),
   ["note: MS18-R5: read with No. 1 (1865 HEAD share No.1 .29 / No.2 .29 / No.9 .16: a tie; the sense reads and the shuffled copies give Butler/Delaware nonsense; no leaf label on this entry, the page's 'No 6 card' heads the Cobb/Logan 23 Nov 1865 entry above, plain). Image: transcription matches line by line. Plain: Bodle, Balto, Dec 2 1865, Hancock, Townsend. 'Brutus' = Secretary of War (key row). Not located in print: OR ends before Dec 1865; no volume searched covers the date; OR ser. III, Hancock's Middle Division files and the Baltimore press not searched."]),
 "X2": ("E352", d(161, 9821, "9821/1", 155, "18 Aug 1864 12.30 PM Washington, to Lawrence H. Ferry (Harpers Ferry, M), signed E. D. Townsend, A.A.Gen: the Secretary of War directs that you take and hand over to E. L. Wentz [prominent citizens (M) at Harpers Ferry (M)] who guided the raiders in their late raid; they are to be held as hostages for negroes taken by [the rebels] from the railroad [force, M]; report receipt and execution of this order"),
   ["note: MS18-R5: No. 1 (HEAD share .51 vs No. 2 .47: the sense picks the book). Image: transcription matches line by line; the entry follows a Beckwith 17 Aug 10.30 AM message (not read here). 'Infant' = Secretary of War (key row). The words 'Walpole's Saxon Weldon Saint' and the opening 'Viola for polking Shelby Camel' are read M (the decoder's 'From the Rail Road Force' and 'Harpers Ferry' are key rows applied by sense, not eye-checked against a clear copy). E. L. Wentz is plain (superintendent of military railroads of Virginia per OR I/43 pt 2). Not located in print: phrase and loose windows none in 164 volumes (the 'Wentz' and 'held as hostages for' hits are other messages, OR I/43 pt 2 pp.156,259 etc.)."]),
 "X3": ("E353", d(344, 10004, "10004/1", 338, "7 May 1865 Washington (ledger label No 1), to Macon, Ga, for Maj. Gen. Wilson (plain 'Will son'), signed Secretary of War: instructions have been sent you in regard to [Brown, M]; any other prominent rebel who may take any steps towards reorganizing rebels should be seized immediately and sent to Washington under guard; your action in respect to the reward for [Jeff Davis] is approved; the President offered a reward of $100,000 for his arrest last week"),
   ["note: MS18-R5: No. 1 (1865 HEAD share .48 vs No. 2 .40; the sense reads; 'husband' = Jeff Davis is a key row, read by sense with the 'reward' sentence). Image: transcription matches; the hour above the header is written '7.30' or '4.30 AM' (not settled; the decoder's '8 AM' is its own reading of the time word). The page's second entry (Caldwell, Richmond, label No 2, 9 May 1865, Speed/Smith reward) is not read here. Not located in print: letters-only phrase and loose windows none in 164 cached volumes; OR I/49 pt 2 (cached if present in the set) not searched individually by date; Wilson's and Stanton's papers not searched."]),
 "X4": ("E354", d(131, 9791, "9791/0", 125, "13 July 1864 4 PM Washington, to Sampson (Baltimore) for Maj. Gen. Ord, signed H. W. Halleck, Chief of Staff: the enemy left here last night and seems to be moving toward Edwards Ferry; General Grant directs that you move out of Baltimore as soon as it becomes evident that the enemy has left your front; your troops should come by railroad as far as possible and then march to Washington; the evidence is that the rebels have no troops in the direction of Baltimore except mounted guerrillas; printed OR I/37 pt 2 (Halleck to Ord, Washington 13 July 1864, 4 p.m.; page head not legible in the OCR)"),
   ["note: MS18-R5: No. 1 (HEAD share .49 vs No. 2 .45). Printed OR I/37 pt 2 (letters-only phrase hits on all four phrases, windows read): body C against that print, word for word ('General Grant directs', 'move out of Baltimore as soon as it becomes evident that the enemy has left your front', 'except mounted guerrillas'); signed H. W. Halleck, Major-General and Chief of Staff. Image: transcription matches; the page's second entry (13 July 11 PM to Rawlins at City Point, names of ships/men) is not read here. The print's page number is not read from an image. Not a key edit (rule 4)."]),
 "X5": ("E355", d(203, 9863, "9863/0", 197, "7 Oct 1864 8 PM Washington, to O'Brien (operator) for [addressee not read, M]: [the addressee's] Wm H. Stiner, reporter at [Fort] Monroe, commences to report activity in the navy, arrival of vessels and so forth; [we] understand very readily that these written accounts of such a character are about all the information the enemy wants; of what use is it to [the] northern reader; signed G. V. Fox, Asst [Secretary of the Navy]"),
   ["note: MS18-R5: No. 1 (HEAD share .45 vs No. 2 .39). Image: transcription matches line by line; the page's other two entries (Caldwell, Army of the Potomac, No 2, 7 Oct 10.20 PM; Sampson, Balt, No 1, 8 Oct, Mosby / Rockville) are not read here. The opening 'Rosalie postpone Knox zebra Sligo France Herald torch plague' is read M: the decoder's 'Maj Gen Butler / New York' for the opening words is not accepted (it comes out of the shuffled copy equally: the addressee is not established). The name 'Stiner' is plain on the page. Not located in print: letters-only phrase none in 164 volumes (OR); Navy ORN (Fox correspondence) and the New York press not searched."]),
 "X6": ("E356", d(69, 9729, "9729/2", 63, "3 May 1864 10.25 PM Washington, to Jno Horner (N.Y.) for Olcott, signed Fox, Asst [Secretary of the Navy]: the commandant at Boston ordered to bring back any witness discharged; the President of the Court ordered to get new rooms if he wishes it; Mr Goodman, late Judge Advocate, ordered to report to you and Wilson so you can go forward at once on the cases in Boston and [New York] Navy Yards"),
   ["note: MS18-R5: No. 1 (HEAD share .37 vs No. 2 .39: the share does not pick the book; the clear text is plain, H 13, and the shuffled copy reads the same words the same way, so the count control cannot fail and licenses nothing). Image: transcription matches line by line; the page's first two entries are Beckwith 2 and 3 May (Halleck-signed, not read here). 'Olcott', 'Goodman', 'Wilson' are plain on the page; 'France Navy Yards' = New York (key row, M). Not located in print: letters-only phrase none in 164 volumes; ORN and Navy Department papers not searched. The holder's short-query hit for 'Goodman Judge Advocate' is this page itself."]),
 "X7": ("E357", d(165, 9825, "9825/1", 159, "19 Aug 1864 2 PM Washington (ledger label No 2), to Beckwith at City Point for Colonel Bowers, signed Geo. K. Leet [Asst Adjt Genl]: [scouts] report that up to Wednesday last no other troops than those already reported had joined Early and none had left him; it was rumored at Orange C.H. Wednesday that Lee's cavalry had been badly beaten, losing all his artillery and many prisoners; they bring no other information"),
   ["note: MS18-R5: read with No. 1 although the ledger's own label above the header is 'No 2' (HEAD share No.1 .39 / No.2 .37: the share does not pick the book; with No. 2 the same words read Butler/Cairo/Oglesby, with No. 1 Orange C.H., Lee's cavalry, artillery: the sense picks No. 1 and the label disagrees, logged as a data conflict, not resolved by the share). Image: transcription matches line by line; the page's second entry (Sholes near Atlanta, No 1, 3 PM) is E345. 'Elgins Spit' is read M ('[scouts]'). The closing 'They bring no other information, Geo. K. Leet' matches Leet's formula in a different message (OR I/43 pt 2, 11 Oct 1864 text, Falmouth scouts): a different telegram, not this one. Not located in print: 164 volumes, loose windows none."]),
 "X8": ("E358", d(383, 10043, "10043/1", 377, "23 July 1865 8.30 PM Washington, to the Cipher Clerk at Memphis, Tenn, for Brig. Gen. Barton (plain 'Barton'), signed Secretary of War: your telegram has been received; instructions will be sent you Monday; in the meantime keep the prisoner in close and secure custody and secure his papers; telegraph in cipher briefly the substance or purport of the papers you found on him; the publication signed 'Canada' referred to I have not seen"),
   ["note: MS18-R5: No. 1 (1865 HEAD share .38 vs No. 2 .33; the sense reads; ledger label on the entry below, not this one). Image: transcription matches line by line; 'Canada' is plain. The next entry on the leaf (10043/2, 24 July 10.30 AM, Cipher Ofr Memphis, label No 1, about sending a prisoner under sufficient guard to this city to be delivered to the custody of [Taunton?]) is the same case and is not read here. 'Brutus' = Secretary of War (key row). Not located in print: 164 cached volumes (OR) none; the Memphis papers and the New York or Memphis press not searched; the prisoner is not identified."]),
 "X9": ("E359", d(93, 9753, "9753/1", 87, "4 June 1864 3.30 PM Washington, to Sampson (Baltimore) for Maj. Gen. [Lew Wallace, M], signed [General-in-Chief, M]: the 1st Maryland Veteran Cavalry [and] Battery D, 1st Maryland [Light] Artillery will be sent to Washington to report to General Augur; as the force in your department is much weakened it will be necessary to concentrate it as much as possible by occupying only the more important points; tail 'tell n/u? see B as directed' (M)"),
   ["note: MS18-R5: No. 1 (HEAD share .61 vs No. 2 .53). Image: transcription matches line by line; the page's first two entries (Sampson, Balt, 4 June, 'send ... Whip of Abner ... to Angel'; Lawrence H. F., 'send by train to Dagger') are not read here. The units and the addressee are decoder readings of code words (M). Print: Halleck to Schoepf, Headquarters of the Army, Washington 4 June 1864 ('Fifth Maryland ... to report to General Augur', OR, the volume ids 'warofrebellion0207rootrich') is a different message of the same day, not this one. Not located in print: loose windows none; OR I/36 pt 3 by date and Lew Wallace's file not searched individually."]),
 "X10": ("E360", d(110, 9770, "9770/1", 104, "2 July 1864 Washington, to R. R. McCaine for Maj. Gen. Hunter, signed [General-in-Chief, M]: General Grant says that such of your forces as are not required to hold the Kanawha Valley should be brought back to the line of the Baltimore and Ohio Railroad so that by operating from that base they can prevent any raid into Maryland; he says that Ewell's corps has returned to his front but he hears nothing of Breckinridge; are you all ready (M); printed OR I/37 pt 2 pp.8-9 (Halleck to Hunter, 2 July 1864; the page head 9 falls inside the item)"),
   ["note: MS18-R5: No. 1 (HEAD share .49 vs No. 2 .41). Printed OR I/37 pt 2 (letters-only phrase hits on three phrases, window read): body C against that print ('Major-General Hunter, West Virginia: General Grant says that such of your forces as are not required to hold the Kanawha Valley should be brought back to the line of the Baltimore and Ohio Railroad, so that by operating from that base they can prevent any raid into Maryland. He says that Ewell's corps has returned to his front, but he hears nothing of Breckinridge. H. W. Halleck, Major-General and Chief of Staff'); the ledger's closing 'Jew are you all oak' is not in the print (M). Image: transcription matches line by line (the third entry on the leaf, Martinsburg 3 July, not read here). The print's page numbers are from the OCR head only, not eye-checked. Not a key edit (rule 4)."]),
}
blocks = {}; cur = None
for ln in (HERE/"ms18_r5_entries.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"### (X\d+) \|", ln)
    if m: cur = m.group(1); blocks[cur] = []; continue
    if cur and ln.strip() and ln.strip() != "No 1" and ln.strip() not in DROP.get(cur, []): blocks[cur].append(ln)
p = HERE.parent/"ciphertext.txt"; txt = p.read_text(encoding="utf-8")
add = [f"### {nid} | {desc}\n" + "\n".join(blocks[k] + notes) + "\n" for k, (nid, desc, notes) in MAP.items() if f"### {nid} |" not in txt]
if add and "--dry" not in sys.argv: p.write_text(txt.rstrip("\n") + "\n\n" + "\n".join(add), encoding="utf-8")
print(("would add " if "--dry" in sys.argv else "added ") + str(len(add)))
