#!/usr/bin/env python3
"""N2R-2: file Y2-Y5, Y7-Y12 of ms18_n2g_entries.txt (mssEC 18 rows read as Cipher No. 2) into ../ciphertext-no2.txt as N2-GA..N2-GJ.
Usage: ms18_n2g_file.py [--dry]  Idempotent. Y1 (9871/2) and Y6 (9871/1) are not filed (no book gives a clause; NOTES "## N2R-2").
Every leaf is holder transcription only unless a note says it was image-read."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
HOLDER = "holder transcription, leaf not eye-checked"
def d(page, ptr, row, pp, rest, chk=HOLDER): return f"Page {page} | {ptr} | mssEC 18 (obj 10074, pointer {ptr}; printed page {pp}), {rest} (N2R-2; row {row}; {chk})"
def bk(sh): return "N2R-2: No. 2 (whole-entry vocabulary share No.1 / No.2 / No.9 = " + sh + "); "
MAP = {
 "Y2": ("N2-GA", d(214, 9874, "9874/1", 208, "22 Oct 1864 Washington (ledger 12.30 PM; cipher time word 11 AM), R. R. McCaine (operator), to Col. J. W. Forsyth, Chief of Staff, signed B. W. Brice, Acting Paymaster General: paymasters leave here Monday morning the 24th with funds for the 19th Army Corps; sufficient escort wanted at Martinsburg"),
  ["note: " + bk(".26/.43/.13") + "the ledger writes '( No 1 )' in the tail, which conflicts with the book; No. 1 reads word salad ('Kirby Smith ... Drove in our pickets ... Encountered enemy in strong force'), No. 2 reads a clause, the decoded day 22 = the header day and Monday = 24 Oct 1864 (200-seed shuffle of No. 2: day agrees 10 of 200). Forsyth and the 19th Corps agree with Sheridan's army in October 1864 (hand). Not located in print: see NOTES '## N2R-2'."]),
 "Y3": ("N2-GB", d(101, 9761, "9761/1", 95, "19 June 1864 11 AM Washington, forwarding Gen. Sigel's telegram from Martinsburg of the 18th to the Adjutant General: the cavalry detachment sent from Beverly with despatches to Hunter found the enemy in possession of Staunton and Lexington and returned with the despatches; another attempt made; sent for the information of Grant"),
  ["note: " + bk(".38/.59/.14") + "No. 1 reads word salad, No. 2 reads the clause, decoded day 19 = header day (shuffle 12 of 200). IN PRINT: OR I/37 pt 1 (IA warofrebellion371unit) pp.650-651, Sigel to the Adjutant-General, Martinsburg 18 June 1864, received 9.35 a.m. 19th, word for word ('The detachment of cavalry sent from Beverly with dispatches to General Hunter found the enemy in possession of Staunton and Lexington. They returned with the dispatches. Another attempt to send the dispatches has been made.'); grade C against the print."]),
 "Y4": ("N2-GC", d(253, 9913, "9913/0", 247, "10 Dec 1864 Washington (ledger 5 PM; cipher time word 12 noon), R. R. McCaine (operator), signed B. W. Brice, Acting Paymaster General: paymasters ready to go to pay the troops unpaid to 31 August; asks to be notified by telegram in cipher when paymasters may be sent to Relay House; the addressee decodes 'Sheridan P H' (M)"),
  ["note: " + bk(".23/.44/.16") + "the ledger writes 'No 1' before the hour, which conflicts with the book; No. 1 reads 'Adjt Genl. U.S.'s repeat ... Evacuate house'. The decoded day 10 = the header day (shuffle 15 of 200). Same page as the sent copy used for E254 (entry 1 of pointer 9913, 12 Dec 1864, No. 1), a different message. Not located in print: see NOTES '## N2R-2'."]),
 "Y5": ("N2-GD", d(140, 9800, "9800/2", 134, "24 July 1864 12 M Washington, S. H. Beckwith (operator), Halleck to Lieut. Gen. Grant at City Point: the rear of the Sixth Corps got into camp last night and is being supplied and paid; they will probably begin to embark tonight; Hunter's last telegram on the enemy in the Shenandoah is forwarded"),
  ["note: " + bk(".35/.60/.23") + "No. 1 reads word salad, No. 2 reads the clause, decoded day 24 = header day (shuffle 3 of 200). IN PRINT: OR I/37 pt 2 (IA warofrebellion372unit) p.426, Halleck to Grant, Washington 24 July 1864, 12 noon: 'The rear of the Sixth Corps got into camp last night; they are being supplied and paid to-day. They will probably begin to embark to-night. Last telegram from Hunter in regard to enemy in the Shenandoah is forwarded.' Word for word but for the code words 'Rear', 'Camp', 'Supply', 'To day', 'Shenandoah', 'Forward'; grade C against the print. The decoded 'Hunter D' = 'Hunter' (print), 'General in Chief' = the signature slot (Halleck, print)."]),
 "Y7": ("N2-GE", d(256, 9916, "9916/1", 250, "16 Dec 1864 Washington (ledger 1.30 PM), Fuller at New Orleans (operator), to Maj. Gen. Canby, signed Halleck: the arrival of the (decoded) 'Savannah' makes it unnecessary to keep supplies and troops to meet him on the Gulf coast; the Quartermaster General has ordered the supplies in vessels at Pensacola(?) to Hilton Head; the others at your disposal"),
  ["note: " + bk(".41/.41/.14") + "the shares tie No. 1 and No. 2; the sense picks No. 2 (header: Washington to New Orleans, Canby's command; decoded Friday 16 = Dec 16 1864 was a Friday; No. 1 reads 'Maj Gen B. M. Prentiss ... Williamsburg ... Columbus ... Maj Gen Geo. H. Thomas', no clause). Header hour '1 30 Pm' (the control script reads it as 30.00 PM; ignore that column). 'Savannah' is the key's value for 'hebrew'; Sherman reached Savannah on 21 Dec 1864 (hand). Not located in print: see NOTES '## N2R-2'."]),
 "Y8": ("N2-GF", d(62, 9722, "9722/1", 56, "25 April 1864 Washington (cipher time word 3 PM), Caldwell (operator, Hd Qrs AP; the ledger's page text has 'Apl 25 1864', the clean-ms18 date 1864-11-02 is a segmenter slip), to Maj. Gen. Meade, signed Augur: Mosby is collecting corn and horses in the vicinity of Upperville; can you send a regiment of cavalry from Warrenton to meet a command; I will send on Wednesday or Thursday next to break up this business and destroy the supplies collected"),
  ["note: " + bk(".42/.55/.19") + "No. 1 reads 'Maj Gen J. G. Parke ... Reinforce ... Drove in Enemys pickets ... Maj Gen Geo. H. Thomas', no clause; No. 2 reads the clause ('Wednesday or Thursday next' after Monday 25 Apr 1864). Header has no hour and the day is plain text, so the time/day checks are not testable here. Some tokens are the key's values and not obvious ('Harrison'ing corn', 'Browns Ferry' for business: M). Not located in print: see NOTES '## N2R-2'."]),
 "Y9": ("N2-GG", d(20, 9680, "9680/0", 14, "27 Feb 1864 11 AM Washington, S. H. Beckwith (operator), Halleck to Grant: there is no immediate movement on foot in West Virginia towards Longstreet; advices just received from Jacksonville, Florida, that Hardee with 15,000 men from Johnston's army defeated Seymour near Baldwin on the 20th instant"),
  ["note: " + bk(".59/.78/.30") + "No. 1 reads word salad, No. 2 reads the clause; the cipher time word 11 AM = the header hour under No. 1 and No. 2 alike (not selective), the decoded day 27 = header day under No. 2 only (shuffle 2 of 200). IN PRINT: OR I/32 pt 2 (IA warofrebellion322unit) p.480, Halleck to Grant at Nashville, Washington 27 Feb 1864, 11 a.m.: 'There is no immediate movement on foot in West Virginia toward Longstreet. Advices just received from Jacksonville, Fla., that Hardee, with 15,000 men from Johnston's army, defeated General Seymour near Baldwin on the 20th instant.' Grade C against the print for the clause; the plain words 'Seymour' and 'Baldwin' stand in the cipher, and the decoder's '[Found] [Near] [Crocker M M]' are the key values of three code words that the print renders 'defeated ... near ... General' (M, not asserted)."]),
 "Y10": ("N2-GH", d(65, 9725, "9725/0", 59, "27 April 1864 Alexandria Va. (cipher time word 2 PM), S. H. Beckwith (operator), to Lieut. Gen. Grant, signed Maj. Gen. A. E. Burnside: the column in motion will reach Fairfax tonight; several regiments not reported; will leave orders for them to follow up; we have the requisite ammunition and supplies with the column"),
  ["note: " + bk(".45/.55/.19") + "No. 1 reads no clause ('Brigadier General and sword ... Danville ... Knoxville'); No. 2 reads the clause, decoded day 27 = header day (shuffle 0 of 200), and the facts fit: the Ninth Corps left Alexandria on 27 Apr 1864 (OR I/33, Grant to Meade, Culpeper 27 April 8.30 a.m.: 'General Burnside's command leaves Alexandria this morning'). Not located in print: see NOTES '## N2R-2'."]),
 "Y11": ("N2-GI", d(254, 9914, "9914/1", 248, "14 Dec 1864 Washington (cipher time word 3 PM), Caldwell (operator, Hdqrs AP), to Maj. Gen. Meade, signed B. W. Brice: in compliance with the Secretary's order of the 2nd inst. the paymasters will leave tomorrow by river for City Point to pay two regiments of the Sixth Corps unpaid to 31 August"),
  ["note: " + bk(".31/.58/.19") + "No. 1 reads 'Chattanooga ... Recruits ... Reinforce'; No. 2 reads the clause; Wednesday = Wed 14 Dec 1864, decoded day 14 appears only as 'Wednesday' (the shuffle floor for the day match is 26 of 200, so that column is not a test here). Not located in print: see NOTES '## N2R-2'."]),
 "Y12": ("N2-GJ", d(21, 9681, "9681/0", 15, "29 Feb 1864 12.30 PM Washington, S. H. Beckwith (operator), Stanton to Maj. Gen. Grant at Nashville: I have directed that Nashville be put in direct communication at 8 o'clock tonight; please come into the telegraph office at that hour; I desire to communicate with you"),
  ["note: " + bk(".46/.58/.08") + "No. 1 reads 'Kirby Smith ... St Louis ... Cipher ... Concentrate'; No. 2 reads the clause, decoded day 29 = header day (shuffle 1 of 200). IN PRINT: OR I/32 pt 2 (IA warofrebellion322unit) p.494, Stanton to Grant, Washington 29 Feb 1864, 12.30 p.m.: 'I have directed that Nashville be put in direct telegraphic communication at 8 o'clock to-night. Please come into telegraph office at that hour. I desire to communicate with you. EDWIN M. STANTON, Secretary of War.' Grade C against the print; the cipher's tail 'Think he will Plant in Pigeon' is not in the print passage quoted (the ledger entry may carry a second telegram; M)."]),
}
blocks = {}; cur = None
for ln in (HERE/"ms18_n2g_entries.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"### (Y\d+) \|", ln)
    if m: cur = m.group(1); blocks[cur] = []; continue
    if cur and ln.strip(): blocks[cur].append(ln)
p = HERE.parent/"ciphertext-no2.txt"; txt = p.read_text(encoding="utf-8")
add = [f"### {nid} | {desc}\n" + "\n".join(blocks[k] + notes) + "\n" for k, (nid, desc, notes) in MAP.items() if f"### {nid} |" not in txt]
if add and "--dry" not in sys.argv: p.write_text(txt.rstrip("\n") + "\n\n" + "\n".join(add), encoding="utf-8")
print(("would add " if "--dry" in sys.argv else "added ") + str(len(add)))
