#!/usr/bin/env python3
"""MS18-R6: file the ten ms18_r6_entries.txt rows X1-X10 into ../ciphertext.txt (Cipher No. 1) as E361-E370. Usage: ms18_r6_file.py [--dry]  Idempotent.
X11, X12 (spares 9842/1, 9907/1) are not filed. Image check: the 9674 leaf (X1, X5) and the 10020 leaf (X9) read at 2400 px; the other leaves are holder-transcription only (not eye-checked)."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
def d(page, ptr, row, pp, rest, chk): return f"Page {page} | {ptr} | mssEC 18 (obj 10074, pointer {ptr}; printed page {pp}), {rest} (MS18-R6; row {row}; {chk})"
H = "holder transcription, leaf not eye-checked"; I = "leaf image-read at 2400 px"
DROP = {"X6": ["No 1"], "X8": ["1"], "X9": ["No 4"]}
BOOK = "MS18-R6: No. 1 (whole-entry vocabulary share No.1 / No.2 / No.9 = "
MAP = {
 "X1": ("E361", d(14, 9674, "9674/0", 8, "10 Feb 1864 4 PM Washington, S. H. Beckwith (label 1), for Maj. Gen. Grant at Nashville, signed Halleck, General-in-Chief: Mr Beckwith has been restored; Captain Stokes will be made quartermaster with the rank of lieutenant-colonel; Governors of States have no authority to furlough troops; report any cases and the Secretary of War will so inform the governors; tail 'Mailed letter today'; printed OR I/32 pt 2 (about p.361)", I),
  ["note: " + BOOK + ".44/.41/.17). Printed OR I/32 pt 2 (IA warofrebellion322unit; the item is followed by the running head 362): Halleck to Grant, Washington 10 Feb 1864 4 p.m., clause for clause; C against the print. The closing 'Mailed letter today' is not in the print (plain, the operator's own addition). Image: transcription matches line by line (ledger page 8). Not a key edit (rule 4)."]),
 "X2": ("E362", d(226, 9886, "9886/1", 220, "3 Nov 1864 4 PM Washington, to Capt. Clowry at St Louis for Brig. Gen. Rawlins, Chief of Staff to Maj. Gen. Grant, signed Halleck: all the troops you can lay hands on in Missouri should be sent forward with the least possible delay to reinforce General Thomas; he is probably opposed by Hood's entire army and the cavalry of Wheeler and Forrest; printed OR I/41 pt 4 p.418", H),
  ["note: " + BOOK + ".54/.60/.20): the share favours No. 2 but No. 2 reads Imboden/Ammunition nonsense and No. 1 reads clause for clause; the sense picks No. 1. Printed OR I/41 pt 4 p.418 (IA warofrebellion414unit; the item sits under the head 418): Halleck to Rawlins, Chief of Staff to General Grant, Saint Louis, 3 Nov 1864 4 p.m. C against the print. The print names Forrest where the ledger has Halifax (plain, in no key row): Halifax = Forrest by print (C, one witness; 'hug' = Wheeler by print too, M in the key); 'Panama' = Cavalry (see E350). The tail 'He is in your city' is not in the print. Sibling of E337 (same day, same operator, 12 m, for Curtis)."]),
 "X3": ("E363", d(16, 9676, "9676/1", 10, "14 Feb 1864 12.30 PM Washington, S. H. Beckwith (label 1), for Maj. Gen. Grant at Nashville, signed Halleck: recruiting officers and provost marshals have been directed to send recruits to their regiments as fast as collected and to send new regiments to the field as fast as organized; in case General Schofield should be rejected, who do you want to command his department; name several to select from; printed OR I/32 pt 2 (pp.386-389)", H),
  ["note: " + BOOK + ".47/.47/.21): a tie, the sense picks No. 1 (No. 2 reads Jenkins/Pemberton nonsense; the shuffled No. 1 gives the same H count, so the count control cannot fail and licenses nothing). Printed OR I/32 pt 2 (running heads 386 before and 390 after; page not narrowed): Halleck to Grant, Washington 14 Feb 1864 12.30 p.m., word for word; C against the print. 'Kiss' = Schofield and 'Polka' + 'Er' = command are key rows confirmed by the print (C). The print's closing is 'Name several to select from.'; the ledger's tail words are the signature code."]),
 "X4": ("E364", d(109, 9769, "9769/1", 103, "29 June 1864 4 PM Washington, to Brig. Gen. Bailey care of Capt. Wooster at Cairo (operator line 'WT June Mason (#1) Cairo'), signed Meigs, Quartermaster General: Lieutenant-General Grant has decided that the Vicksburg and Shreveport Railroad shall not be repaired at present; whenever repaired the gauge should be changed to 5 feet; no engines or cars of 5 feet 6 inches gauge are in existence up North; tail 'Where is Wash Parker now'; printed OR I/34 pt 4 p.586", H),
  ["note: " + BOOK + ".59/.43/.18): No. 1. Printed OR I/34 pt 4 p.586 (IA warofrebellion013404rootrich; item under the head 586): Meigs to Bailey (Care Captain Wooster, Cairo), Washington 29 June 1864 4 p.m.; C against the print. 'Wooster' stands for Cairo's Capt. Wooster (plain in print); the print's 'Lieutenant-General Grant' is the ledger's 'Jupiter' (= Maj Genl U.S. Grant in the key: a title difference, Grant was Lieutenant-General from March 1864; the key row's title is M). The tail 'Where is Wash Parker now' is not in the print. Context in clear at the holder: pointer 10469 (Canby, New Orleans 23 June 1864, to Halleck on the Vicksburg and Shreveport road, gauge) and 8986 (Kimber, 17 June 1864, the gauge question), both other pages, not this telegram."]),
 "X5": ("E365", d(14, 9674, "9674/1", 8, "11 Feb 1864 4 PM Washington, S. H. Beckwith (label 1), for Maj. Gen. Grant at Nashville, signed Halleck: Congress has been more than two months discussing the draft bill and unless it soon passes we cannot fill up infantry regiments in time to supply the place of furloughed men; other armies are in the same or worse condition than yours; tail 'She's my darling'; printed OR I/32 pt 2 (about p.369)", I),
  ["note: " + BOOK + ".46/.41/.15): No. 1. Printed OR I/32 pt 2 (running heads 368 before and 370 after): Halleck to Grant, Washington 11 Feb 1864 4 p.m., word for word; C against the print. Image: transcription matches line by line (ledger page 8). Tail 'She's my darling' is not in the print. The next entry on the leaf (A. H. Caldwell, label 2, 11 Feb 1864 4 PM) is not read here."]),
 "X6": ("E366", d(345, 10005, "10005/2", 339, "8 May 1865 4 PM Washington (label No 1), to Caldwell at Richmond for Halleck [M], signed [Dana, M]: the Secretary of War directs that you arrest William Boulware, whose estate is Norwell Rest [M], five or six miles from [Hanover?, M] and King and Queen Court House; send him here under guard to the Judge Advocate", H),
  ["note: " + BOOK + ".49/.44/.24): No. 1 (the 1865 HEAD share row for this pointer is not in key-share-1865.tsv, so the share is the whole-entry share above); the clear text is plain. Not located in print: letters-only phrase grep over 177 cached/scratch volumes (hits for 'Boulware' only in OR I/46 ser. other volumes about Boulware's Wharf, a place), date-window search for 8 May 1865 headings with Boulware/arrest/Richmond/Halleck in OR I/46 pt 3, I/47 pt 3, I/48 pt 2, I/49 pt 2: 0. Holder witnesses of the case at other pointers (clear): 7905 (object 8066, Richmond 10 May 1865 12.30 pm, Halleck to Dana: 'your telegraph for the arrest of Wm Boulware has been received and orders accordingly') and 8728 (object 8886, Richmond 13 May 1865, Halleck to Grant: 'Boulware has been captured and will be sent immediately to Wash'): corroborate that Boulware was ordered arrested at Dana's telegram (C for the name and the act); the 8 May telegram itself has no clear copy found."]),
 "X7": ("E367", d(141, 9801, "9801/0", 135, "24 July 1864 10 PM Washington, McCaine at Harpers Ferry, for Maj. Gen. Hunter, signed Stanton, Secretary of War: we have dispatches from General Grant's headquarters this afternoon; he is not in Richmond and gives no intimation that the rebel army is down the Valley of the Shenandoah; where was General Crook when you last heard from him and in what direction was he operating; printed OR I/37 pt 2 (about pp.429-431)", H),
  ["note: " + BOOK + ".45/.39/.16): No. 1. Printed OR I/37 pt 2 (IA warofrebellion372unit; running heads 428 before, 432 after): Stanton to Hunter, War Department 24 July 1864 10 p.m.; C against the print. The print reads 'is moving down the Valley'; the ledger's word group gives 'is down' (no 'moving'); 'Galway' = Richmond and 'Jupiter's' = General Grant's by print; 'Indus' = Secretary of War (signature). Context: Hunter to Stanton 24 July 8.30 p.m. immediately above in the print."]),
 "X8": ("E368", d(367, 10027, "10027/2", 361, "2 June 1865 Washington (hour 10 AM), Clowry at St Louis, for Maj. Gen. Pope, signed Grant: you may authorize the issuing of arms to all persons connected with the carrying of Government freight over the plains on proper security that the arms will not be lost to the Government; referred to the Secretary of War for approval; approved; printed OR I/48 pt 2 p.730", H),
  ["note: " + BOOK + ".57/.43/.20): No. 1. Printed OR I/48 pt 2 p.730 (IA warofrebellion482unit; the item ends just before the head of p.731 and follows the head 730): Grant to Pope, Washington 2 June 1865, 'Received 10 a.m.'; C against the print. 'Niggards' = arms (the key row; read by sense, the print confirms C). The referral and approval lines ('Respy referred to the Secretary of War for approval ... approved') are the ledger's own and not in the print. Holder: 10027 is this page alone."]),
 "X9": ("E369", d(360, 10020, "10020/2", 354, "24 May 1865 Washington (hour 8.30 or 4.30 PM, M), label No 1, H. F. Lines at Macon, signed [Secretary of War, M]: you will immediately arrest Thomas J. Paxton or Parton [M] Campbell [M], who was a Confederate officer at [Chattanooga?, M], and send him under guard to Nashville to be delivered to Maj. Gen. Thomas; forward by rail", I),
  ["note: " + BOOK + ".64/.64/.19): a tie of No. 1 and No. 2; the sense picks No. 1 (No. 2 reads Butler/Cavalry nonsense; the shuffled copy gives the same H count). Image (ledger page 354): the operator line is 'H. F. Lines, No 1, Macon' and the header 'Wash'n May 24th 1865'; the hour above the page (9.30 am) belongs to the entry above; 'No 4' at the foot is the next entry's label (T. C. Sullivan, Nashville), dropped. The name is written 'Thomas J. Parton' or 'Paxton' on the image (not settled): decoder reads the code groups 'Paxton' (name, plain) and 'bell' (Campbell?) as M. Not located in print: phrase grep (177 volumes) and date-window search for 23-24 May 1865 headings with Macon/Wilson/Nashville and Campbell/Paxton/deliver in OR I/46 pt 3, I/47 pt 3, I/48 pt 2, I/49 pt 2: 0 (I/49 pt 2 has 35 dated headings for the window, none with the terms). Holder: 'Paxton' returns 53 pages (a common cipher word in the ledger), none opened."]),
 "X10": ("E370", d(176, 9836, "9836/1", 170, "7 Sept 1864 Washington, Horner at New York, for [Col. McCallum, M] care Masury and Whiton, 111 Fulton street, signed [Head Quarters Army, M]/Whiton: [the army] wish to know for how many 'spartons' in excess of those now in [Sherman's] command can be supplied by rail; have sent this to [Tennessee, M]", H),
  ["note: " + BOOK + ".45/.36/.18): No. 1 (the decode gives McCallum and Fulton street as plain; 'spartons' is in no key row, M). Not located in print: phrase grep (177 volumes: 'Masury', 'Fulton street', 'supplied by rail' none) and date-window search for 7-8 Sept 1864 headings with New York/Horner/Whiton/Masury and rail in OR I/42 pt 2 (54 dated headings), I/42 pt 3 (1), I/43 pt 2 (47): 0 with the terms. Holder: 'Masury Whiton' returns pointer 9836 only (this page); no clear copy. McCallum is presumably the Director of Military Railroads (not established)."]),
}
blocks = {}; cur = None
for ln in (HERE/"ms18_r6_entries.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"### (X\d+) \|", ln)
    if m: cur = m.group(1); blocks[cur] = []; continue
    if cur and ln.strip() and ln.strip() not in DROP.get(cur, []): blocks[cur].append(ln)
p = HERE.parent/"ciphertext.txt"; txt = p.read_text(encoding="utf-8")
add = [f"### {nid} | {desc}\n" + "\n".join(blocks[k] + notes) + "\n" for k, (nid, desc, notes) in MAP.items() if f"### {nid} |" not in txt]
if add and "--dry" not in sys.argv: p.write_text(txt.rstrip("\n") + "\n\n" + "\n".join(add), encoding="utf-8")
print(("would add " if "--dry" in sys.argv else "added ") + str(len(add)))
