#!/usr/bin/env python3
"""MS18-R3: file the ten ms18_r3_entries.txt rows into ../ciphertext.txt (Cipher No. 1) as E331-E340. Usage: ms18_r3_file.py [--dry]  Idempotent.
Rows X3, X4, X5, X10 image-read at 2400 px (full page, own entry); X1, X2, X6-X9 confirmed against the print (OR), pages not eye-checked."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
def d(page, ptr, row, pp, rest, chk): return f"Page {page} | {ptr} | mssEC 18 (obj 10074, pointer {ptr}; printed page {pp}), {rest} (MS18-R3; row {row}; {chk})"
IMG = "image-read at 2400 px"; PR = "text checked against the print, page not eye-checked"
MAP = {
 "X1": ("E331", d(356, 10016, "10016/1", 350, "22 May 1865 Washington, 7 PM, to Maj. Gen. Schofield at Raleigh, signed Grant: inform General J. E. Johnston he will be permitted to go to Canada through the States as he may select, not to return to the United States without first obtaining leave; printed OR I/47 pt 3 p.560 (headed 2 p.m.)", PR),
   ["note: MS18-R3: No. 1 (share .35; control median .41, p10 .29). Printed OR I/47 pt 3 p.560 (Grant to Schofield, Washington 22 May 1865, 2 p.m.): the body is C against that print; the ledger has 7 PM (hour of sending or copying; print says 2 p.m.). 'Maj Genl J. M. Schofield' = Helen harsh plank kiss (H), 'Maj Genl U.S. Grant' = Jupiter (H). The ledger header reads 'OBrien Raleigh'; the print's addressee is Schofield at Raleigh. Not a key edit (rule 4)."]),
 "X2": ("E332", d(148, 9808, "9808/1", 142, "2 Aug 1864 3.30 PM Washington, to McCaine for Maj. Gen. Hunter at Monocacy, signed General-in-Chief (Halleck): General Kelley defeated the enemy last night near Cumberland and drove him back toward Old Town on the Potomac; can you not push forward Averell's cavalry to cut off his retreat; printed OR I/37 pt 2 p.576", PR),
   ["note: MS18-R3: No. 1 (share .68). Printed OR I/37 pt 2 p.576 (Halleck to Hunter, Monocacy, Washington 2 Aug 1864, 3.30 p.m.): body C against that print. The decoder's place and name words around 'Friend ... Topple Comb her land' differ from the print's 'General Kelley ... near Cumberland' and are M; 'Dovers' (Averell's) and 'Warrick' (retreat) are unread in the key (print-derived, not key edits). Not a key edit (rule 4)."]),
 "X3": ("E333", d(85, 9745, "9745/1", 79, "26 May 1864 2.40 PM Washington, to John Horner (addressee 'Kunkle' = Dix, New York), signed L. C. Turner: the Secretary of War directs me to inform you of a plot to seize a steamer going from France to New Orleans (Eddy = New Orleans); several spies have left Havana and are now in or about New York; one named Phillips left for [New York] in the steamer Havana (Phillips tall, thin, stout built, black moustache, imperial and goatee, diamond ring on little finger of left hand); a Capt. Edwards, aged ?, side whiskers, formerly in our navy; Dr Monthny de Lasalle, a Frenchman, about ? years old, stout, Portuguese passport; more by mail", IMG),
   ["note: MS18-R3: No. 1 (share .38; control median .41). Image: the margins carry period glosses on four code words ((brace) on Imogene, (miles) on harrow, (smoking) on pledge, (animal) on zebra, and at the foot (propulsion), (distance) beside L, (prisoners) beside C) and some pencil words at the right margin (not read); they are in the same hand as the ledger and are not decoded here. 'Phillips', 'Edwards', 'Monthny de Lasalle' and the description are plain. Name codes unread: Kunkle (addressee), Horner. Not located in print: 171 volumes, 0 phrase hits (ms18_r3_printcheck.out); not searched in the Navy ORN, the New York press or the Dix papers."]),
 "X4": ("E334", d(86, 9746, "9746/0", 80, "27 May 1864 2.30 PM Washington, to Capt. Geo. H. Smith (for Maj. Gen. Rosecrans), signed 'Infant' = Secretary of War: send down the Mississippi at once to report to Maj. Gen. Hurlbut the 10th Kansas Volunteer Infantry, 68th US Colored Infantry, 12th Missouri Volunteer Cavalry and 7th Kansas Volunteer Cavalry; if the cavalry cannot be mounted at once they will be dismounted and sent forward as infantry; see they go with proper provisions and supplies; report daily the progress", IMG),
   ["note: MS18-R3: No. 1 (share .66; the sense reads, H 47). Image check: the transcription matches every line; 'Windsor' (Ark Windsor = Mississippi River) is plain in the image. Regiment numbers are the key's 10, 68, 12, 7. Not located in print: OR I/34 pt 3, 34 pt 4, 36 pt 3 and 168 cached volumes, no phrase hit, no Hurlbut/Kansas/Colored window (ms18_r3_loose.out); the Hurlbut OR I/34 pt 4 mentions are other letters. A second entry follows on the same page (27 May 1864 3 PM), not read here."]),
 "X5": ("E335", d(33, 9693, "9693/1", 27, "31 Mar 1864 11.30 AM Washington, to W. F. Mason at Cairo, signed Henry A. Wise, Chief of Bureau of Ordnance (T. T. Eckert): Pilgrim [Captain] Penrock at Cairo: your telegram received; 1000 barrels powder, part cannon and part musket, have been ordered to Cairo and are being forwarded; the Bureau decides to let it go and as it has been consigned first to Capt. Berrien at Pittsburgh to be reshipped by him, be pleased to communicate with him and if you apprehend any danger desire him to retain it at Pittsburgh subject to your order", IMG),
   ["note: MS18-R3: No. 1 (share .40; control median .41). Image: the transcription matches; small numerals written above six code words (4, 6, 2, 5, 3, 7: 'Mar' 4, 'Florence' 6, 'For' 2, 'Wise' 5, 'Chief' 3, 'Ordnance' 7) and marginal and footer pencil notes (not read); none decoded. 'Bleaching' = Cairo (H). The sender's name is plain. Not located in print: 171 volumes, no window for Berrien + Pittsburgh + powder (Ordnance Bureau letter books are not in OR)."]),
 "X6": ("E336", d(221, 9881, "9881/1", 215, "1 Nov 1864 11.30 AM Washington, to Capt. G. H. Smith at St Louis for Maj. Gen. Rosecrans, signed Halleck: dispatches just received from General Thomas render it imperative that reinforcements be sent to him with all possible dispatch; A. J. Smith should move by forced marches, his men can rest on the steamers; no delay for payments as Hood is crossing the Tennessee; Thomas may want the reinforcements landed at Savannah or Clifton or sent direct to Nashville; consult him by telegraph when the troops reach St Louis; General Grant directs that all available troops in St Louis and vicinity be sent to General Thomas; printed OR I/41 pt 4 p.390", PR),
   ["note: MS18-R3: No. 1 (share .56 vs No. 2 .61: the sense picks the book). Printed OR I/41 pt 4 p.390 (Halleck to Rosecrans, Washington 1 Nov 1864, 11.30 a.m., via St Louis): body C against that print. Decoder: Lady = Thomas, Garter = Savannah, Embrace = Nashville (key rows). From the print only (proposed, not key edits, rule 4): Hudson = Hood, webb = reinforcements, Macbeth = A. J. Smith, tablet = move, sainted = forced, Jupiter = Grant."]),
 "X7": ("E337", d(226, 9886, "9886/0", 220, "3 Nov 1864 12 m Washington, to Capt. Clowry at St Louis for Maj. Gen. Curtis, signed Halleck: the Secretary of War directs you assume command of all troops belonging to the Department of the Missouri now serving on the western border of that state and pursue Price toward the Arkansas River or till he reaches the troops of Steele or Reynolds; having completed this duty return the troops to their commands; furnish a copy of this order to the several commanders and to Major-General Rosecrans; regiments of the Department of Arkansas to be sent to General Steele; printed OR I/41 pt 4 p.420", PR),
   ["note: MS18-R3: No. 1 (share .52). Printed OR I/41 pt 4 p.420 (Halleck to Curtis, Newtonia, Washington 3 Nov 1864, 12 m.; the print's footnote says Curtis misquoted it as 7 Nov): body C against that print. Print: 'Major-General Curtis, Newtonia'; the ledger addresses Clowry at St Louis for Curtis. Decoder gives Arkansas, West, Steele, Reynolds for Archery, Wilson, Mellow, Montrose (key rows)."]),
 "X8": ("E338", d(228, 9888, "9888/2", 222, "5 Nov 1864 2.30 PM Washington, to R. C. Clowry at St Louis for Brig. Gen. Rawlins, signed Halleck: it is reported there is an Illinois regiment at Cairo not required there and under orders for Atlanta; if so order it to Paducah or to Thomas; are there not troops at Cape Girardeau or New Madrid that could be spared; I think every man you can possibly get should be hurried to Thomas; if Beauregard can be checked on the Tennessee River Sherman can begin his own movement at once; printed OR I/41 pt 4 p.438", PR),
   ["note: MS18-R3: No. 1 (share .42 vs No. 2 .42; the sense picks the book). Printed OR I/41 pt 4 p.438 (Halleck to Rawlins, Washington 5 Nov 1864, 2.30 p.m.): body C against that print. The print's Rawlins is Brig. Gen. J. A. Rawlins at St Louis, answered by Rawlins at 9 p.m. the same day. Closing 'Jacob weather clear & cool' is the ledger's own addition. Not a key edit (rule 4)."]),
 "X9": ("E339", d(204, 9864, "9864/0", 198, "12 Oct 1864 Washington (sent 9 PM), to McCaine for Maj. Gen. Sheridan, signed Infant = Secretary of War (Stanton): this Department again tenders its thanks to you, and through you to Major-General Torbert, Generals Merritt and Custer and the officers and soldiers under their command for the brilliant victory won last Sunday by their gallantry over the rebel cavalry in the Shenandoah Valley; under gallant leaders your cavalry has become the efficient arm in this war that it has proved in other countries; printed OR I/43 pt 1 p.62", PR),
   ["note: MS18-R3: No. 1 (share .46). Printed OR I/43 pt 1 p.62 (Stanton to Sheridan, War Department 12 Oct 1864, sent 9 p.m.): body C against that print (found through the cross-reference in OR I/43 pt 2 p.345, 'For Stanton to Sheridan, tendering thanks, &c., see Part I, p. 62'). The 'last Sunday' victory is Tom's Brook, 9 Oct 1864. 'Nelly forbid Nabob' = for Sheridan (M, key rows not edited)."]),
 "X10": ("E340", d(396, 10056, "10056/2", 390, "1 Oct 1865 12 m Washington, to Sampson at Lynchburg, Va., for Mrs M. H. Alberger, Church St: get from Hall the safe key and bring it with you; Hall can leave the safe open by taking the money papers home with him every night; signed M. H. Alberger; the second entry on the page (H. Seiberg, New Orleans, 7 Oct 1865) is not read here", IMG),
   ["note: MS18-R3: No. 1 (share .37; control median .41, p10 .29). Image: the word the holder transcription gives as 'Gvt' reads 'Get' in the page image; the entry is a civil private message, plain except the codes 'plug publish ghost' (number 115) and 'dryden' (Lynchburg). The ledger's printed page is 390, not 396 (the holder pointer's page). ms18_r3_entries.txt has an 'H Seiberg N Orleans' entry carried in by the segmenter; it is cut here and not filed. Not located in print: the post-war date is outside the OR series; 171 volumes, no window for Alberger + safe."]),
}
blocks = {}; cur = None
for ln in (HERE/"ms18_r3_entries.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"### (X\d+) \|", ln)
    if m: cur = m.group(1); blocks[cur] = []; continue
    if cur and ln.strip() and ln.strip() != "No 1": blocks[cur].append(ln)
# X10: cut the carried-in second entry (from 'No 5' / 'H Seiberg' on)
b = blocks["X10"]
for i, ln in enumerate(b):
    if ln.strip() == "No 5" or ln.startswith("H Seiberg"): blocks["X10"] = b[:i]; break
p = HERE.parent/"ciphertext.txt"; txt = p.read_text(encoding="utf-8")
add = [f"### {nid} | {desc}\n" + "\n".join(blocks[k] + notes) + "\n" for k, (nid, desc, notes) in MAP.items() if f"### {nid} |" not in txt]
if add and "--dry" not in sys.argv: p.write_text(txt.rstrip("\n") + "\n\n" + "\n".join(add), encoding="utf-8")
print(("would add " if "--dry" in sys.argv else "added ") + str(len(add)))
