#!/usr/bin/env python3
"""L14-B (LEDGER-14): replace the DRAFT headers of E610-E617 in ../ciphertext.txt with final headers and append each entry's note line. Rows are the 8 mssEC 18 No. 1 rows
held by MS18-R10/R11 (step-0 hits; filed under the LEDGER-14 RULING: a hit is a non-test, STEP0-KEYCTL). Idempotent (skips a block already carrying 'L14-B;').
Transcription only: no leaf was image-read by this worker (the holder transcription is the source)."""
import re, sys
from pathlib import Path
p = Path(__file__).resolve().parent.parent/"ciphertext.txt"; t = p.read_text(encoding="utf-8")
P = "L14-B; "
def hdr(pg, ptr, pp, rest): return f"Page {pg} | {ptr} | mssEC 18 (obj 10074, pointer {ptr}; printed page {pp}), {rest}"
S0 = "Step 0 (as information only, a hit is a non-test under STEP0-KEYCTL): "
NOCOPY = "Holder clear copy: CISOSEARCHALL p16003coll11 rare plain words, all pointers, hit only the row's own pointer (control 'Inspector Inquiry evidence' returned 9678), so none."
R = {
"E610": (hdr(127,9787,121,"11 July 1864 Washington 12.30 PM, R. R. McCaine (operator), for Maj. Gen. David Hunter via Cumberland, signed [Halleck]: as soon as you form a junction with General Howe leave forces enough to hold Maryland Heights, move down the Potomac to form a junction with General Wright at or near Edwards Ferry; object a heavy force in the enemy's rear to intercept his retreat (row 9787/1; "+P+"in print, OR I/37 pt 2, 11 July 1864 12.30 p.m., word for word)"),
  "note: L14-B: No. 1 (share .48/.47/.27 not discriminating vs No. 2; read by sense). "+S0+"(a) 0.619 (39/63), (b) p95 0.190, HIT (MS18-R10). In print: OR I/37 pt 2 (IA warofrebellion372unit, cached text; page not read), Halleck to Hunter, Washington 11 July 1864 12.30 p.m., 'As soon as you form a junction with General Howe, leave forces enough to hold Maryland Heights ... heavy force in the enemy's rear, so as to intercept his retreat. The details will, of course, be varied according to circumstances'; C against the print. The ledger's tail 'Sir come stanzas' = 'circumstances' (undecoded group, M). "+NOCOPY+" Transcription only, leaf not image-read."),
"E611": (hdr(73,9733,67,"7 May 1864 Washington 11 AM, John Horner (operator), for Capt. S. L. Brown, Asst. Quartermaster in charge of forage, New York, signed [Qr Master Genl U.S.], marked confidential: daily forage shipments to Monroe to average 27,000 bushels of grain and 350 tons of hay, consigned to Colonel Biggs, Chief Quartermaster, Department of Virginia; supply here lately low; about 60,000 animals to be supplied from here (row 9733/1; "+P+"not located in sources searched by date, below)"),
  "note: L14-B: No. 1 (share .44/.30/.14; read by sense). "+S0+"(a) 0.662 (43/65), (b) p95 0.215, HIT (MS18-R10). Not located: letters-only phrase grep of five clauses over the 177 cached OR/ORN/Butler volumes (one phrase hit, '27,000 bushels of grain and 350 tons of hay', is OR I/32 pt 3 [IA warofrebellion323unit] Meigs to Grant 8 Apr 1864 on '40,000 bushels of grain and 700 tons of hay' to Pensacola: a different telegram, rejected); date window 7 May 1864 with Brown/Biggs/forage: no heading; IA be-api whole collection, two exact-phrase queries ('daily shipments of forage to Monroe', 'consign this forage to Colonel Biggs'): 0 hits. The numbers 27000, 350 and 60000 are code-group values (M). "+NOCOPY+" Transcription only, leaf not image-read."),
"E612": (hdr(223,9883,217,"1 Nov 1864 Washington (hour 1 PM), for Brig. Gen. Robert Allen, Quartermaster, Louisville, signed [Qr Master Genl U.S.] (M, the signature groups read 'M see Me Eggs'): the Secretary of War informs me that many days since he ordered you to order Captain Ferry to Memphis without a day's delay and to arrest him and report the execution; he understands Ferry has not gone and you have not reported; the Secretary is not satisfied with your conduct (row 9883/0; "+P+"not located in sources searched by date, below)"),
  "note: L14-B: No. 2 share .39 vs No. 1 .35 (not discriminating; No. 1 read by sense, No. 2/9 nonsense, as MS18-R10). "+S0+"(a) 0.630 (29/46), (b) p95 0.217, HIT (MS18-R10). Not located: phrase grep of five clauses over the 177 cached volumes: none; date window 1 Nov 1864 with Allen/Ferry/Memphis: no heading; IA be-api whole collection, two queries ('not satisfied with your conduct' + Captain Ferry + Memphis; 'Captain Ferry to Memphis' + 'Robert Allen'): 0 hits. Addressee's first name and the Secretary of War are inferred from the decode (M). "+NOCOPY+" Transcription only, leaf not image-read."),
"E613": (hdr(142,9802,136,"27 July 1864 Washington 9 AM, J. C. Van Duzer (operator), for Gov. [Andrew] Johnson, Nashville, signed [President U.S.] (Lincoln): yours about General A. C. Gillem received, will look after it today; I also read yours about Carl Schurz, appreciate him as highly as you do, but you can never know until you have the trial how difficult it is to find a place for an officer of so high rank when there is no place seeking him (row 9802/1; "+P+"in print, Lincoln's telegram, IA letterstelegrams0008abra, below)"),
  "note: L14-B: No. 1 (share .30/.28/.18, not discriminating; read by sense). "+S0+"(a) 0.846 (33/39), (b) p95 0.282, HIT (MS18-R10). In print: IA be-api whole-collection exact-phrase query 'find a place for an officer of so high rank': 88 hits, first on 'Letters and Telegrams of Abraham Lincoln' vol. 8 (IA letterstelegrams0008abra; snippet 'trial, how difficult it is to find a place for an officer of so high rank when there is no place seeking'), also a Missouri Historical Review 1932 issue and a quotation book; the snippet matches the decode word for word; edition page and date not read on a page (to be read by a verifier; the Lincoln Collected Works carries the same telegram by the same phrase). The cached 177 OR volumes have no such phrase. C against the snippet. "+NOCOPY+" Transcription only, leaf not image-read."),
"E614": (hdr(214,9874,208,"22 Oct 1864 Washington 12.30 PM, John Horner (operator) at the Quartermaster General's office, for Col. Brown and Maj. Van Vliet, Quartermaster Department, signed [Qr Master Genl U.S.]: orders on shipment of supplies suspended by my dispatch from City Point are renewed; supplies to be sent to Hilton Head and stored there if storage, until the store houses are filled, the remainder held afloat for instant transfer to some point when needed (row 9874/2; "+P+"in print, OR I/39, below)"),
  "note: L14-B: No. 1 (share .22/.27/.08, No. 2 higher, not discriminating; read by sense). "+S0+"(a) 0.776 (38/49), (b) p95 0.245, HIT (MS18-R10). In print: IA be-api whole-collection exact-phrase query 'held afloat for instant transfer': 8 hits; snippet 'store-houses are filled; the remainder to be held afloat for instant transfer to some other point when needed' in the Official Records vol. 39 (IA warofrebellionco0039unit_y0l1 and warofrebellionco0039majg_t8d1, cu31924079575357); matches the decode word for word; part and page not read. Cached 177 volumes: no phrase hit (vol. 39 not among them). 'Gassette inst.' and 'tooth list' are undecoded groups (M). "+NOCOPY+" Transcription only, leaf not image-read."),
"E615": (hdr(119,9779,113,"8 July 1864 Washington 10 PM, R. R. McCaine (operator), for Maj. Gen. David Hunter, signed [Halleck]: report the positions and numbers of your forces and when they will reach Harper's Ferry; the enemy has crossed the Potomac and appears to be moving by Boonsborough and Middletown on Frederick, his advance under Breckenridge has crossed the Monocacy and is moving on Urbana; unless your forces move forward rapidly they will not be in time (row 9779/0; "+P+"in print, OR I/37 pt 2, word for word)"),
  "note: L14-B: No. 1 (share .52/.41/.20; read by sense). "+S0+"(a) 0.524 (22/42), (b) p95 0.190, HIT (MS18-R10). In print: OR I/37 pt 2 (IA warofrebellion372unit, cached text; page not read), Halleck to Hunter, Washington 8 July 1864 10 p.m., 'Please report the positions and numbers of your forces, and when they will reach Harper's Ferry. The enemy has crossed the Potomac, and appears to be moving by Boonsborough and Middletown on Frederick. His advance, under Breckinridge, has crossed the Monocacy, and is moving on Urbana. Unless your forces move forward rapidly they will not be in time to be of much use'; C against the print (print spells Breckinridge; the ledger's 'Tableling' = moving, a code word read M). "+NOCOPY+" Transcription only, leaf not image-read."),
"E616": (hdr(83,9743,77,"23 May 1864 Washington 9 PM, R. R. McCaine (operator), for Maj. Gen. David Hunter, Cedar Creek, signed [Halleck]: there are no vacancies of brigadier-general of volunteers; you have three generals of cavalry in your department, Stahel, Duffie and Averell, enough for your cavalry; if any are worthless recommend them to be mustered out and I will endorse it; no one can be appointed till some one else is mustered out (row 9743/1; "+P+"in print, OR I/37 pt 1, word for word)"),
  "note: L14-B: No. 1 (share .53/.36/.17; read by sense). "+S0+"(a) 0.629 (22/35), (b) p95 0.286, HIT (MS18-R11). In print: OR I/37 pt 1 (IA warofrebellion371unit, cached text; page 525 by the OCR running head before the 10.30 a.m. telegram of the same date, not read on a page image), Halleck to Hunter, Cedar Creek, Washington 23 May 1864 9 p.m., 'There are no vacancies of brigadier-general of volunteers. You have three generals of cavalry in your department, Stahel, Duffie, and Averell, certainly enough for your cavalry force. If any are worthless recommend them to be mustered out and I will indorse it. No one can be appointed till some one else is mustered out'; C against the print. The ledger's 'Stall Duffin and Dover' = Stahel, Duffie, Averell (undecoded name groups, M). "+NOCOPY+" Transcription only, leaf not image-read."),
"E617": (hdr(26,9686,20,"4 March 1864 by the cipher date words (ledger header 'Mar 14th', unreconciled, M) Washington 10.30 AM, Capt. Geo. H. Smith (operator), for [Curtis, Fort Leavenworth] (name and place groups 'Shelton Curtes', 'Fort 11 worth', M), signed Halleck, General-in-Chief: neither yourself nor any officer under your command will exercise authority over any troops not within the limits of your department when the order establishing it was received; if orders have been issued assuming command of troops outside such boundaries they will be immediately revoked (row 9686/2; "+P+"in print, OR I/34 pt 2, below)"),
  "note: L14-B: No. 1 (share .38/.30/.13; read by sense). "+S0+"(a) 0.788 (26/33), (b) p95 0.273, HIT (MS18-R11). In print: IA be-api whole-collection exact-phrase queries: 'will exercise authority over any troops not within the limits of your department' 5 hits and 'assuming command of troops outside of such boundaries' 7 hits, in the Official Records vol. 34 pt 2 (IA warofrebellion342unit, warofrebellion013402rootrich, cu31924077730251) and other copies; snippets match the decode word for word; the Halleck-to-Curtis date, page and addressee not read on the page (a verifier's); the date mismatch (4 vs 14 March; Halleck was General-in-Chief to 12 March 1864) is for the image check of leaf 9686 (not done). Cached 177 volumes: no phrase hit (vol. 34 pt 2 is not among them). "+NOCOPY+" Transcription only, leaf not image-read."),
}
n = 0
for e, (h, note) in R.items():
    m = re.search(rf"^### {e} \|[^\n]*\n(.*?)(?=\n### |\Z)", t, re.S | re.M)
    if not m: print("missing", e); sys.exit(1)
    if "L14-B; " in t[m.start():m.start()+3000].split("\n")[0]: continue
    body = [l for l in m.group(1).splitlines() if l.strip() and not l.startswith("note: L14-B")]
    new = f"### {e} | {h}\n" + "\n".join(body + [note]) + "\n"
    t = t[:m.start()] + new + t[m.end():]; n += 1
if "--dry" not in sys.argv: p.write_text(t, encoding="utf-8")
print("updated", n)
