#!/usr/bin/env python3
"""MS65-R1: file Y3 (10039/0) and Y4 (10030/2) of ms65_r1_entries.txt into ../ciphertext.txt as E400, E401 (the other seven rows are Step-0 hits or no-book rows: not filed).
Usage: ms65_r1_file.py [--dry]  Idempotent. Both leaves image-read at 2400 px (crops, scratch, not committed)."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
MAP = {
 "Y3": ("E400", "Page 379 | 10039 | mssEC 18 (obj 10074, pointer 10039; printed page 373), 26 June 1865 Washington (hour 3.30 PM), Capt. J. R. Gillmore at Washington (operator header), Jno C Sullivan at Nashville and W. G. Fuller at New Orleans (operators), copy to Schofield (Raleigh), Gillmore (Charleston), Thomas (Nashville), Sheridan (New Orleans), signed [U. S. Grant, M]: commanding officers of North Carolina, South Carolina, Georgia, Alabama, Florida, Mississippi, Louisiana and Texas are instructed that whilst they are not to endanger private property by efforts to seize that heretofore claimed by the so-called Confederate States, they will aid the officers of the Treasury Department in protecting and bringing to market that already in Government possession or included in the surrender of the rebel armies; printed OR I/47 pt 3, I/48 pt 2, I/49 pt 2 (MS65-R1; row 10039/0; leaf image-read at 2400 px (own lines))",
  ["note: MS65-R1: No. 1 (whole-entry vocabulary share No.1 / No.2 / No.9 = .58/.54/.09; No. 2 reads the same H count by count but Butler/Pemberton/Milledgeville nonsense; sense decides, the meaning-shuffled copy gives the same H count so the count control cannot fail). Step-0 (ordered LCS vs the entry's own transcription): a 0.431 (31/72), shuffle p95 0.153, (c) 32 words: not a hit. Printed, clause for clause (C): Grant, Washington 26 June 1865 3.30 p.m., 'Commanding officers of North Carolina, South Carolina, Georgia, Alabama, Florida, Mississippi, Louisiana, and Texas are instructed that whilst they are not to endanger private property by efforts to seize that heretofore claimed by the so-called Confederate States, they will aid the officers of the Treasury Department in protecting and bringing to market that already in Government possession, or which was included in the surrender of the rebel armies': OR I/49 pt 2 (to Thomas; near the running head p.1035, page not read), I/48 pt 2 (to Sheridan, under Chap. LX), I/47 pt 3 (to Schofield, 'Same to Generals Gillmore, Thomas, and Sheridan'); the same order of 26 May 1865 8.30 p.m. to Capt. J. R. Gilmore is OR I/47 pt 3 p.573. The decoder gives the signature as [Washington] and 'Command=Er(-ed,-ing)' for the plain 'Commanding'; the signer is the print's U. S. Grant (M). Image: transcription matches the first lines (page 373, operator header 'Capt J. R. Gillmore', 'Jno C Sullivan Nashville', 'W. G. Fuller New Orleans')."]),
 "Y4": ("E401", "Page 370 | 10030 | mssEC 18 (obj 10074, pointer 10030; printed page 364), 14 June 1865 12.30 AM Washington, to Geo K. Smith at Cumberland Md, for Maj. Gen. W. H. Emory commanding Department of West Virginia, signed by order of Maj. Gen. Hancock, C. W. Clark Jr. A.A.G.: by direction of the President you will cause the rebel General McCausland to be arrested and held until further orders; he is reported to be at his farm opposite Point Pleasant, West Virginia, at the mouth of the Great Kanawha, four miles above Gallipolis; the commanding officer of the post of Gallipolis or Point Pleasant might be best to entrust with the duty of arresting McCausland; not located in print; Cumberland reply of 16 June in holder 7953 (MS65-R1; row 10030/2; leaf image-read at 2400 px (own lines))",
  ["note: MS65-R1: No. 1 (whole-entry vocabulary share No.1 / No.2 / No.9 = .48/.51/.22: favours No. 2 by 3 points; the sense reads No. 1: Emory, West Virginia, Kanawha, Gallipolis, arrest; No. 2 reads Pickets/Harbor nonsense; header 'Tappan Shelby' = Major General, 'Irving' = President (No. 1 rows)). Step-0: a 0.458 (33/72), shuffle p95 0.181, (c) 19 words: not a hit. 'Mac Cause land' / 'Mack Cause Land' is written plain (McCausland, Gen. John McCausland, M for the identity); the decoder reads the plain 'oakumed' as [Arrest] and 'wicked' as [Report] (key rows). Not located in print: OR I/46 pt 3 (IA warofrebellion463unit): McCausland appears only at one index line p.507 and one cavalry mention; 26 dated headings 13-15 June 1865, two with terms (13 June Eckert to Halleck at Richmond, arrest of Northrop; not this). Holder 7953 (received ledger page 295, 12.20 PM Cumberland 16 June 1865, Emory to Col King: 'Gallopolis June 15 to Maj General Emory: Mack cause land is said to be in St Louis Mo. he is not here, have made thorough search (signed) C W Smith Captain Comdg Post'): the reply to this order, a context item not a clear copy. Image: the entry (lower half of the leaf, lines from 'for Tappan Shelby W H Emory' to 'how are you') matches the transcription line by line; signed 'C W Clark Junior A A G'."]),
}
blocks = {}; cur = None
for ln in (HERE/"ms65_r1_entries.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"### (Y\d+) \|", ln)
    if m: cur = m.group(1); blocks[cur] = []; continue
    if cur and ln.strip(): blocks[cur].append(ln)
p = HERE.parent/"ciphertext.txt"; txt = p.read_text(encoding="utf-8")
add = [f"### {nid} | {desc}\n" + "\n".join(blocks[k] + notes) + "\n" for k, (nid, desc, notes) in MAP.items() if f"### {nid} |" not in txt]
if add and "--dry" not in sys.argv: p.write_text(txt.rstrip("\n") + "\n\n" + "\n".join(add), encoding="utf-8")
print(("would add " if "--dry" in sys.argv else "added ") + str(len(add)))
