#!/usr/bin/env python3
"""N2R-3: file Z1-Z9 of ms18/n2r3_entries.txt (mssEC 18 rows read as Cipher No. 2) into ../ciphertext-no2.txt as N2-HA..N2-HI.
Usage: n2r3_file.py [--dry]  Idempotent. Z10-Z12 (the spares 9848/1, 9876/1, 9691/0) are decoded but not filed (the brief's ten rows are met by Z1-Z9; NOTES "## N2R-3").
Every leaf is holder transcription only unless a note says it was image-read."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
HOLDER = "holder transcription, leaf not eye-checked"
def d(page, ptr, row, pp, rest, chk=HOLDER): return f"Page {page} | {ptr} | mssEC 18 (obj 10074, pointer {ptr}; printed page {pp}), {rest} (N2R-3; row {row}; {chk})"
def bk(sh): return "N2R-3: No. 2 (whole-entry vocabulary share No.1 / No.2 / No.9 = " + sh + "); "
MAP = {
 "Z1": ("N2-HA", d(131, 9791, "9791/1", 125, "13 July 1864 11 PM Washington (the ledger's header time 11 PM; Sent ledger, entry 1 of the leaf; entry 0 of the same pointer is E354), signed C. A. Dana (the print), to Lieut. Gen. Grant at City Point ('Crossed'): since my dispatch of last evening to Rawlins there have debarked here of the Sixth Corps 1,689 men and of the Nineteenth Corps 3,560 men, 800 of the Nineteenth landed Monday; Emory has reported in person; the head of Wright's column passed Fort Reno at 5 PM moving out on the Rockville road, his own two divisions and the Nineteenth Corps troops, in all about 15,000 men; Lowell's cavalry about 750; Wright will move on with all practicable energy but is inferior in numbers"),
  ["note: " + bk(".40/.63/.18") + "No. 1 reads 'Hudson ... Movement Dawson Corps ... Impregnable', no clause; No. 2 reads the whole clause, decoded time 11 PM = the header hour and day 13 = the header day (No. 1: 11.30 PM, day not matched; 200-seed shuffle of No. 2: time 4 of 200, day 45 of 200). IN PRINT: OR I/37 pt 2 (IA warofrebellion372unit) pp.259-260, War Department 13 July 1864, 11 p.m., C. A. Dana to Lieut. Gen. Grant, City Point, word for word ('Since my dispatch of last evening to General Rawlins there have debarked here of the Sixth Corps 1,689 men, and of the Nineteenth Corps 3,560 men. ... The head of General Wright's column passed Fort Reno at 5 p. m., moving out on the Rockville road ... Colonel Lowell's cavalry, which is serving with him, amounts to about 750 men'); grade C against the print for every decoded clause; the decoder's '[1600] & [89]' = 1,689, '[3500] & [60]' = 3,560, '[Eastport] at hand' = 'close at hand' (M for the code word), 'Ewell' for 'Edwards' (the print names Edwards Ferry elsewhere; here the print reads 'As you will remember' for the code group, M)."]),
 "Z2": ("N2-HB", d(179, 9839, "9839/0", 173, "12 Sept 1864 8 PM Washington, S. H. Beckwith (operator), to Lieut. Gen. Grant at City Point, signed (decoded) the Quartermaster General (M): Colonel Bingham and the other inspectors have been ordered to report here for instructions; as soon as Bingham arrives he will be sent on the inspection of the Little Rock route unless some other suitable officer reports; Rutherford, chief of one division of this office, has been sent away by the Secretary of War on a special tour of inspection; Biggs cannot be spared; Carr was nominated for promotion as chief quartermaster of the Department of the Arkansas; difficulty in supplying troops at Fort Smith and above; wagon transportation asked from Fort Leavenworth for 1,200 tons a month; the cost this winter will be enormous; they report it impracticable to supply Fort Smith and Gibson by the river; nearly impracticable to supply them by wagon from Fort Hawkinsworth", chk="leaf 9839 (printed p.173) read at 2400 px: header and lines 1-13 agree with the holder transcription, the rest holder transcription only"),
  ["note: " + bk(".30/.47/.14") + "No. 1 reads 'Maj Gen O. O. Howard ... Resist ... Camp Bingham', no clause; No. 2 reads the clause; the day (12th) is plain text in the header only, so the day/time test is not testable here (the control row for this entry reads n/n/n and 0 of 200 shuffles for time; ignore). The context is the Quartermaster's reply to Grant's 11 Sept 1864 10.30 a.m. request for 'a good, competent inspecting officer' for the Department of Arkansas, 'Either Colonel Biggs or Bingham would be good officers' (OR I/41 pt 3, IA warofrebellion413unit, p.157: Grant to Halleck; Judson D. Bingham and Herman Biggs both appear in its index at p.157). Not located in print as this telegram: see NOTES '## N2R-3'. The tail 'Quantrell was arrested today at Indianapolis' (Quantrell = the key's value for a name; M) is a second sentence the reader has not tested."]),
 "Z3": ("N2-HC", d(147, 9807, "9807/1", 141, "2 Aug 1864 Washington (the ledger header '(No 2)'; cipher time word 2.30 PM), S. H. Beckwith (operator), to Lieut. Gen. Grant at City Point: Grover's command of the Nineteenth Corps landed last night; a few companies of Torbert's cavalry are arriving; the transportation of troops in small steamers is slow; several days before Sheridan's division is all landed; as it now stands Wright commands the Sixth Corps, Emory the Nineteenth, Crook the troops of the Department of West Virginia, and Averell and Duffy the cavalry, Hunter being in general command of the whole; if Sheridan is not placed in general command I think he should take all the cavalry but not the Sixth Corps; to make that and the cavalry a single and separate command will ..."),
  ["note: " + bk(".45/.52/.16") + "the same ledger leaf's entry 0 is N2-FF (1 Aug 1864, N2R-1). No. 1 reads 'Brooks for [Knoxville] ... [Demoralize] of morgan', no clause; No. 2 reads the clause, decoded day 2 = header day (shuffle 14 of 200); 'Hotly [?]' for the ledger's 'presume' is a key mismatch (M). The time word 2.30 PM is the key's value for the header's tail, no hour in the header (not testable). Not located in print: see NOTES '## N2R-3'. The entry breaks off at 'will' in the holder transcription: its end is on the next leaf or not transcribed (not read)."]),
 "Z4": ("N2-HD", d(228, 9888, "9888/1", 222, "5 Nov 1864 Washington (ledger header; cipher time word 1 PM), S. H. Beckwith (operator), to Maj. Gen. Grant at City Point, signed Maj. Gen. H. W. Halleck: Price's affair will be over in the course of the next ten days and Reynolds' troops can then be withdrawn from Arkansas; Steele's effective force is about 20,000; Sherman thinks a movement from the Mississippi toward Selma, cutting the Mobile and Ohio Railroad by which Beauregard's army is supplied, will be more advantageous than any operations on the coast; if you are of the same opinion Canby's instructions should be to that effect; for the present all Canby's efforts should be directed to prevent Kirby Smith from sending reinforcements across the river to assist Beauregard against Thomas"),
  ["note: " + bk(".50/.56/.20") + "No. 1 reads 'Maj Genl Wilson's affair ... Newbern'; No. 2 reads the clause, decoded day 5 = header day (shuffle 10 of 200) and time 1 PM (the ledger header has no hour). IN PRINT, with a date difference: OR I/41 pt 4 (IA warofrebellion414unit) near pp.421-424 (the page header preceding the telegram reads 424; leaf not opened), 'Washington, November 4, 1864 -- 12.30 p. m. Lieutenant-General Grant, City Point, Va.: I think from present appearances that Price's affair will be over in the course of the next ten days, and that Reynolds' troops can then be withdrawn from Arkansas. Steele's effective force is now about 20,000. Sherman thinks that a movement from the Mississippi River toward Selma, cutting the Mobile and Ohio Railroad, by which Beauregard's army is now supplied, will be more advantageous to him than any operations on the coast. If you are of the same opinion, General Canby's inst[ructions]...' Grade C against the print for the decoded clauses; the ledger entry is dated 5 Nov and the print 4 Nov 12.30 p.m. (an hour the ledger does not carry): the verifier decides whether this is the same telegram or a repeat, and the date difference is the reader's open question. The tail names the decoded Kossuth (a name code, M)."]),
 "Z5": ("N2-HE", d(213, 9873, "9873/3", 207, "21 Oct 1864 Washington (ledger header; cipher time word 4.30 PM), S. H. Beckwith (operator), to Maj. Gen. Grant at City Point, signed H. W. Halleck: no troops can at present be taken from Sheridan's command and the vessels collected at Alexandria are wanted elsewhere and involve enormous cost for demurrage, so I have directed General Rucker to use them for other purposes, they can be collected again in a week or ten days; nothing satisfactory from Missouri; I can form no clear idea of the condition of affairs from reports received here; Curtis seems to be fighting near Independence but I hear nothing of Rosecrans, A. J. Smith's or Mower's divisions; no action yet as to change of commanders"),
  ["note: " + bk(".31/.41/.13") + "No. 1 reads 'Oliver Brown [Culpepper] ... [Jno A. Dahlgren] ... Chickamauga', no clause; No. 2 reads the clause, decoded day 21 = header day (shuffle 6 of 200); the ledger carries 'Manifest' struck and 'Execute' written (the decoder takes 'Execute'; the print reads 'manifest': M for that word). Same pointer as E330 (20 Oct 1864 3 PM, Halleck to Thomas, entry 2 or 3 of the same leaf). IN PRINT: OR I/41 pt 4 (IA warofrebellion414unit) p.153, Washington, Oct. 21, 1864, Halleck to Lieut. Gen. Grant at City Point, word for word ('As it is manifest that no troops can at present be taken from General Sheridan's command, and as the vessels collected at Alexandria are wanted elsewhere, and involve enormous cost for demurrage, I have directed General Rucker to use them for other purposes. They can be collected again in a week or ten days if required. Nothing satisfactory from Missouri. I can form no clear idea of the condition of affairs from reports received here. General Curtis seems to be fighting near Independence, but I hear nothing of Rosecrans, A. J. Smith's or Mower's divisions. No action yet as to change of commanders.'); grade C against the print."]),
 "Z6": ("N2-HF", d(153, 9813, "9813/0", 147, "6 Aug 1864 Washington, F. T. Bickford (operator), to Brig. Gen. Ingalls (Quartermaster, City Point; decoded 'Quarter Master', the addressee 'Palermo In galls' = Ingalls), signed (decoded) the Quartermaster General (M): I have telegraphed to secure in Baltimore, Philadelphia and New York steamboats in addition to those now employed to move 12 or 13,000 men; we had here waiting orders and sent them all to City Point when the present movement began, steamers estimated by General Rucker to have a capacity of 19,000 infantry; when those now ordered arrive there will be room for over 30,000 men; this is to be kept in readiness for any necessary movement; in case of urgent necessity the flag-of-truce boats and the boats about Fort Monroe will of course be used"),
  ["note: " + bk(".35/.43/.21") + "same pointer as E327 (6 Aug 1864, Cavalry Bureau telegram to Hunter, entry 1 of the leaf); this entry is entry 0. No. 1 reads 'Casualties In galls Pursue ... Baton Rouge Tuscumbia & Shelbyville ... Chattanooga'; No. 2 reads the clause. The ledger header has no hour and the day is plain text (day/time not testable here; the control row reads n/n/n, ignore). 'Acton's of truce boats' is the key's value for 'flags' (M). Not located in print: see NOTES '## N2R-3'. OR I/40 pt 2 and pt 3 and I/42 pt 2 date windows 5-7 Aug for steamers/Rucker/capacity 19,000 gave only Meigs's 7 Aug telegram about Wilson's division embarking (a different text)."]),
 "Z7": ("N2-HG", d(180, 9840, "9840/0", 174, "13 Sept 1864 Washington (ledger header; cipher time word 11.30 AM), S. H. Beckwith (operator), to Lieut. Gen. Grant at City Point: in accordance with your previous instructions I directed General A. J. Smith to take charge of the expedition against Price and Co. and to select his own line of operations after consulting with Rosecrans and others; I so informed Rosecrans and directed him to assist Smith; Smith answered that he would wait for further news from Price before deciding but thought it probable that he would move by St. Louis and Rolla; is it now your wish that these orders be countermanded and that Smith report for orders to Rosecrans; before acting on your telegram of yesterday I wish you to understand precisely what orders have already been given"),
  ["note: " + bk(".36/.41/.12") + "No. 1 reads 'Hudson [Knoxville] ... Harding ... Maj Genl Wilson & Co'; No. 2 reads the clause, decoded day 13 = header day (shuffle 6 of 200), time 11.30 AM (the key's value for the sent hour; the ledger header has no hour). The decoded 'Lieut Gen U.S. Grant' fills the addressee slot; the signature (Halleck) is not in the transcription. IN PRINT: OR I/41 pt 3 (IA warofrebellion413unit) near p.170, 'Washington, September 13, 1864 -- 11.30 a. m. Lieutenant-General Grant, City Point, Va.: In accordance with your previous instructions to me I directed General A. J. Smith to take charge of the expedition against Price & Co., and to select his own line of operations after consulting with General Rosecrans and others. I so informed General Rosecrans, and directed him to assist Smith all he could. Smith answered that he would wait for further news from Price before deciding, but thought it probable that he would move by Saint Louis and Rolla. Is it now your wish that these orders be countermanded, and that Smith report for orders to General Rosecra[ns]...'; word for word; grade C against the print (page from the nearest preceding page header, leaf not opened)."]),
 "Z8": ("N2-HH", d(114, 9774, "9774/3", 108, "6 July 1864 Washington (ledger header; cipher time word 2 PM), S. H. Beckwith (operator), to Lieut. Gen. Grant at City Point, signed H. W. Halleck: General Howe has reached Harper's Ferry ('Chum') with his command; Sigel is expecting an attack today; most of Hunter's forces have reached Parkersburg and are coming forward; it is believed that Ewell's corps under Early is in the Valley; it is reported that Sigel abandoned a large amount of public stores at Martinsburg without making any defense; as that place was without fortifications and only a mere outpost it is difficult to understand why the stores were taken from the depot at Harper's Ferry"),
  ["note: " + bk(".43/.50/.20") + "same pointer as E377 (5 July 1864 4 PM, Halleck to Hunter, entry 2 of the leaf); this entry is 3 and breaks off at 'depot at' in the holder transcription. No. 1 reads 'Maj Gen O. O. Howard ... Government Home ... Chum', no clause; No. 2 reads the clause. IN PRINT: OR I/37 pt 2 (IA warofrebellion372unit) p.79, Washington, July 6, 1864 -- 2 p. m. (received 7th), Halleck to Lieut. Gen. Grant, City Point, word for word ('General Howe has reached Harper's Ferry with his command. Sigel is expecting an attack to-day. Most of Hunter's forces have reached Parkersburg, and are coming forward. It is believed that Ewell's corps, under Early, is in the Valley. It is reported that Sigel abandoned a large amount of public stores at Martinsburg, without making any defense. As that place was without fortifications, and only a mere outpost, it is difficult to understand why the stores were taken from the depot at Harper's Ferry.'); grade C against the print. The key's 'Chum' = Harper's Ferry and 'Home' = Howe are the ledger's own spellings of two code words; the code word 'Chum' is the key's value for a place name (a candidate attested here against the print: M for that single value)."]),
 "Z9": ("N2-HI", d(27, 9687, "9687/0", 21, "15 March 1864 10.30 AM Washington, S. H. Beckwith (operator), to Lieut. Gen. Grant at Nashville, signed H. W. Halleck, Major-General, Chief of Staff: a despatch just received from Banks, dated 6 March, says he expects to effect a junction with Sherman's forces on Red River by the 17th; he desires that positive orders be sent to Steele to move in conjunction with them for Red River with all his available forces; Sherman and Banks are of opinion that Steele can do much more than make a mere demonstration as he last proposed; a telegram from you might decide him; veterans of the Ninth Corps ordered to Annapolis"),
  ["note: " + bk(".47/.76/.22") + "No. 1 reads 'Lee's Jones Enoch ... Maj Gen Joseph Hooker', no clause; No. 2 reads the clause; the cipher time word 10.30 AM = the header hour under No. 1 and No. 2 alike (not selective), the decoded day 15 = header day under No. 2 only (shuffle 22 of 200). IN PRINT: OR I/34 pt 2 (IA warofrebellion013402rootrich) pp.609-610, Washington, March 15, 1864 -- 10.30 a. m., Halleck to Lieut. Gen. Grant, Nashville, word for word ('A dispatch just received from General Banks, dated March 6. He expects to effect a junction with Sherman's forces on Red River by the 17th. He desires that positive orders be sent to General Steele to move in conjunction with them for Red River with all his available forces. Sherman and Banks are of opinion that Steele can do much more than make a mere demonstration, as he last proposed. A telegram from you might decide him. Veterans of the Ninth Corps ordered to Annapolis.'); grade C against the print (the OCR reads the headers 610 mid-telegram, the telegram begins on p.609)."]),
}
blocks = {}; cur = None
for ln in (HERE/"n2r3_entries.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"### (Z\d+) \|", ln)
    if m: cur = m.group(1); blocks[cur] = []; continue
    if cur and ln.strip(): blocks[cur].append(ln)
p = HERE.parent/"ciphertext-no2.txt"; txt = p.read_text(encoding="utf-8")
add = [f"### {nid} | {desc}\n" + "\n".join(blocks[k] + notes) + "\n" for k, (nid, desc, notes) in MAP.items() if f"### {nid} |" not in txt]
if add and "--dry" not in sys.argv: p.write_text(txt.rstrip("\n") + "\n\n" + "\n".join(add), encoding="utf-8")
print(("would add " if "--dry" in sys.argv else "added ") + str(len(add)))
