#!/usr/bin/env python3
"""N2R-4 (10 Oct 2026): file Z1-Z10 of ms18/n2r4_entries.txt (mssEC 18 rows read as Cipher No. 2) into ../ciphertext-no2.txt as N2-IA..N2-IJ.
Usage: n2r4_file.py [--dry]  Idempotent. Every leaf is holder transcription only (no leaf was opened for this job; NOTES "## N2R-4")."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
HOLDER = "holder transcription, leaf not eye-checked"
def d(page, ptr, row, pp, rest): return f"Page {page} | {ptr} | mssEC 18 (obj 10074, pointer {ptr}; printed page {pp}), {rest} (N2R-4; row {row}; {HOLDER})"
def bk(sh): return "N2R-4: No. 2 (whole-entry vocabulary share No.1 / No.2 / No.9 = " + sh + "); "
MAP = {
 "Z1": ("N2-IA", d(41, 9701, "9701/0", 35, "9 April 1864 1.30 PM Culpeper, S. H. Beckwith (operator), to Lieut. Gen. Grant, signed (decoded) Halleck (M): a veteran Maryland infantry regiment of the Twelfth Corps (Slocum) has been detained in Baltimore a few days for a special purpose; if it is intended to bring more troops from the West here or to West Virginia it would save transportation to take this one; Burnside will be given another battery in place of that now in the Army of the Potomac"),
  ["note: " + bk(".52/.59/.25") + "No. 1 reads 'Knoxville ... Baton Rouge ... Maj Gen Joseph Hooker', no clause; No. 2 reads the clause; decoded time 1.30 PM = header 1.30 pm (shuffle 3 of 200), decoded day not matched (shuffle 14 of 200). Not located in print: see NOTES '## N2R-4' (OR I/33 searched; the 8 April 1864 Halleck to Grant telegram on p.821 is a different text)."]),
 "Z2": ("N2-IB", d(190, 9850, "9850/1", 184, "25 Sept 1864 Washington, S. H. Beckwith (operator), to Lieut. Gen. Grant, signed (decoded) the Secretary of War (M): it is important to remove Heintzelman from any function and perhaps Rosecrans; have you any objection to Hooker being assigned to the place of one of them; there is no vacant major-general's place for Crook but I am disposed to muster out Heintzelman and make a vacancy; Crook shall have the one that occurs; Duval promoted immediately"),
  ["note: " + bk(".33/.46/.13") + "same pointer as 9850/2 (26 Sept, not read here). No. 1 reads 'Prentiss ... Hartsuff', no clause; No. 2 reads the clause; the decoded numeral [20] against the header day 25 does not match (shuffle 0 of 200 for the day), no hour in the header (not testable). 'Duval Harbor promoted' the last words are not read (M). Not located in print: see NOTES '## N2R-4'."]),
 "Z3": ("N2-IC", d(95, 9755, "9755/0", 89, "7 June 1864 Washington (cipher time word 3.30 PM), S. P. Kimber (operator), to Maj. Gen. Canby, signed (decoded) Meigs, Quartermaster General (M): what is the gauge of the Vicksburg and Monroe railroad; in the annual report of the Directors there is no grading between Monroe and Shreveport; it is not likely that any work has been done upon it since this rebellion; it is 74 and a quarter miles from Vicksburg to Monroe"),
  ["note: " + bk(".37/.57/.18") + "No. 1 reads 'Maj Gen B. M. Prentiss ... Johnston ... Junction', no clause; No. 2 reads the clause, decoded day 7 = header day (shuffle 25 of 200), time 3.30 PM not in the header (not testable). Context only: Meigs to Canby 17 June 1864 1.30 p.m., 'I learn that the gauge of the Vicksburg and Shreveport Railroad is 5 feet 0 inches ... I have telegraphed you twice to inform me of the gauge' (OR I/34 pt 4 pp.424-425), a later and different text. Not located in print as this telegram: see NOTES '## N2R-4'."]),
 "Z4": ("N2-ID", d(238, 9898, "9898/2", 232, "23 Nov 1864 10.30 AM Washington, to Col. G. H. Sharpe (decoded; the ledger 'G H Sharp'), signed G. K. Leet (the ledger's own signature): all the hotels in this city and Georgetown have been searched for the man Buyers without avail; there is no hotel at the corner of 21st Street and Pennsylvania Avenue; Captain Potts commanding detectives and patrols will make every effort to find Buyers but thinks he is not in the city"),
  ["note: " + bk(".38/.49/.07") + "No. 1 reads 'Longstreet ... Command ... Rail Road', no clause; No. 2 reads the clause, decoded day 23 = header day (shuffle 6 of 200) and time 10.30 AM = the header hour (shuffle 2 of 200). 'Buyers' is the ledger's own plain spelling of the man's name (the OCR of OR I/45 and I/41 pt 4 gives only unrelated 'buyers'); 'Pontiac' decodes to City (M for the place). Not located in print: see NOTES '## N2R-4'."]),
 "Z5": ("N2-IE", d(99, 9759, "9759/0", 93, "13 June 1864 8 PM Washington, to Maj. Gen. Canby at Vicksburg, signed Col. J. A. Hardie (decoded 'Colonel Hardie'): with regard to the subject of your telegram of the 4th instant to Meigs, the supply of stock and materials for the repair of the railroad from Vicksburg to Monroe, I am directed by the Secretary of War to say that the expediency of the expense is so much doubted that it has been referred to Lieutenant General Grant"),
  ["note: " + bk(".51/.54/.14") + "same pointer as E379 (13 June 1864 12 m, entry 1 of the leaf); this entry is entry 0. No. 1 reads 'Norfolk ... Johnston ... Columbus', no clause; No. 2 reads the clause, decoded day 13 = header day (shuffle 14 of 200) and time 8 PM = header hour (shuffle 8 of 200). IN PRINT: OR I/34 pt 4 (IA warofrebellion013404rootrich) p.331 (the page header 332 follows the next telegram; leaf not opened), 'Washington, D. C., June 13, 1864 -- 8 p. m. (Received New Orleans, 24th.) Major-General Canby, Vicksburg, Miss.: With regard to subject of your telegram of the 4th instant to General Meigs, the supply of stock and materials for the repair of the railroad from Vicksburg to Monroe, I am directed by the Secretary of War to say that the expediency of the expense is so much doubted as that it has been referred to Lieut. Gen. U. S. Grant. Jas. A. Hardie, Colonel and Inspector-General.'; word for word; grade C against the print."]),
 "Z6": ("N2-IF", d(25, 9685, "9685/1", 19, "10 March 1864 Washington, to Lieut. Gen. Grant, Commander in Chief, Headquarters Army of the Potomac, signed (decoded) the Secretary of War (Stanton): pursuant to the authority of the act of Congress approved February 29 (decoded 'Feb 4700', M), the President by Executive order of this date has assigned to you the command of the Armies of the United States"),
  ["note: " + bk(".25/.45/.07") + "No. 1 reads 'Kirby Smith ... Culpepper ... Georgia', no clause; No. 2 reads the clause; the header has no hour; decoded day [4] against header day 10 is not a match (shuffle 3 of 200); 'Chattahoochee' for the print's 'authority' is a key mismatch (M), the clerk's 'Perkins' insertion is the decoded 'Perkins' (M). IN PRINT: OR I/33 (IA warofrebellion33unit) pp.663-664 (the page header 664 follows the next circular; leaf not opened), 'War Department, March 10, 1864 -- 1.40 p. m. Lieut. Gen. U. S. Grant, Commander-in-Chief, Hdqrs. Army of the Potomac: Pursuant to the authority of the act of Congress approved February 29, 1864, the President, by Executive order of this date, has assigned to you the command of the Armies of the United States. Edwin M. Stanton, Secretary of War.'; word for word; grade C against the print (the same order is in OR I/32 pt 3, IA warofrebellion323unit)."]),
 "Z7": ("N2-IG", d(246, 9906, "9906/0", 240, "5 Dec 1864 11 AM Washington, S. H. Beckwith (operator), to Lieut. Gen. Grant, signed Rufus Ingalls, Brig. General, Quartermaster (the ledger's own 'Roof us In galls'): the vessels will be ready; should they not be assembled at Bridgeport (M for the place name) instead of at Monroe (M); if so please cause General Rucker to be notified; I shall leave at 3 PM to-day"),
  ["note: " + bk(".41/.50/.22") + "No. 1 reads 'Knoxville ... Bowling Green ... Secretary of State', no clause; No. 2 reads the clause, decoded day [5] = header day (shuffle 7 of 200) and time 11 AM = header hour (shuffle 3 of 200); the clause 'I shall leave at 3 PM' carries a second decoded time word. The two place names are the key's values for place codes and are M here. Not located in print: see NOTES '## N2R-4'."]),
 "Z8": ("N2-IH", d(79, 9739, "9739/2", 73, "19 May 1864 8.30 PM Washington (the ledger's '( 2 )' header), S. H. Beckwith (operator), to Lieut. Gen. Grant, signed (decoded) C. A. Dana (M): it is Canby and not Hurlbut who commands the combined departments of the Gulf and Arkansas; Hurlbut is not on duty; Banks is to be relieved and Reynolds appointed to command the department; the order will be issued tomorrow"),
  ["note: " + bk(".50/.57/.18") + "No. 1 reads 'Knoxville ... Hooker ... Gillmore', no clause; No. 2 reads the clause, decoded day [19] = header day (shuffle 7 of 200) and time 8.30 PM = header hour (shuffle 5 of 200). 'Hurlbut' is the ledger's plain spelling. Not located in print: see NOTES '## N2R-4'."]),
 "Z9": ("N2-II", d(122, 9782, "9782/0", 116, "9 July 1864 Washington (ledger header 10.30 PM; decoded time 11 PM), to Lieut. Gen. Grant, signed Halleck: as the arrival of the Nineteenth Corps is very uncertain I think the remainder of the Sixth Corps should be sent to this place; I have ordered all troops [from the North] to be stopped at Baltimore for the defense of that city"),
  ["note: " + bk(".48/.52/.08") + "same pointer as N2-FG (10 July 1864 12.30 AM, entry 2 of the leaf); this entry is entry 0. No. 1 reads 'Howard ... Baton Rouge ... Thomas', no clause; No. 2 reads the clause; the decoded time 11 PM equals the printed hour, the ledger header writes 10.30 PM (so the time word does not match the header, and the decoded day does not either: shuffle 3 of 200 for the time, 8 for the day). IN PRINT: OR I/40 pt 3 (IA warofrebellion403unit), 'Washington, July 9, 1864 -- 11 p. m. Lieutenant-General Grant, City Point, Va.: As the arrival of the Nineteenth Corps is very uncertain, I think the remainder of the Sixth Corps should be sent to this place. I have ordered all troops from the North to be stopped at Baltimore for the defense of that city. H. W. Halleck, Major-General and Chief of Staff.' (page not read from the OCR text; leaf not opened); word for word except the ledger's lacking 'from the North'; grade C against the print."]),
 "Z10": ("N2-IJ", d(220, 9880, "9880/0", 214, "31 Oct 1864 3 PM Washington (ledger header 'No 2'), S. H. Beckwith (operator), to Lieut. Gen. Grant, signed H. W. Halleck: telegram just received from General Curtis states that Rosecrans has recalled his troops from the pursuit of Price; this is contrary to repeated orders; I have just telegraphed that the pursuit must be continued"),
  ["note: " + bk(".50/.69/.27") + "No. 1 reads 'Culpepper ... Curtis ... Brannon', no clause; No. 2 reads the clause; the decoded day word is 'Monday' (not the header's 31) and the entry carries no decoded time word (header '3 pm' plain; control reads n/n/n, shuffle 0 of 200 for both). IN PRINT: OR I/41 pt 4 (IA warofrebellion414unit) p.337 (the page header 338 follows it; leaf not opened), 'Washington, D. C., October 31, 1864 -- 3 p. m. Lieutenant-General Grant, City Point: Telegram just received from General Curtis states that General Rosecrans has recalled his troops from the pursuit of Price. This is contrary to repeated orders. I have just telegraphed that the pursuit must be continued. H. W. Halleck, Major-General and Chief of Staff.'; word for word; grade C against the print."]),
}
blocks = {}; cur = None
for ln in (HERE/"n2r4_entries.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"### (Z\d+) \|", ln)
    if m: cur = m.group(1); blocks[cur] = []; continue
    if cur and ln.strip(): blocks[cur].append(ln)
p = HERE.parent/"ciphertext-no2.txt"; txt = p.read_text(encoding="utf-8")
add = [f"### {nid} | {desc}\n" + "\n".join(blocks[k] + notes) + "\n" for k, (nid, desc, notes) in MAP.items() if f"### {nid} |" not in txt]
if add and "--dry" not in sys.argv: p.write_text(txt.rstrip("\n") + "\n\n" + "\n".join(add), encoding="utf-8")
print(("would add " if "--dry" in sys.argv else "added ") + str(len(add)))
