#!/usr/bin/env python3
"""N2R-6: file the five non-hit entries of ms18/n2r6_entries.txt (Z4 Z5 Z7 Z8 Z9, mssEC 18 rows read as Cipher No. 2) into ../ciphertext-no2.txt as N2-KA..N2-KE.
Z1 Z2 Z3 Z6 are step-0 hits under the Wave 3 ruling (body in holder transcription) and are NOT filed. Usage: n2r6_file.py [--dry]  Idempotent.
Every leaf is holder transcription only (no leaf was opened)."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
HOLDER = "holder transcription, leaf not eye-checked"
def d(page, ptr, row, rest): return f"Page {page} | {ptr} | mssEC 18 (obj 10074, pointer {ptr}; printed page {page-6}), {rest} (N2R-6; row {row}; {HOLDER})"
def bk(sh): return "N2R-6: No. 2 (whole-entry vocabulary share No.1 / No.2 / No.9 = " + sh + "); "
MAP = {
 "Z4": ("N2-KA", d(69, 9729, "9729/1", "3 May 1864 11 AM Washington ('S. H. Beckwith, Washn May 3rd 1864'; entry 1 of the leaf), to Lieut. Gen. Grant at Culpeper, signed H. W. Halleck: your last instructions in regard to [matters] were telegraphed to [Cairo] and were sent by [General] [name unresolved] on [1 May]; the President has seen your telegrams but has said nothing to me on the subject since I last wrote to you; I will write to you immediately"),
  ["note: " + bk(".39/.58/.19") + "No. 1 reads 'Kirby Smith ... Knoxville ... Fredericksburg', no consistent clause; No. 2 reads the whole clause, decoded date 'May 3' = header day (200-seed shuffle: 11 of 200, weak). Coherence -6.288 / -5.594 / -6.946, shuffled No. 2 -5.980 / -6.866 / -5.947 (No. 2 beats all, by 0.35 over the best shuffle). M by hand: 'BrayMan' (the sender of the instructions), 'done the [River] on [May] [1]' (decoder row 'Wafer' = River), 'Protect' read for 'subject'; 'Telegraph(-ed)' for 'whimpered'. Not located in print."],
 ),
 "Z5": ("N2-KB", d(37, 9697, "9697/0", "7 Apr 1864 1 PM Washington ('SH Beckwith (2), Washn April 7th 1864 1 P. M'; entry 0 of the leaf), to Lieut. Gen. Grant at Culpeper, signed H. W. Halleck: [Burnside] left unexpectedly last night; your message will be sent to him in cipher as soon as he can be found; 'Manngo' has been relieved and troops ordered as directed; [Sigel] asks that a regiment of heavy artillery be sent from 'Pard' [Baltimore?] to garrison [Harpers Ferry]; shall it be done? (the ledger adds 'fine day this')"),
  ["note: " + bk(".56/.62/.28") + "No. 1 reads 'Danville ... Cut off ... Drove in our pickets', no consistent clause; No. 2 reads the whole clause; no decoded day numeral (header gives 7th); decoded 1 PM = header. Coherence -6.371 / -5.415 / -8.080, shuffled No. 2 -6.748 / -7.069 / -7.424. M by hand: 'Manngo', 'Pard' (the sending place of the heavy-artillery regiment), the first name ([Burnside], by the key) and 'Left' (a code word). Context in the holder transcription (not a copy): 10215 (Sigel to the Adjutant General, Cumberland 6 Apr 1864 8.30 PM: the regiment of heavy artillery now at Baltimore to be sent to Harpers Ferry to garrison) and 10219 (Grant to Halleck, 7 Apr 8 PM: 'order a regiment of heavy artillery from Balt Maryland to Harpers Ferry'); the Sigel request is the subject of this telegram. Not located in print as this telegram (OR I/33 p.813 and its neighbours print Sigel's 6 Apr request)."],
 ),
 "Z7": ("N2-KC", d(248, 9908, "9908/2", "6 Dec 1864 1 PM Washington ('Beckwith City Pt., Washn D.C. Dec 6. 1864'; entry 2 of the leaf), to Lieut. Gen. Grant, signed Halleck: [Sheridan] was ordered some days ago to report in regard to the New Creek disaster; the movements asked for by [Thomas] against the Mobile and Ohio Railroad were ordered by [Canby] on the 25th and 26th ult. and these orders have been repeated"),
  ["note: " + bk(".36/.55/.18") + "No. 1 reads 'Overtook the Enemy ... Jno A. Dahlgren ... Resist', no clause; No. 2 reads the whole clause, no decoded day numeral (header gives the 6th). Coherence -6.869 / -6.079 / -8.448, shuffled No. 2 -7.674 / -6.958 / -7.843. M by hand: 'Sheridan' (code 'chart Negus'), 'Thomas' and 'Canby' (names read by the key from code words), the sender 'Halleck' (tail), 'Tuesday', 'Mobile & Ohio Rail-road' ('Galway & Biscay Walnut'). Not located in print as this telegram, but its second sentence is word for word the printed Halleck to Thomas, Washington 6 Dec 1864 1 p.m. (OR I/45 pt 2, IA warofrebellion452unit, p.71: 'The movements against the Mobile and Ohio Railroad were ordered by General Canby on the 25th and 26th ultimo, and the orders have been repeated') and the New Creek subject is the printed Stanton to Sheridan 6 Dec 9.30 p.m. (OR I/43 pt 2, IA warofrebellion432unit, p.746); the telegram to Grant is the companion, not located."],
 ),
 "Z8": ("N2-KD", d(138, 9798, "9798/1", "19 July 1864 4 PM Washington ('SH Beckwith, Washn July 19th 1864'; entry 1 of the leaf), to Lieut. Gen. Grant, signed H. W. Halleck: I am of the opinion that another regiment of heavy artillery, in addition to those with General Wright ('Right' by the key, M), should be sent here as soon as you can spare it; I have written to-day at length"),
  ["note: " + bk(".50/.58/.33") + "No. 1 reads 'Knoxville ... Reinforcements of Heavy Battery', no consistent clause; No. 2 reads the whole clause, decoded day 19 = header day (200-seed shuffle: 7 of 200). Coherence -5.596 / -4.407 / -6.638, shuffled No. 2 -6.120 / -6.251 / -6.641. IN PRINT word for word: OR I/37 pt 2 (IA warofrebellion372unit), Halleck to Grant, 'Washington, July 19, 1864 - 4 p. m.', 'I am of the opinion that another regiment of heavy artillery, in addition to those with General Wright, should be sent here as soon as you can spare it. I have written to-day at length. H. W. Halleck'; page not read (OCR running heads 388 and 385 either side; about pp.384-385, M). Grade C."],
 ),
 "Z9": ("N2-KE", d(172, 9832, "9832/1", "3 Sept 1864 9.30 PM City Point ('Beckwith City Pt., Wash. Sept. 3. 1864 930 pm'; entry 1 of the leaf), to Captain M. Smith, Senior Naval Officer, James River, City Point, signed Gideon Welles (Secretary of the Navy; the ledger's closing code words 'Benjamin Paulding' read [Secretary of Navy] by the key, M): the Onondaga and the Atlanta will be the only ironclads retained in the James River; prepare the Saugus and Canonicus to go south; convoy will be sent from the north; answer"),
  ["note: " + bk(".41/.56/.22") + "No. 1 reads 'Minnesota ... Chattanooga ... Report', no clause; No. 2 reads the whole clause, decoded day 3 = header day (200-seed shuffle: 9 of 200), decoded 9.30 PM = header. Coherence -8.806 / -7.224 / -9.672, shuffled No. 2 -8.428 / -9.455 / -8.446. IN PRINT word for word: Official Records of the Union and Confederate Navies, ser. I vol. 10 (IA officialrecordso0010unse), North Atlantic Blockading Squadron, p.418 (between running heads 418 and 419), Gideon Welles to Captain M. Smith, Senior Naval Officer, James River, City Point, 'Navy Department, September 5 [OCR; the neighbouring entries are 3 Sept], 1864. The Onondaga and the Atlanta will be the only ironclads retained in James River. Prepare the Saugus and Canonicus to go south. Convoy will be sent from the north. Answer. Gideon Welles, Secretary.' The print dates it September 3 or 5 by the OCR; the ledger gives 3 Sept 9.30 p.m. (not resolved, M). Grade C. Decoder slip noted M: 'Fear' read for 'from'."],
 ),
}
blocks = {}; cur = None
for ln in (HERE/"n2r6_entries.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"### (Z\d+) \|", ln)
    if m: cur = m.group(1); blocks[cur] = []; continue
    if cur and ln.strip(): blocks[cur].append(ln)
p = HERE.parent/"ciphertext-no2.txt"; txt = p.read_text(encoding="utf-8")
add = [f"### {nid} | {desc}\n" + "\n".join(blocks[k] + notes) + "\n" for k, (nid, desc, notes) in MAP.items() if f"### {nid} |" not in txt]
if add and "--dry" not in sys.argv: p.write_text(txt.rstrip("\n") + "\n\n" + "\n".join(add), encoding="utf-8")
print(("would add " if "--dry" in sys.argv else "added ") + str(len(add)))
