#!/usr/bin/env python3
"""O9R-1: file G1-G11 of ms18/o9r1_entries.txt (mssEC 18 rows guessed Cipher No. 9; 10 rows, 9684/0 holds two telegrams) into ../ciphertext-no9.txt as O9-DA..O9-DK.
Usage: o9r1_file.py [--dry]   Idempotent. Per-entry note lines (plain: / variant: / graded:) are decode.py's existing mechanism; key-no9.md is not touched."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent.parent
def d(page, ptr, pp, rest, row, eye): return f"Page {page} | {ptr} | mssEC 18 (obj 10074, pointer {ptr}; printed page {pp}), {rest} (O9R-1; row {row}; {eye})"
HT = "holder transcription, leaf not eye-checked"
COH = {"G1": "-9.945/-9.405/-9.995; shuffled No. 9 -9.815/-9.990/-9.795", "G2": "-6.211/-6.376/-6.578; -6.720/-6.642/-6.617", "G3": "-7.515/-7.280/-7.255; -7.645/-7.778/-7.737",
       "G4": "-6.916/-6.791/-6.598; -7.040/-6.853/-6.936", "G5": "-7.138/-7.370/-7.053; -7.646/-7.300/-7.259", "G6": "-7.071/-7.124/-7.103; -7.204/-7.188/-7.087",
       "G7": "-5.995/-6.370/-5.525; -6.195/-6.097/-6.001", "G8": "-7.047/-7.020/-6.656; -7.104/-7.241/-7.165", "G9": "-8.082/-7.859/-6.926; -7.697/-7.586/-8.598",
       "G10": "-7.020/-6.594/-7.255; -7.354/-7.493/-7.391", "G11": "-7.989/-6.992/-6.373; -6.680/-6.735/-6.413"}
def n(k, text):
    return ["note: O9R-1: No. 9 (header words decide, not the coherence number: bigram coherence per word-pair, No. 1 / No. 2 / No. 9; " + COH[k] + "; ms18/o9r1_coherence.out, a weak instrument at this length, O9-BOOK's finding repeated). " + text]
MAP = {
 "G1": ("O9-DA", d(49, 9709, 43, "19 Apr 1864 Washington (cipher time word Viola 12.30 PM; the ledger header has no time), John Horner (operator, New York), to R. C. Morgan, [Colonel] H. S. Olcott, 93 Franklin St: send immediately to Secretary Fox the full names of Simpson, Barlow, Haestis(?), Hunter, Kilsey; then enquire at the Brooklyn Yards if master Painter has absconded; all right here; probably return with Wilson tonight; signed H. S. Olcott (plain); tail 'Canon & C' unread", "9709/1", HT + "; leaf 9709 fetched to scratch, not read"),
  ["plain: Wilson", "graded: Can:M", "graded: Canon:M"],
  n("G1", "Book test: place word Pagan = Washington agrees with the header dateline ('Washn D. C.') and the date words agree; 'Vesper' = Colonel only under No. 9 (No. 1 Position, No. 2 Re-enforcements) and the same Olcott is 'Venus/Vesper' Colonel in O9-DE, O9-DH, O9-DI; the time word Viola (12.30 PM) cannot be tested (no header time). Decoder slip: 'Wilson' has a key row (Invested) on a plain name, set plain (M, not a key edit). Unread by the sample table: 'Can' (before Vesper) and 'Canon' (tail), 2 tokens, graded M. Weakest filing of the ten on content (the body is plain names and a navy-yard question). Not located in print or in the holder's other pages (CISOSEARCHALL 'Brooklyn Yards master Painter absconded': 9709 only); Fox Confidential Correspondence vol. 2 'Olcott': see NOTES.")),
 "G2": ("O9-DB", d(148, 9808, 142, "3 Aug 1864 Washington 4 PM (cipher time word Henrietta = 4 PM = the header's own time), E. W. Culgan (operator), Halleck to Maj. Gen. Couch, Pittsburg (address group 'Optic' unread): as a new raid may immediately follow and be directed towards Pittsburg, the instructions in regard to blocking up the roads leading from the Cumberland Valley should be carried out; a space could be left in the barriers for trains [print: teams] to pass through, and means to close it in case of danger; the town and county authorities should do this for their own protection; I will endeavor to send you some engineer officers [ledger 'Preston Officers'] to assist in this matter; signature groups 'Austria Mohawk', not read; printed OR I/37 pt 2 p.590", "9808/2", "header time word, 'Optic' and the signature line read on a 2400 px crop"),
  ["plain: valley", "variant: Austria=Austria:M", "graded: Optic:M", "graded: Preston:M", "graded: Mohawk:M"],
  n("G2", "Book test: the time word Henrietta = 4 PM agrees with the header's 4 PM under No. 9 only (No. 1/2: 2.30 PM); no label and no place word, so this is ONE test, the weakest book call of the ten (a 1-in-48 chance word, 2.5% shuffle floor in LS3-R18's control, not rerun). Printed OR I/37 pt 2 p.590 (IA warofrebellion372unit; Halleck to Major-General Couch, Pittsburg, Washington 3 Aug 1864): word for word apart from 'teams' (print) / 'trains' (ledger text) and 'engineer' / 'Preston'; C against the print. Print-match instrument (o9r1_printmatch.out): No. 9 0/2 word tokens match the print, No. 1 0/5, No. 2 0/6, shuffled No. 9 max 1 of 20 seeds: the instrument is silent because the entry is nearly plain. DATA CONFLICT: 'Austria' is 'Abel/Austria = Sec. of State' (key-no9.md, H, p.[9]) and the print signs H. W. Halleck, whom 'Abortion' reads in O9-DJ and O9-DK; 'Austria' is graded M here (variant), the groups 'Austria Mohawk' are the clerk's signature groups, not read. Decoder slip: 'valley' has a key row (Valley/Vermont = Brig. Gen.) on the plain word, set plain. Unread by the table: 'Optic' (= Maj. Gen. Couch by the print, C, not tabled), 'Preston' (= engineer by the print, not tabled), 'Mohawk': 3 tokens graded M.")),
 "G3": ("O9-DC", d(13, 9673, 7, "5 Feb 1864 Washington (cipher time word Henrietta = 4 PM; the ledger header has none), John Horner (operator, label '9' after his name), Meigs (signed M. C. Meigs, Quartermaster General) to Major Van Vliet, Quartermaster, New York: let all expenses incurred in charter and outfit and victualling, manning, sailing, loading, including stores and rations from the Subsistence Department, put on board [the] Maria C. Day be kept in a separate and distinct account so that the cost of this special expedition may be known and reimbursed if desirable when completed; tail 'warm cloudy like rain' is a weather note", "9673/0", HT),
  [],
  n("G3", "Book test: label '9' on the operator's name; Pagan = Washington agrees with the dateline; 'Village Van Vliet Vincent Merlin' reads Major Van Vliet, Quartermaster, New York and the signature tail 'Aragon' = Quartermaster General agrees with 'M C Meigs' (all four H, key-no9.md p.[17]/p.[22]/p.[9]); No. 1 reads the same words as Heintzelman and Missouri and No. 2 as Rebel/Rifle Pits/Kelly (nonsense for a Meigs letter to Van Vliet). Time word not testable. Unread by the table: none (0 tokens). Not located in print (letters-only phrase grep in 170 cached volumes incl. OR I/32 pts 2-3, I/33, I/34 pts 2-3, I/35 pt 2, I/36 pt 1-2, I/37 pts 1-2: 0; OR ser. III vol. 4, the Meigs reports and ORN were not on disk: unchecked). CISOSEARCHALL 'special expedition reimbursed separate distinct account victualling': 9673 only.")),
 "G4": ("O9-DD", d(27, 9687, 21, "16 Mar 1864 Washington 11 AM (cipher time word Francis = 11 AM = the header's own time; label '( 9 )' after the operator), Jno. Horner N. Y. (operator), Meigs (signed MC Meigs, Quartermaster General) to Major Van Vleet, Quartermaster, New York: reserve accommodations on the Fulton for Miss Dix who expects to have authority from the Secretary of War to make an official visit to the Department of the South; reserve also three state rooms for officers of rank to be designated hereafter, and don't let the Fulton sail until further advised on this subject; report for orders when ready; tail 'Confidential'", "9687/1", HT),
  [],
  n("G4", "Book test: label '( 9 )'; time word Francis = 11 AM equals the header's 11 AM under No. 9 only (No. 1: 12, No. 2: 12.30 AM); 'Village Van Vleet Vincent Midas' = Major Van Vleet, Quartermaster, New York; 'Arabia' = Sec. of War; 'Aragon' = Quartermaster General (all H). The Miss Dix / Fulton content is independent of the book: Butler's letters to Miss Dix of 4 and 15 Apr 1864 (Private and Official Correspondence IV, cached) mention the Fulton, a different telegram; the telegram itself is not located in print (phrase grep as O9-DC: 0; 'Reserve accommodations Fulton Miss Dix State rooms': 9687 only). Unread by the table: none (0 tokens).")),
 "G5": ("O9-DE", d(24, 9684, 18, "10 Mar 1864 Washington 10.30 PM (cipher time word Susan = 10.30 PM = the header's own '1030 P. M.'; label '( 9 )'), John Horner N. Y. (operator), G. V. Fox (sig 'Atlas') to Colonel H. S. Olcott, New York: seize all the books and papers of H. D. Stover now prisoner in Fort La Fayette; no permits will be issued until we have held consultation; tail 'dam bore' unread", "9684/1", HT + "; leaf 9684 fetched, top half (O9-DH, O9-DI) read, this entry not"),
  ["graded: dam:M", "graded: bore:M"],
  n("G5", "Book test: label '( 9 )'; Pagoda = Washington; time word Susan = 10.30 PM equals the header's 1030 PM under No. 9 only (No. 1: 11.30 PM, No. 2: 11 PM); 'Venus ... Midas' = Colonel ... New York, 'Husband' = (Fort) La Fayette, 'Atlas' = G. V. Fox (all H). Same Atlas/Olcott pair as O9-DH, O9-DI (9 Mar), the day before. 'dam bore' after the signature word: 2 unread tokens graded M (filler as in 'easy' and 'Abbot' elsewhere). Not located in print (phrase grep 'H. D. Stover', 'Stover now prisoner': 0 in 170 cached volumes incl. OR ser. II vol. 7; Fox Confidential Correspondence: see NOTES; CISOSEARCHALL 'books papers Stover prisoner permits consultation': 0 hits).")),
 "G6": ("O9-DF", d(39, 9699, 33, "9 Apr 1864 Washington 12.30 PM (cipher time word Viola = 12.30 PM = the header's own time; label '( 9 )'; the entry runs onto pointer 9700, printed page 34), John Horner NY (operator), Meigs (signed M C Meigs) to Captain S. L. Brown, Quartermaster, New York: you have instructions as to the quantity of forage to be placed at [Muss, unread] and the time, do not fail; do not use steamers, very expensive, to a greater extent than absolutely necessary; to send steamers to [Maine] after hay would probably consume more time than to ship it instantly upon good [sailing vessels]; [Mud] [Harbor] has a deep entrance; probably one large propeller dispatched immediately from [New York] or Willow would insure the needed first instalment; you are in charge of the work, judge but be certain of success; ask advice if doubtful but state reasons of doubt; signed M C Meigs, Abbott", "9699/1", "holder transcription (pointers 9699 + 9700), leaf not eye-checked"),
  ["variant: Abbott=Abbot:M", "graded: Muss:M", "graded: Mud:M", "graded: Willow:M"],
  n("G6", "Book test: label '( 9 )'; Pagan = Washington; time word Viola = 12.30 PM equals the header's 12.30 PM under No. 9 (and No. 1 reads '12.30' without a meridian: a half-weight match; No. 2 '12 midnight PM'); 'Vulcan S L Brown Vinton Midas' = Captain S. L. Brown, Quartermaster, New York; the body reads under No. 9 only as sense ('steamers to [Maine] after hay', 'good [sailing vessels]', 'from [New York] or Willow'; No. 1 reads Dalton, Invest, Brannon, Fortify). The 'Abbott' tail is the key's Abbot (Quartermaster General), a spelling variant, M. Sibling the day before: 9699/0 (8 Apr 1864, 'Send forty thousand bushels of grain and seven hundred tons of hay to Mud ... report at Muss', same Horner, same Meigs to Brown, same unread 'Muss'): O9-BOOK left it 'undecided'; it reads as No. 9 on the same grounds ('For [Captain] S. L. Brown assistant [Quartermaster]'), but is not in this brief and is not filed here. Unread by the table: 'Muss', 'Mud', 'Willow' (3 place words, graded M). Bigram coherence does NOT favour No. 9 here (-7.103 against shuffled -7.087 and No. 1 -7.071): the gate would fail; the header time word and the sense decide. Not located in print (phrase grep 'quantity of forage to be placed', 'Do not use steamers very expensive': 0; ser. III vol. 4 not on disk).")),
 "G7": ("O9-DG", d(143, 9803, 137, "27 July 1864 Washington 9 PM (cipher time word Lucy = 9 PM = the header's own '9 P.M'; no label), Lt Kelly (operator), Halleck (signature not in the ledger) to Kelley, Cumberland: with your railroad facilities you should be able to concentrate nearly all your force on any threatened point; you will be expected to make your arrangements to accomplish this object; tail '1140 am' is a time note; printed OR I/37 pt 2 p.471", "9803/0", "header and first two lines read on a 2400 px crop"),
  ["variant: Vermin=Vermin:M"],
  n("G7", "Book test: time word Lucy = 9 PM equals both the header's 9 P.M and the printed 'Washington, July 27, 1864 - 9 p. m.' under No. 9 only (No. 1: 5 PM, No. 2: 5.30 PM). Printed OR I/37 pt 2 p.471 (IA warofrebellion372unit; Halleck to Brigadier-General Kelley, Cumberland, Md.): word for word; 'Soap' = railroad and 'Smoky' = point are key rows (H) and the print says railroad and point: both match with no cryptanalysis. Print-match instrument (o9r1_printmatch.out): No. 9 3/4 word tokens, No. 1 0/4, No. 2 0/3, shuffled No. 9 max 1 of 20 seeds, p95 1. DATA CONFLICT: 'Vermin' is 'Vernon/Vermin = Maj. Gen.' (key-no9.md, H) and the print addresses Brigadier-General Kelley (the leaf reads 'Vermin', crop checked); graded M here (variant). The same conflict shape as Village = Major in reading-no9.md. Unread by the table: none (0 tokens). The ledger text carries no signature group; the print signs H. W. Halleck.")),
 "G8": ("O9-DH", d(24, 9684, 18, "9 Mar 1864 Washington 11 AM (cipher time word Francis = 11 AM = the header's own '11 A.M'; no label on this header), John Horner (operator), G. V. Fox (sig 'Atlas') to Colonel Olcott, New York: is [E. L.] Brady connected with a Navy operation or [Army]? if the former this Department will arrest him, if the latter the War Department should take it up", "9684/0", "header and first lines read on a 2400 px crop"),
  [],
  n("G8", "Book test: time word Francis = 11 AM equals the header's 11 A.M under No. 9 only (No. 1: 12, No. 2: 12.30 AM); 'Venus ... Midas' = Colonel ... New York; 'Walnut' = Army, 'wadding' = arrest, 'Atlas' = G. V. Fox (H). The leaf carries a second telegram of the same day below it with its own header (O9-DI): the volunteer segmenter had folded the two, split here from the crop. Unread by the table: none (0 tokens). Not located in print (phrase grep 'Is Brady connected with a Navy operation', 'Edwin L. Brady': 0 in 170 cached volumes incl. OR ser. II vol. 7; CISOSEARCHALL 'Brady connected Navy operation War Dept should take it up': 9684 only).")),
 "G9": ("O9-DI", d(24, 9684, 18, "9 Mar 1864 Washington (cipher time word Sarah = 9.30 PM; the ledger header 'Wash. D. C. / John Horner N. Y. \"No 9\" / mar. 9th 1864' has no time), John Horner N. Y. (operator, label 'No 9' written over the header), Fox (sig 'Atlas') to Colonel Olcott, New York: arrest Edwin L. Brady and place him in Fort La Fayette; call upon [Jno. A. Dix] for assistance", "9684/0 (second telegram)", "header and first lines read on a 2400 px crop"),
  [],
  n("G9", "Book test: label 'No 9' on the header (the clerk's insertion, read on the crop); 'Vesper Olcott' = Colonel Olcott; time word Sarah = 9.30 PM, not testable (no header time) but a night time after the 11 AM question of O9-DH is the natural order; 'husband' = (Fort) La Fayette, 'Agate' = Jno. A. Dix, 'Atlas' = G. V. Fox (H). Unread by the table: none (0 tokens). The orders are in line with O9-DE (10 Mar, Stover). Not located in print (as O9-DH).")),
 "G10": ("O9-DJ", d(75, 9735, 69, "9 May 1864 Washington (cipher time word Hannah = 2 PM; the ledger header has no time), Rowe, Cumberland (operator, label '9'), Halleck (sig 'Abortion') to Brig. Gen. Kelley ('Vermont'), Cumberland ('Jargon'): you remain under General Sigel's ('Belgiums') orders; report directly when you have any important information to convey; three regiments of Ohio militia were ordered to Parkersburg, three to New Creek ('Knew Creek'), two [print: three] to Cumberland ('Jaundice') and three to Harper's Ferry ('Harp fairy'); you can distribute them as you deem best; printed OR I/37 pt 1 p.414", "9735/0", "header and first two lines read on a 2400 px crop"),
  ["variant: Hannah=Hannah:M", "graded: Jargon:M", "graded: Belgiums:M", "graded: Jaundice:M", "graded: Harp:M"],
  n("G10", "Book test: label '9' after 'Rowe Cumberland' (read on the crop); Pagan = Washington; 'Vermont' = Brig. Gen. (the print addresses Brigadier-General Kelley: agrees, unlike O9-DG's 'Vermin'), 'shylock' = regiment(s), 'Castor' = Ohio, 'Abortion' = Halleck (H). Printed OR I/37 pt 1 p.414 (IA warofrebellion371unit, Washington, D. C., May 9, 1864 - 10.05 a. m., Halleck to Brigadier-General Kelley, Cumberland): word for word apart from ledger 'two' for the print's 'three' (to Cumberland). Print-match instrument: No. 9 4/5 word tokens, No. 1 0/9, No. 2 0/9, shuffled No. 9 max 1 of 20 seeds. TIME-WORD CONFLICT: Hannah = 2 PM against the printed 10.05 a.m. (the header has no time); graded M (variant); no book in hand gives a morning time here (No. 1 1.30 PM, No. 2 1 PM). Unread by the table: 'Jargon' (= Cumberland by the print's address line, C, not tabled), 'Belgiums' (= Sigel's, C), 'Jaundice' (= Cumberland, C), 'Harp' (+ 'fairy' = Harper's Ferry, C): 4 groups graded M. Bigram coherence No. 9 -7.255 against No. 2 -6.594: coherence prefers No. 2 here, the instrument's known weakness on a mostly plain text with decoded names; the print match and the header words decide.")),
 "G11": ("O9-DK", d(26, 9686, 20, "14 Mar 1864 Washington (cipher time word Clara = 10.30 AM; the printed time is 10.30 p.m.; the ledger header has none), R. C. Clowry at Little Rock (operator, label '(9)'), Halleck (sig 'Abortion') to Maj. Gen. Frederick Steele ('Vernon Frd'k Steele'), Little Rock: you command [ledger 'come and'] all troops found within the limits of your Department when the order establishing it was received; you will arrest any officer within your Department who interferes with your authority in this respect; tail 'easy' unread; printed OR I/34 pt 2 p.602", "9686/1", "header and first lines read on a 2400 px crop"),
  ["variant: Clara=Clara:M", "graded: easy:M"],
  n("G11", "Book test: label '(9)' (read on the crop); Pagan = Washington; 'Vernon' = Maj. Gen. (print: Major-General Steele, agrees), 'youth' = troops, 'waggish' = arrest, 'Abortion' = Halleck (H). Printed OR I/34 pt 2 (IA warofrebellion013402rootrich; 'Washington, D. C., March 14, 1864 - 10.30 p. m., Major-General Steele, Little Rock, Ark.', Halleck as General-in-Chief, the item ends on p.602 before the head of p.603): word for word apart from 'come and' / 'command'. Print-match instrument: No. 9 5/5 word tokens, No. 1 0/4, No. 2 0/6, shuffled No. 9 max 2 of 20 seeds, p95 1. TIME-WORD CONFLICT: Clara = 10.30 AM in key-no9.md against the printed 10.30 p.m.: the hour agrees to the half hour, the meridian does not (Susan = 10.30 PM, O9-DE); graded M (variant); No. 1/No. 2 read Clara as 5.30 AM. Bigram coherence puts No. 9 first (-6.373 against shuffled No. 9 -6.413 and No. 2 -6.992): beats No. 1/2 and, by 0.04, the shuffled No. 9 control (not a margin). Unread by the table: 'easy' (tail filler, 1 token, M).")),
}
blocks = {}; cur = None
for ln in (HERE/"ms18"/"o9r1_entries.txt").read_text(encoding="utf-8").splitlines():
    m = re.match(r"### (G\d+) \|", ln)
    if m: cur = m.group(1); blocks[cur] = []; continue
    if cur and ln.strip(): blocks[cur].append(ln)
p = HERE/"ciphertext-no9.txt"; txt = p.read_text(encoding="utf-8")
add = [f"### {nid} | {desc}\n" + "\n".join(blocks[k] + extra + notes) + "\n" for k, (nid, desc, extra, notes) in MAP.items() if f"### {nid} |" not in txt]
if add and "--dry" not in sys.argv: p.write_text(txt.rstrip("\n") + "\n\n" + "\n".join(add), encoding="utf-8")
print(("would add " if "--dry" in sys.argv else "added ") + str(len(add)))
