#!/usr/bin/env python3
"""H299 (runner 10 session_0148wt8Aokh6aZEdJsXzYiZX, 29 Sept 2026): join H297's blind read of sheet B's L05 (h297_reply.tsv) to read_call_A's 18 L05 signs
from the TRUE line start. Rule: a word item read as the bare letter 'h' standing between two sign items is taken as the CH sign (as H257 took the bare
'a' as CA); the bare 'a' immediately before the first sign is H63's uncoded edge CA (pos 0, class CA_edge); dot/punctuation items dropped. Joined in
order iff the sign count then equals 18. Writes f61_positions_L05B.tsv (line, pos, class, segment, x_reply, prev, next, desc; x at the reader's
scale, sheet B, whole line) and appends the L05 row to f61_sheet_edges.tsv's positioned-edge list is NOT done here (that file is regenerated by its
own script). Result f61positions_L05B_join_result.txt.  [--check]"""
import csv, os, sys, unicodedata
HERE = os.path.dirname(os.path.abspath(__file__))
def norm(s): return "".join(c for c in unicodedata.normalize("NFD", s) if unicodedata.category(c) != "Mn").lower().strip()
def main():
    rows = [l.rstrip("\n").split("\t") for l in open(f"{HERE}/h297_reply.tsv") if l[0] == "L"]
    items = [r for r in rows if not (r[3] == "sign" and ("dot" in r[4].lower() or "punctuation" in r[4].lower()))]
    kinds = [r[3] for r in items]
    for k, r in enumerate(items):
        if r[3] == "word" and norm(r[4]) == "h" and 0 < k < len(items) - 1 and items[k - 1][3] == "sign" and items[k + 1][3] == "sign": kinds[k] = "sign_h"
    first = next(k for k, kd in enumerate(kinds) if kd != "word")
    edge_a = first > 0 and items[first - 1][3] == "word" and norm(items[first - 1][4]) == "a"
    A = [r for r in csv.DictReader(open(f"{HERE}/read_call_A.tsv"), delimiter="\t") if r["line"] == "L05"]
    dec = {int(r["pos"]): r["class"] for r in csv.DictReader(open(f"{HERE}/../family/f61_decode_period_v4_frac0.1_sbs.tsv"), delimiter="\t") if r["line"] == "L05"}
    signs = [k for k, kd in enumerate(kinds) if kd != "word"]
    rep = [f"signs after taking the bare 'h' as CH: {len(signs)} vs read_call_A {len(A)}; edge a before the run: {'yes' if edge_a else 'no'}"]
    out = ["line\tpos\tclass\tsegment\tx_reply\tprev\tnext\tdesc"]
    if len(signs) == len(A):
        rep.append("joined from the true line start")
        if edge_a: r = items[first - 1]; out.append(f"L05\t0\tCA_edge\t{r[1]}\t{r[2]}\tword\tsign\t{r[4]} (H63's uncoded edge a)")
        for p, k in enumerate(signs, 1):
            prev = "edge" if k == 0 else ("word" if kinds[k - 1] == "word" else "sign"); nxt = "edge" if k == len(items) - 1 else ("word" if kinds[k + 1] == "word" else "sign")
            out.append(f"L05\t{p}\t{dec.get(p, '?')}\t{items[k][1]}\t{items[k][2]}\t{prev}\t{nxt}\t{items[k][4]}")
        rep.append("classes in order: " + " ".join(dec.get(p, "?") for p in range(1, len(A) + 1)))
    else: rep.append("not joined")
    open(f"{HERE}/f61_positions_L05B.tsv", "w").write("\n".join(out) + "\n"); txt = "\n".join(rep) + "\n"; p = f"{HERE}/f61positions_L05B_join_result.txt"
    if "--check" in sys.argv:
        ok = os.path.exists(p) and open(p).read() == txt; print("check", "OK" if ok else "STALE"); sys.exit(0 if ok else 1)
    open(p, "w").write(txt); print(txt, end=""); print("\n".join(out[:5]))
if __name__ == "__main__": main()
