#!/usr/bin/env python3
"""F61-SKELETON (campaign step H58, 28 Sept 2026, runner session_01J8hunWPcE7QYcpCx59CUHV): the f.61r skeleton under the
corrected cells, one file for the verifier and for the person-reading rows (ASKS 88, CAMPAIGN.md H50/H53). NOT a reading:
no letter is chosen within any pair; the five known spans carry Tomokiyo's own markup letters (his tentative reading,
grade M as a reading, the reference of every control here) and nothing else on the leaf carries a letter.

Sources, all on disk: scripts/passA_classes.tsv (the six span lines, VBAR split) and passU2_classes.tsv (L02, L04, L10),
relabelled by H26's blind groups and H22's (scripts/f61qo2.relabel: SBS, EBR_A/EBR_B/ISH); cells from
scripts/f61joint_h51_map.tsv (the joint fit on f.61 + f.108r, H51; a cell is used when the map gives one on 2+ signs of
both leaves) -- grade M (fitted on Tomokiyo's markup and the reprinted period gloss); ZHOOK i/x also published (H44,
family/key_published_rare.tsv); the classes his markup leaves as dashes at every f.61 position (CA, LOOPBAR, LL, CROSS,
ELOOP, HASH4, LOOPSTEM1, CH, C6: class_diag.tsv, H44) are nulls '-'; OTHER and any class with no cell is '?'. Tomokiyo's
letters are placed on the span lines by the F61-CAL DP with the H51 map (scripts/f61crib.align), as every control did.
  python3 scripts/f61skeleton.py [--check]   -> scripts/f61_skeleton.txt
  python3 scripts/f61skeleton.py --leaf f108v [--check]   (H62, 28 Sept 2026) -> scripts/f108v_skeleton.txt: the same cells on
      family/passes/f108v3z_draft_reconciled.tsv (H59, grade M transcription of fr.3983 f.108v's seven top rows, same hand as
      f.61); no Tomokiyo letters exist for this leaf, so every covered sign is a pair and the draft's own grade is counted.
"""
import csv, os, sys
from collections import Counter
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
from f61crib import align, load_read, load_spans
from f61crib4 import split_lines
import f61qo2
NULLS = {"CA", "LOOPBAR", "LL", "CROSS", "ELOOP", "HASH4", "LOOPSTEM1", "CH", "C6"}   # C6 and LOOPBAR: the joint map's a/n on them (2 counts each) is the DP placing a neighbour's letter on an uncovered class; his markup dashes them at every position (class_diag.tsv, H44) and fragment_L10.tsv already treats C6 as a null
LEAF = sys.argv[sys.argv.index("--leaf") + 1] if "--leaf" in sys.argv else "f61"
def main_108v(cells):
    rows = [r for r in csv.DictReader((l for l in open(f"{HERE}/../family/passes/f108v3z_draft_reconciled.tsv") if not l.startswith("#")), delimiter="\t")]
    out = ["# fr.3983 f.108v skeleton under the corrected cells -- campaign H62, 28 Sept 2026, regenerated by scripts/f61skeleton.py --leaf f108v (NOT a reading: no letter chosen within any pair).",
           "# Signs: family/passes/f108v3z_draft_reconciled.tsv (H59: two blind passes reconciled by one call; sign grade H = both passes confident, M = settled or agreed at low confidence, L = still flagged). Cells: the H51 joint fit (grade M), SBS b/o (H26), ZHOOK i/x (published, H44); - = a null class (Tomokiyo's dashes on f.61, H44); ? = no cell (OTHER, ISH-like shapes the map does not fit).",
           "# cells used: " + " ".join(f"{c}={v}" for c, v in sorted(cells.items()))]
    stats = Counter(); grades = Counter(r["grade"] for r in rows); per = []
    for line in [f"L0{i}" for i in range(1, 8)]:
        seq = [r["sign"] for r in rows if r["line"] == line]; toks = []
        for c in seq:
            if c in NULLS: toks.append("-"); stats["null"] += 1
            elif c in cells: toks.append(f"[{cells[c]}]"); stats["pair"] += 1
            else: toks.append("?"); stats["?"] += 1
        per.append(f"{line} ({len(seq)} signs): " + " ".join(toks)); per.append(f"{line} classes: " + " ".join(seq))
    out.append(f"# counts: {stats['pair']} pair positions (no letter chosen), {stats['null']} nulls, {stats['?']} unread; signs {sum(stats.values())}; sign grades H {grades['H']} M {grades['M']} L {grades['L']}; coverage (pair+null)/signs {(stats['pair']+stats['null'])/max(1,sum(stats.values())):.2f}")
    out += per
    txt = "\n".join(out) + "\n"; res = f"{HERE}/f108v_skeleton.txt"
    if "--check" in sys.argv:
        ok = os.path.exists(res) and open(res).read() == txt; print("fresh" if ok else "STALE"); sys.exit(0 if ok else 1)
    open(res, "w").write(txt); print(txt, end="")
def main():
    lines = split_lines(load_read())
    for r in csv.DictReader((l for l in open(f"{HERE}/passU2_classes.tsv") if not l.startswith("#")), delimiter="\t"):
        lines.setdefault(r["line"], []).append(r["sign"])
    f61qo2.relabel(lines)
    cells = {}
    for r in csv.DictReader((l for l in open(f"{HERE}/f61joint_h51_map.tsv") if not l.startswith("#")), delimiter="\t"):
        if r["cell"] != "null" and int(r["n_signs_both_leaves"]) >= 2 and not r["tie"]: cells[r["class"]] = r["cell"]
    key = {c: tuple(v.split("/")) for c, v in cells.items()}
    if LEAF == "f108v": return main_108v(cells)
    tomo = {}
    for s, line, markup in load_spans():
        _, pairs = align(markup, lines[line], key)
        for mi, sj in pairs:
            if markup[mi] != "-": tomo[(line, sj)] = markup[mi]
    out = ["# f.61r skeleton under the corrected cells -- campaign H58, 28 Sept 2026, regenerated by scripts/f61skeleton.py (NOT a reading: no letter chosen within any pair).",
           "# Token forms: T:x = Tomokiyo's own markup letter on one of his five spans (his tentative reading, the reference of every control; grade M as a reading); [x/y] = the cell of the sign's class, grade M (H51 joint fit; SBS b/o from H26's blind sort; ZHOOK i/x also published, H44); - = a null (a class under his dashes at every f.61 position, H44); ? = no cell (OTHER, or a class the map does not fit).",
           "# cells used: " + " ".join(f"{c}={v}" for c, v in sorted(cells.items())),
           "# lines: pass A (span lines L01 L03 L05 L07 L08 L11, VBAR split) and pass U2 (L02 L04 L10); L06 and L09 carry no cipher; classes relabelled by H26 (SBS) and H22 (EBR_A/EBR_B/ISH)."]
    stats = Counter(); per = []
    for line in ["L01", "L02", "L03", "L04", "L05", "L07", "L08", "L10", "L11"]:
        seq = lines.get(line, []); toks = []
        for j, c in enumerate(seq):
            if (line, j) in tomo: toks.append(f"T:{tomo[(line, j)]}"); stats["T"] += 1
            elif c in NULLS: toks.append("-"); stats["null"] += 1
            elif c in cells: toks.append(f"[{cells[c]}]"); stats["pair"] += 1
            else: toks.append("?"); stats["?"] += 1
        per.append(f"{line} ({len(seq)} signs): " + " ".join(toks))
        per.append(f"{line} classes: " + " ".join(seq))
    out.append(f"# counts: {stats['T']} Tomokiyo letters, {stats['pair']} pair positions (no letter chosen), {stats['null']} nulls, {stats['?']} unread; signs {sum(stats.values())}")
    out += per
    txt = "\n".join(out) + "\n"; res = f"{HERE}/f61_skeleton.txt"
    if "--check" in sys.argv:
        ok = os.path.exists(res) and open(res).read() == txt; print("fresh" if ok else "STALE"); sys.exit(0 if ok else 1)
    open(res, "w").write(txt); print(txt, end="")
if __name__ == "__main__":
    main()
