#!/usr/bin/env python3
"""H178b (runner 6, 28 Sept 2026): tiles for the blind link test between f.176r's i-sign (the columns f.176r pass A reads ZHOOK
and pass B reads C43, H178) and f.61r's own ZHOOK (3) and C43 (6) signs. f.61 tiles located by the runner's eye on
images/f61sheet_L05/L07/L11.jpg (segment, x in sheet px, listed below); f.176r tiles = the first 10 such columns in row order
(pass A's segment and x_px on the native crops, regenerated by family/sheets/f176r_full/README.md into the scratch dir given as
argv[1]). Every tile scaled to height 180, shuffled (seed 178), laid out 5 per row with a number; key -> scripts/h178b_key.tsv
(never shown to the reader).  python3 h178b_tiles.py CROPDIR"""
import csv, difflib, random, sys
from PIL import Image, ImageDraw, ImageOps
HERE = "ciphers/fr4715-f61-mayenne-1592"
F61 = [("ZHOOK", "L07", 2, 1430), ("ZHOOK", "L07", 3, 2080), ("ZHOOK", "L11", 2, 1500),
       ("C43", "L05", 1, 2310), ("C43", "L05", 2, 500), ("C43", "L05", 2, 1190), ("C43", "L05", 2, 1700),
       ("C43", "L11", 1, 1565), ("C43", "L07", 2, 1795)]
NSEG = {"L05": 3, "L07": 3, "L11": 2}
def rd(p): return [r for r in csv.DictReader((l for l in open(p) if not l.startswith("#")), delimiter="\t")]
def f61_tile(line, seg, x):
    im = Image.open(f"{HERE}/images/f61sheet_{line}.jpg").convert("L"); h = im.size[1] / NSEG[line]
    return im.crop((x - 150, int((seg - 1) * h) + 10, x + 150, int(seg * h) - 6))
def f176_tiles(cropdir, n=10):
    out = []
    for fa, fb in (("f176r_signsA_h170.tsv", "f176r_signsB_h170.tsv"), ("f176r_signsA_L05-L12.tsv", "f176r_signsB_L05-L12.tsv")):
        A, B = rd(f"{HERE}/family/passes/{fa}"), rd(f"{HERE}/family/passes/{fb}")
        for line in sorted(set(r["line"] for r in A)):
            a = [r for r in A if r["line"] == line and r["sign"] != "PLAIN"]; b = [r for r in B if r["line"] == line and r["sign"] != "PLAIN"]
            sm = difflib.SequenceMatcher(None, [r["sign"] for r in a], [r["sign"] for r in b], autojunk=False)
            for op, i1, i2, j1, j2 in sm.get_opcodes():
                if op == "replace" and i2 - i1 == j2 - j1:
                    for ra, rb in zip(a[i1:i2], b[j1:j2]):
                        if ra["sign"] == "ZHOOK" and rb["sign"] == "C43": out.append((line, ra["segment"], float(ra["x_px"])))
    pick = out[:: max(1, len(out) // n)][:n]; tiles = []
    for line, seg, x in pick:
        im = Image.open(f"{cropdir}/f176_{line}_{seg}.jpg").convert("L")
        tiles.append((("f176", line, seg, x), im.crop((int(x) - 62, 0, int(x) + 62, im.size[1]))))
    return tiles, len(out)
def main():
    t176, total = f176_tiles(sys.argv[1])
    tiles = [(("f61",) + k[1:] + (k[0],), f61_tile(*k[1:])) for k in F61] + [(k + ("?",), im) for k, im in t176]
    random.Random(178).shuffle(tiles); W = 5; cell = (300, 220)
    sheet = Image.new("L", (W * cell[0], ((len(tiles) + W - 1) // W) * cell[1]), 255); d = ImageDraw.Draw(sheet); key = []
    for n, (k, im) in enumerate(tiles, 1):
        im = ImageOps.autocontrast(im.resize((int(im.size[0] * 180 / im.size[1]), 180)), cutoff=2); im.thumbnail((cell[0] - 10, 180))
        X, Y = ((n - 1) % W) * cell[0], ((n - 1) // W) * cell[1]; sheet.paste(im, (X + 5, Y + 30)); d.text((X + 8, Y + 6), f"tile {n}", fill=0)
        key.append((n,) + tuple(k))
    sheet.save(f"{HERE}/images/h178b/tiles.jpg", quality=90)
    with open(f"{HERE}/scripts/h178b_key.tsv", "w") as f:
        f.write(f"# H178b key (not shown to the reader); f.176r C43/ZHOOK-disputed columns in L01-L12: {total}\ntile\tleaf\tline\tsegment\tx\tclass\n")
        for r in key: f.write("\t".join(map(str, r)) + "\n")
    print(len(tiles), "tiles;", total, "disputed columns on f.176r")
if __name__ == "__main__": main()
