#!/usr/bin/env python3
"""Build the annealer inputs for Dupuy 468 f.28 (step 4). Written 23 Sept 2026.

target_anneal.txt  the reconciled ciphertext in tools/nomenclator_anneal.py format: letter-sign tokens as
                   they are, clear words as {word}, word signs (K F O PW SX HHH Y~ ß) and ?BLOT as a run break
                   '{-}' (the letter-key search does not try to read word signs).
control_plain.txt  control_source.txt (Erasmus, Epistolae selectae, Latin Library via
                   github.com/cltk/latin_text_latin_library, held out of the model corpus) normalised with
                   italian_ngram.norm, '#' at word boundaries.
design.json        the control key design matched to the target: 21 letters one sign each, r with a rare
                   second sign (R/R2), two null signs at the target's rate (g+o = 16 of 671 letter-run tokens).
reveal.txt         the fraction of target letter-run tokens that stand under an aligned gloss (key_from_gloss.tsv).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "..", "tools"))
import italian_ngram as ing  # noqa: E402

BREAK = {"K", "F", "O", "PW", "SX", "HHH", "Y~", "ß", "?BLOT"}


def main():
    lines, ntok = [], 0
    for l in open(os.path.join(HERE, "..", "ciphertext.txt"), encoding="utf-8"):
        if l.startswith("#") or not l.strip():
            continue
        f = l.rstrip("\n").split("\t")
        out = []
        for t in f[1].split():
            if t.startswith("[PLAIN:"):
                out.append("{" + t[7:-1] + "}")
            elif t in BREAK:
                out.append("{-}")
            else:
                out.append(t)
                ntok += 1
        lines.append(f"# {f[0]}\n" + " ".join(out))
    open(os.path.join(HERE, "target_anneal.txt"), "w").write(
        "# Dupuy 468 f.28r-v, generated by make_inputs.py from ciphertext.txt\n" + "\n".join(lines) + "\n")
    votes = [l.split("\t") for l in open(os.path.join(HERE, "..", "key_from_gloss.tsv"), encoding="utf-8")
             if not l.startswith("#") and not l.startswith("line\t") and l.strip()]
    glossed = {(v[0], v[1]) for v in votes if v[2] not in BREAK and not v[3].startswith("=")}
    frac = len(glossed) / ntok
    open(os.path.join(HERE, "reveal.txt"), "w").write(f"{frac:.4f}\n")
    plain = ing.norm(open(os.path.join(HERE, "control_source.txt"), encoding="utf-8").read()).strip("#")
    open(os.path.join(HERE, "control_plain.txt"), "w").write(plain + "\n")
    nnull = sum(1 for l in lines for t in l.split() if t in ("g", "o"))
    design = {"_note": "Matched control for Dupuy 468 f.28 (23 Sept 2026): simple substitution, one sign per "
                       "letter, a rare second r sign, two nulls at the target's rate, no syllable or word signs "
                       "(the target's word signs are run breaks in both).",
              "letters": ing.ALPHA, "homophones": {"r": 2}, "homo_weights": {"2": [0.95, 0.05]},
              "syllables": 0, "words": 0, "nulls": 2, "null_rate": round(nnull / ntok, 4)}
    json.dump(design, open(os.path.join(HERE, "design.json"), "w"), indent=1)
    print(f"target letter-run tokens {ntok}, glossed {len(glossed)} ({frac:.1%}), nulls g+o {nnull}")


if __name__ == "__main__":
    main()
