#!/usr/bin/env python3
"""Regenerate reading.txt and reading_tokens.tsv from ciphertext.txt + key.tsv (+ exceptions.tsv if present).
  python3 decode.py          write the reading
  python3 decode.py --check  exit 1 if the committed reading differs from what the inputs give (rule 7)
ciphertext.txt: '<folio> <line> | tok tok ...'; a token is a sign code, '.', '[?]', or code+'?' (uncertain sign).
key.tsv: code, value, grade, source. Value '' or '?' = unknown; 'NULL' = null; a multi-letter value is a word sign.
exceptions.tsv (optional): folio, line, index, value, grade, reason -- a per-position reading that overrides the key.
f.30r-v (item 22): ciphertext_f30.tsv (line, position, sign, confidence; built by build_ciphertext_f30.py) with the
same key gives reading_f30.txt and reading_f30_tokens.tsv. Confidence 'l' counts as an uncertain sign (grade M at
most); '.' is a dot, '[?]' an illegible sign. --check covers both leaves and exits 1 if either is stale.
Every run also writes reading_f30_extended.txt / reading_f30_extended_tokens.tsv, the f.30 reading with the grade S
values of key_extension_f30.tsv added for signs key.tsv does not value (key.tsv untouched); --check covers them too.
  python3 decode.py --extended   also print the extended f.30 reading"""
import sys, os, collections
H = os.path.dirname(os.path.abspath(__file__))
def rows(fn):
    for l in open(os.path.join(H, fn), encoding='utf-8'):
        if l.strip() and not l.startswith('#'): yield l.rstrip('\n').split('\t')
key = {}
for r in rows('key.tsv'):
    if r[0] == 'code': continue
    key[r[0]] = (r[1], r[2])
exc = {}
if os.path.exists(os.path.join(H, 'exceptions.tsv')):
    for r in rows('exceptions.tsv'):
        if r[0] != 'folio': exc[(r[0], r[1], int(r[2]))] = (r[3], r[4])
out, tok, cnt = [], ['folio\tline\tindex\tsign\tvalue\tgrade'], collections.Counter()
for l in open(os.path.join(H, 'ciphertext.txt'), encoding='utf-8'):
    if not l.strip() or l.startswith('#'): continue
    head, body = l.split('|', 1); fo, ln = head.split()
    txt = []
    for i, t in enumerate(body.split()):
        if t == '.': continue
        unsure = t.endswith('?') and t != '[?]'; c = t.rstrip('?')
        if (fo, ln, i) in exc: v, g = exc[(fo, ln, i)]
        elif c in key and key[c][0] not in ('', '?'): v, g = key[c]
        else: v, g = '?', 'U'
        if unsure and g in 'HCS': g = 'M'   # an uncertain sign cannot carry a firm grade
        cnt[g] += 1; tok.append(f'{fo}\t{ln}\t{i}\t{t}\t{v}\t{g}')
        txt.append('' if v == 'NULL' else '·' if v == '?' else f'[{v}]' if len(v) > 1 else v)
    out.append(f'{fo} {ln} | ' + ''.join(txt))
total = sum(cnt.values())
summary = f'# tokens {total}: ' + ', '.join(f'{g} {cnt[g]}' for g in 'HCSMIU') + ' (U = sign not covered by the key)'
text = '# Generated by decode.py from ciphertext.txt + key.tsv; do not edit.\n' + summary + '\n' + '\n'.join(out) + '\n'
tsv = '\n'.join(tok) + '\n'
# f.30r-v (item 22)
out30, tok30, cnt30, cur = [], ['folio\tline\tposition\tsign\tconfidence\tvalue\tgrade'], collections.Counter(), None
for r in rows('ciphertext_f30.tsv'):
    if r[0] == 'line': continue
    ln, pos, c, conf = r[0], int(r[1]), r[2], r[3]; fo, l = ln.split('_')
    if ln != cur: out30.append([ln, []]); cur = ln
    if c == '.': continue
    if (fo, l, pos) in exc: v, g = exc[(fo, l, pos)]
    elif c in key and key[c][0] not in ('', '?'): v, g = key[c]
    else: v, g = '?', 'U'
    if conf == 'l' and g in 'HCS': g = 'M'
    cnt30[g] += 1; tok30.append(f'{fo}\t{l}\t{pos}\t{c}\t{conf}\t{v}\t{g}')
    out30[-1][1].append('' if v == 'NULL' else '·' if v == '?' else f'[{v}]' if len(v) > 1 else v)
tot30 = sum(cnt30.values())
sum30 = f'# tokens {tot30}: ' + ', '.join(f'{g} {cnt30[g]}' for g in 'HCSMIU') + ' (U = sign not covered by the key)'
text30 = ('# Generated by decode.py from ciphertext_f30.tsv + key.tsv; do not edit. f.30r-v, item 22.\n' + sum30 + '\n'
          + '\n'.join(f'{a.replace("_", " ")} | ' + ''.join(b) for a, b in out30) + '\n')
tsv30 = '\n'.join(tok30) + '\n'
# --extended: the same f.30 reading with key_extension_f30.tsv (grade S values proposed by infer_unkeyed.py with a
# matched control) filling only codes key.tsv leaves unvalued. key.tsv is never changed by it.
ext = {r[0]: (r[1], r[2]) for r in rows('key_extension_f30.tsv') if r[0] != 'code'} \
    if os.path.exists(os.path.join(H, 'key_extension_f30.tsv')) else {}
outx, tokx, cntx, cur = [], ['folio\tline\tposition\tsign\tconfidence\tvalue\tgrade'], collections.Counter(), None
for r in rows('ciphertext_f30.tsv'):
    if r[0] == 'line': continue
    ln, pos, c, conf = r[0], int(r[1]), r[2], r[3]; fo, l = ln.split('_')
    if ln != cur: outx.append([ln, []]); cur = ln
    if c == '.': continue
    if (fo, l, pos) in exc: v, g = exc[(fo, l, pos)]
    elif c in key and key[c][0] not in ('', '?'): v, g = key[c]
    elif c in ext: v, g = ext[c]
    else: v, g = '?', 'U'
    if conf == 'l' and g in 'HCS': g = 'M'
    cntx[g] += 1; tokx.append(f'{fo}\t{l}\t{pos}\t{c}\t{conf}\t{v}\t{g}')
    outx[-1][1].append('' if v == 'NULL' else '·' if v == '?' else f'[{v}]' if len(v) > 1 else v.lower() if g == 'S' else v)
sumx = f'# tokens {sum(cntx.values())}: ' + ', '.join(f'{g} {cntx[g]}' for g in 'HCSMIU') + ' (U = sign in neither key file)'
textx = ('# Generated by decode.py from ciphertext_f30.tsv + key.tsv + key_extension_f30.tsv; do not edit. f.30r-v.\n'
         '# Lower case = value from key_extension_f30.tsv (grade S, cryptanalytic with a control); upper case as in\n'
         '# reading_f30.txt. An S value on a doubtful (l) sign is graded M but still shown in lower case.\n' + sumx + '\n'
         + '\n'.join(f'{a.replace("_", " ")} | ' + ''.join(b) for a, b in outx) + '\n')
tsvx = '\n'.join(tokx) + '\n'
files = (('reading.txt', text), ('reading_tokens.tsv', tsv), ('reading_f30.txt', text30), ('reading_f30_tokens.tsv', tsv30),
         ('reading_f30_extended.txt', textx), ('reading_f30_extended_tokens.tsv', tsvx))
if '--check' in sys.argv:
    ok = all(os.path.exists(os.path.join(H, f)) and open(os.path.join(H, f), encoding='utf-8').read() == s for f, s in files)
    print('reading up to date' if ok else 'STALE: run python3 decode.py'); print(summary); print('f30', sum30); print('f30 extended', sumx); sys.exit(0 if ok else 1)
for f, s in files: open(os.path.join(H, f), 'w', encoding='utf-8').write(s)
print(summary); print('f30', sum30)
if '--extended' in sys.argv: print('f30 extended', sumx); print(textx)
