#!/usr/bin/env python3
"""Regenerate reading.txt and reading_tokens.tsv from ciphertext.txt + key.tsv (+ exceptions.tsv if present).
  python3 decode.py          write the reading
  python3 decode.py --check  exit 1 if the committed reading differs from what the inputs give (rule 7)
ciphertext.txt: '<folio> <line> | tok tok ...'; a token is a sign code, '.', '[?]', or code+'?' (uncertain sign).
key.tsv: code, value, grade, source. Value '' or '?' = unknown; 'NULL' = null; a multi-letter value is a word sign.
exceptions.tsv (optional): folio, line, index, value, grade, reason -- a per-position reading that overrides the key."""
import sys, os, collections
H = os.path.dirname(os.path.abspath(__file__))
def rows(fn):
    for l in open(os.path.join(H, fn), encoding='utf-8'):
        if l.strip() and not l.startswith('#'): yield l.rstrip('\n').split('\t')
key = {}
for r in rows('key.tsv'):
    if r[0] == 'code': continue
    key[r[0]] = (r[1], r[2])
exc = {}
if os.path.exists(os.path.join(H, 'exceptions.tsv')):
    for r in rows('exceptions.tsv'):
        if r[0] != 'folio': exc[(r[0], r[1], int(r[2]))] = (r[3], r[4])
out, tok, cnt = [], ['folio\tline\tindex\tsign\tvalue\tgrade'], collections.Counter()
for l in open(os.path.join(H, 'ciphertext.txt'), encoding='utf-8'):
    if not l.strip() or l.startswith('#'): continue
    head, body = l.split('|', 1); fo, ln = head.split()
    txt = []
    for i, t in enumerate(body.split()):
        if t == '.': continue
        unsure = t.endswith('?') and t != '[?]'; c = t.rstrip('?')
        if (fo, ln, i) in exc: v, g = exc[(fo, ln, i)]
        elif c in key and key[c][0] not in ('', '?'): v, g = key[c]
        else: v, g = '?', 'U'
        if unsure and g in 'HCS': g = 'M'   # an uncertain sign cannot carry a firm grade
        cnt[g] += 1; tok.append(f'{fo}\t{ln}\t{i}\t{t}\t{v}\t{g}')
        txt.append('' if v == 'NULL' else '·' if v == '?' else f'[{v}]' if len(v) > 1 else v)
    out.append(f'{fo} {ln} | ' + ''.join(txt))
total = sum(cnt.values())
summary = f'# tokens {total}: ' + ', '.join(f'{g} {cnt[g]}' for g in 'HCSMIU') + ' (U = sign not covered by the key)'
text = '# Generated by decode.py from ciphertext.txt + key.tsv; do not edit.\n' + summary + '\n' + '\n'.join(out) + '\n'
tsv = '\n'.join(tok) + '\n'
if '--check' in sys.argv:
    ok = all(os.path.exists(os.path.join(H, f)) and open(os.path.join(H, f), encoding='utf-8').read() == s
             for f, s in (('reading.txt', text), ('reading_tokens.tsv', tsv)))
    print('reading up to date' if ok else 'STALE: run python3 decode.py'); print(summary); sys.exit(0 if ok else 1)
open(os.path.join(H, 'reading.txt'), 'w', encoding='utf-8').write(text)
open(os.path.join(H, 'reading_tokens.tsv'), 'w', encoding='utf-8').write(tsv)
print(summary)
