#!/usr/bin/env python3
"""FM65-E: file eleven of the fifteen rows of fm65e_entries.txt into ../ciphertext.txt (Cipher No. 1) as E551-E558, E560, E562, E564, E565 (10 Oct 2026).
Not filed: F6 5905/0 (in print, OR I/47 pt 2), F9 5914/1 (holder clear copy 7782), F11 5915/1 (holder clear copy 7784), F13 5918/0 (in print, Grant Papers 14); ids E556 E559 E561 E563 stay unused.
Usage: python3 fm65e_file.py [--dry]  Idempotent. Step-0 numbers are read from fm65e_step0.out."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
rows = {}
for ln in (HERE/"fm65e_step0.out").read_text().splitlines()[1:]:
    f = ln.split("\t"); rows.setdefault(f[0], {})[f[2]] = f
def s0(F):
    a, b = rows[F]["no1"], rows[F]["no1shuf7"]
    return (f"Step 0 (fm65e_step0.py, information only on mssEC 25 under the Wave 2 ruling; the page transcription of the row is its own cipher copy): No. 1 (a) {a[4]} ({a[5]}) vs (b) p95 {a[6]}, {'HIT' if a[7]=='HIT' else 'no hit'}; "
            f"under one meaning-shuffled No. 1 copy (seed 7) (a) {b[4]} vs {b[6]}, {'HIT' if b[7]=='HIT' else 'no hit'}; (c) key-dependent words: {a[9]}. ")
BASE = "FM65-E (10 Oct 2026, account 1, for LANE LEDGER-13): book No. 1 per BOOK-FM65 (header features and month; no row-level book test beyond the share table). "
SPEC = {
 "F1": ("E551", "Page 354", "mssEC 25 (obj 5952, pointer 5898), 4 Feb 1865, received at Ft Monroe by Sheldon, closing line 'T. T. Eckert', signature word 'Buxton' (the Secretary of the Navy in the pair 5867/0 and clear copy 8511): [two] vessels exclusive of the Rhode Island at the yard or in the Roads, [available] to patrol from Cape Henry to Cape Fear River whilst troops [are moving] south; addressee and opening words unread (FM65-E; row 5898/1; weak, 41 words)",
  "Weak: the clause rests on eight key values (2, Rhode Island, Roads, Available, Fear, River, Troops, South), but 'wessells' = vessels, 'pat roll' = patrol and 'K penri' = Cape Henry are plain misspellings the decoder leaves as written, read by hand (M, not key readings), and the addressee words 'Berrying famish' are decoded to [Chief of Staff] [Norfolk] which do not fit (M, unread). The shuffled No. 1 copy gives 'Beauregard ... Goldsboro ... Maj Gen O. O. Howard ... Telegraph' for the same words, and No. 2 gives 'Secretary of State ... Canby ... Subsistence ... Sumter'. Not in print (exact-phrase grep of 184 volumes none; windows only the Rhode Island / Hampton Roads strand of OR I/46 pt 2 and ORN I/11, other texts; be-api 'exclusive of the Rhode Island': 1863 and 1798-era hits rejected). No holder clear copy (CISOSEARCHALL 'Sheldon wessells sligo wileys Rhode Island yard' and 'Sheldon Eckert wessells': own page and three other ledger pages that carry Sheldon and Eckert, none a clear copy of this text)."),
 "F2": ("E552", "Page 355", "mssEC 25 (obj 5952, pointer 5899), 4 Feb 1865 Ft Monroe, Sheldon to Maj. Eckert, Washington, for [the Secretary of the Navy, 'Buxton']: 'Sir, [your telegram] received; we have but one vessel, the Dumbarton, ready, and she had been [promised] to [an officer, name unread] to convey him up the James River; the Cambridge will be available on Tuesday next'; signed 'Jay M. ...' (unread) and Geo. D. Sheldon (FM65-E; row 5899/0)",
  "'Dumbarton' is plain in the row and is the flag-ship of Commodore Radford's James River Flotilla (OR I/46 pt 2, Radford to Grant, 3 Mar 1865: 'Flag-ship Dumbarton'; ORN I/11 also names a Dumbarton in the North Atlantic Blockading Squadron): context, not this telegram. 'Came bridge' = Cambridge is read by hand (M), as is 'Sir wranglam' = 'your telegram' (unread). The decoder gives [1000]d for 'promised' (a key-row slip, M) and [Chief of Staff]ing for the signature. Under the meaning-shuffled No. 1 the same words give 'Valley Trenton' for the James River. Not located in print (exact phrase none; be-api 'Dumbarton' 'Cambridge' available Tuesday next: ten hits, all Times of London and Daily Telegraph items of 1942-1988, rejected). No holder clear copy (CISOSEARCHALL 'Dumbarton Came bridge Tuesday promised convey': own page only)."),
 "F3": ("E553", "Page 358", "mssEC 25 (obj 5952, pointer 5902), 8 Feb 1865 [11 PM], J. H. Emerick, Hdqrs Army of the James, for [Maj. Gen. Ord]: 'I would respectfully suggest that the purposes of the Commission be more advanced by placing the Command of the Eastern District temporarily in hands of General Vogdes, as all my time and attention is devoted to the investigation'; signed George H. Gordon, Brigadier General, forwarded by Geo. D. Sheldon (FM65-E; row 5902/1)",
  "Mostly plain; key values in the clause are 'Mentor' = Ord (addressee, as in 5918/0's signature, BOOK-FM65), 'polka' = Command, 'torch' = of the, 'shelby' = General, 'palsy' = Brigadier General. Context printed in OR I/46 pt 2 (IA warofrebellion014602rootrich, scratch djvu): Ord to Grant 7 Feb 1865 6.20 p.m. 'I propose ordering at once General Vogdes to relieve General Gordon on the commission; General Gordon to relieve General Shepley', approved the same day; Ord to Grant 7 Feb 7 p.m. objecting to Vogdes for Norfolk; the index lists 'Gordon, George H. Assigned to temporary command of District of Eastern Virginia' and 'Shepley ... relieved ... 504' (index entry, page not read on an image); Gordon's Norfolk order of 13 Feb puts Vogdes in command of the post of Norfolk and Portsmouth. The row's own text is not in those pages (exact phrase 'placing the Command of the Eastern District' none; 'purposes of the Commission' hits only 'Despatches' of another century; be-api 'Vogdes' 'Eastern District' Gordon Commission: 0). No holder clear copy (CISOSEARCHALL 'Vogdes Gordon investigation Eastern District Commission': own page only)."),
 "F4": ("E554", "Page 358", "mssEC 25 (obj 5952, pointer 5902), 8 Feb 1865 [12 noon or 12.30 PM] Ft Monroe, Geo. D. Sheldon, for [Brig. Gen.] Gordon: 'you will have to take the command for the present; the investigation can progress quietly at the same time; General V[ogdes] will not obtain [it]'; signed [Ord] (the reply to E553; short, 24 tokens, weak) (FM65-E; row 5902/2)",
  "Short and weak: two connected clauses with three key values (Brigadier General, Command, General; signature Mentor = Ord), the rest plain; the reading hangs together with E553 and with the printed 7 Feb exchange in OR I/46 pt 2 (Ord proposing that Gordon relieve Shepley and Vogdes relieve Gordon on the commission), which is the only support for the sense. The shuffled No. 1 copy gives 'you will have to take the Maj Gen W. T. Sherman for the present ... [Danger] V will not obtain ... [W. F. Smith]'. 'It is obtain very plain Emerick' after the signature is left unread (Emerick is the operator named in E553). Not located in print (exact phrases 'investigation can progress quietly', 'take the command for the present': none; be-api: 0). No holder clear copy (CISOSEARCHALL 'Vogdes Gordon investigation progress quietly Emerick': own page only)."),
 "F5": ("E555", "Page 360", "mssEC 25 (obj 5952, pointer 5904), 9 Feb 1865 [12.30 PM], Washington, Rucker via Beckwith to Sheldon at Ft Monroe: dispatch received [for 1 battery and 440 horses]; Schofield's corps, with about 5000 of Meagher's division, shipped from here and Annapolis; still waiting for two divisions of the 23rd Corps, about 10,000 men, the horses of regimental and staff officers, 3 or 4 batteries, 306 mule teams and wagons and 102 horse ambulances; 2,500 of these troops will sail from here tomorrow morning and the remainder as soon as ships arrive and are prepared and loaded; signed D. H. Rucker, Brigadier General, S. H. Beckwith (FM65-E; row 5904/1; BOOK-FM65 test row: clause reused, not re-derived)",
  "BOOK-FM65 verdict for this row: No. 1, clause '[Schofield]'s [corps] with about [5000] of Meagher's [division] shipped from here and Annapolis ... still waiting while [2] [division]s of [23] [corps], about [10000] [men] ... [306] mule teams ... [2500] of these [troops] will sail from here [tomorrow] morning', with the same tokens nonsense under the shuffled copies; No. 2 reads H31 against No. 1's H53. The numerals (5000, 10000, 306, 102, 2500) are key values and M together; the 'Glass ring alls' span is Ingalls (plain). Context in print, not this telegram: OR I/47 pt 2 (IA warofrebellion014702rootrich) prints the Annapolis telegram of 3 Feb 1865 'One of General Schofield's brigades arrived at 5.30 p.m., and is being embarked' and the order sending 'The Second and First Divisions, Twenty-third Army Corps ... will embark at Alexandria or Annapolis, as may be directed by Brigadier-General Rucker, quartermaster'; the holder pointers 7721, 8538, 8561 carry the neighbouring 23-24 Jan and 2 Feb telegrams on the same movement, none this one. Exact phrases ('306 mule teams', 'about 10,000 men') none in the Fort Monroe context; be-api whole-collection 'Meagher Schofield Rucker Annapolis mule teams ambulances': ten hits, all general Schofield/Rucker passages of OR I/45 and memoirs, rejected. No holder clear copy (CISOSEARCHALL 'Meagher Schofield Rucker ambulances mule teams' 0 hits; 'Meagher Schofield': 7721 8538 8561, read, none a copy)."),
 "F7": ("E557", "Page 363", "mssEC 25 (obj 5952, pointer 5907), 16 Feb 1865 Ft Monroe, Sheldon to Maj. Eckert, Washington, for Comdr H. A. Wise, Chief of the Bureau of Ordnance: the [submarine torpedoes ('Sub squdron torpid owes', plain, read by hand, M)] mentioned in the Bureau's letter of the 25th ultimo have not been received; they are wanted for immediate use on the James River; 14 in addition to these [6] are also required; signed D. Lynch, Commander and Inspector of Ordnance (FM65-E; row 5907/1)",
  "Key values in the clause: 16 (date), Washington, 25, James River, 14, 6, Command = Er; the vocabulary of the torpedoes and the signature are plain. Related telegrams in print and in the holder text, not this one: ORN I/11 prints Lynch to Cdr W. A. Parker, off Norfolk, 24 Jan 1865 'The Bureau of Ordnance can not furnish the torpedoes required'; the holder page 8538 (mssEC 13 p.60) carries Lynch to Wise 24 Jan 1865 '12 torpedoes of nine hundred pounds each ... required by Comdr Parker ... James river for immediate use' (clear copy of another message). This row of 16 Feb is a follow-up asking for the earlier consignment; exact phrases none; be-api 'torpedoes Lynch Bureau ultimo immediate use': ten hits, all OR/ORN passages on torpedoes in other contexts, rejected; Butler Corr. V, Grant Papers 13-14: no Lynch telegram among the snippets. No holder clear copy (CISOSEARCHALL 'Lynch Bureau letter ultimo immediate use squadron': own page only)."),
 "F8": ("E558", "Page 368", "mssEC 25 (obj 5952, pointer 5912), 22 Feb 1865 Ft Monroe, Sheldon to Maj. Eckert, Washington, for [Maj. Gen. Ord]: General Ord requires an office at Yorktown at once; there is also anxious inquiry about an office at the Quartermaster Department here; can you supply these operators; the one at Yorktown is considered imperative (FM65-E; row 5912/1)",
  "Five key values (Volunteer, Ord, Yorktown, Quartermaster, Department), the rest plain; the sense is supported by its follow-up E560 (24 Feb, the order to establish the Yorktown station), not by a print. Under the shuffled No. 1 copy 'Yorktown' becomes 'Capture' and 'Hurlbut', under No. 2 'Shelbyville'. Not located in print (OR I/46-47 windows found only telegraph-office passages of other dates; be-api 'anxious inquiry' office Yorktown operators: one hit, a 19th-century gardening journal, rejected). No holder clear copy (CISOSEARCHALL 'Hastings Vinton anxious inquiry office imperative': own page only)."),
 "F10": ("E560", "Page 371", "mssEC 25 (obj 5952, pointer 5915), 24 Feb 1865 Ft Monroe, Sheldon to Maj. Eckert, Washington, enclosing 'Chief Quartermaster's office, Monroe, 24th': 'The Major General [Commanding] has directed that a Telegraph station be established at Yorktown, Virginia, without delay. Please take the necessary steps to provide a [battery] and operator and establish the office as speedily as practicable. Very respectfully ... [William] D. James, Captain, A.Q.M. and Acting Chief Quartermaster'; 'Foregoing respectfully forwarded to Major Eckert, Asst. Supt., &c. Geo. D. Sheldon' (FM65-E; row 5915/0)",
  "The follow-up to E558. Key values in the body: Quartermaster, Monroe, 24, Major, General, Telegraph, Yorktown, Virginia, Battery (the 'Hastings Alba' of the page), Captain; the grammar is plain. The decoder's [Battery] for 'pagan' and the [100] for 'yoke William' are slips (M). Which Major General (Ord) is not stated in the row (M). Not located in print (exact 'station be established at Yorktown' none; be-api none; 'Acting Chief Quartermaster' hits only other volumes' officers). No holder clear copy (CISOSEARCHALL 'Hastings station established Acting Chief Quartermaster James Asst. Supt' 0 hits; 'Hastings Vincent station': own page only)."),
 "F12": ("E562", "Page 373", "mssEC 25 (obj 5952, pointer 5917), 25 Feb 1865 Ft Monroe, Sheldon to Maj. Eckert, Washington, for Hon. E. B. Washburne, Chairman of the Committee of Commerce: 'I sent for Johnson to try him. It would be a pity that the greatest rascal should escape. I can send him to you under guard but do not let him turn State's evidence. His confidential [statement] is clear. Do you want him?'; signed George H. Gordon, Brigadier General; 'raining here tonight', Geo. D. Sheldon (FM65-E; row 5917/1; weak: mostly plain)",
  "Weak: the body is plain English with two key values ('saddle' = Guard, 'palsy' = Brigadier General) besides the header words (Volunteer, Norfolk, 25, Washington); the sense is not tested by the key. Under the shuffled No. 1 copy the two values become nonsense. The sender is Brig. Gen. George H. Gordon (Norfolk, Eastern Virginia; see E553), and 'Johnson' is unidentified (M); the Committee of Commerce of the House under Washburne is plain. Not located in print (exact phrases none; windows zero; be-api 'I sent for Johnson' 'turn State evidence': 0; 'Do you want him' hits OR I/40 and Butler Corr. V in unrelated contexts, rejected). No holder clear copy (CISOSEARCHALL 'Washburne Committee of Commerce Johnson rascal state evidence' and 'Washburne Johnson rascal': 0 hits)."),
 "F14": ("E564", "Page 374", "mssEC 25 (obj 5952, pointer 5918), 4 Mar 1865 [10 PM] Ft Monroe, Sheldon to S. H. Beckwith, City Point, for Colonel George W. Bradley, Chief Quartermaster: 'I am entirely out of pilots. I was compelled to furnish the Navy with [two] pilots today for monitors to go up James River'; signed Captain James; 'sent 10.10 PM' (FM65-E; row 5918/1)",
  "Eight key values around plain words (Colonel, Quartermaster, City Point, 2, Today, James, River, Captain); the decoder reads the plain word 'Pilots' as [Capture (-ed, -ing)] (a plain-word misfire, M), and 'peach pilots wedge' as [2] ... [Today]. Grant Papers 14 (IA papersofulyssess0014gran, be-api) prints a Bowers telegram of the same days about pilots for boats ('The pilots are ready. Direct the boats to call on Colonel ...'): a different text. Not located in print (exact phrases none; windows only monitors/James River passages of other texts; be-api 'out of pilots' monitors James River: 0). No holder clear copy (CISOSEARCHALL 'pilots monitors Bradley furnish Navy James': own page only)."),
 "F15": ("E565", "Page 375", "mssEC 25 (obj 5952, pointer 5919), 5 Mar 1865 [11.30 AM, sent 11.35] Ft Monroe, Sheldon to S. H. Beckwith, City Point, for Lieut. Col. T. S. Bowers, A.A.G.: 'I cannot find the scout that was to report to me this morning. [We shall] be ready to proceed in two hours. Shall I go without him?'; signed S. H. Roberts, Colonel, 139th New York Volunteers [Expedition ...]; 'fine morning' (FM65-E; row 5919/1)",
  "Key values: Colonel, General, City Point, Scout (the 'wolf' of the page), Report, 2, Colonel, 139, New York, Volunteer, Expedition; the signature and the 'Expedition' tail are M. 'Colonel S. H. Roberts, 139th New York' is a field officer of the Army of the James in Mar 1865 (M; the regiment was not checked in any volume here). Not located in print (exact phrases none; windows zero; be-api 'Roberts' '139th New York' Bowers scout: ten hits, none this telegram: OR I/46 scouting passages and Whitman notebooks, rejected). No holder clear copy (CISOSEARCHALL 'Bowers Roberts proceed Beckwith ready Shall I go': own page only)."),
}
txt = (HERE.parent/"ciphertext.txt").read_text(encoding="utf-8")
body = {}; cur = None
for ln in (HERE/"fm65e_entries.txt").read_text(encoding="utf-8").splitlines():
    if ln.startswith("### "): cur = ln.split("|")[0][4:].strip(); body[cur] = []; continue
    if cur and ln.strip(): body[cur].append(ln)
add = ""
for F, (eid, page, desc, note) in SPEC.items():
    if f"### {eid} |" in txt: continue
    ptr = re.search(r"pointer (\d+)", desc).group(1)
    add += f"### {eid} | {page} | {ptr} | {desc}\n" + "\n".join(body[F] + ["note: " + BASE + s0(F) + note]) + "\n\n"
if not add: print("already present")
elif "--dry" in sys.argv: print("would add\n" + add)
else: (HERE.parent/"ciphertext.txt").write_text(txt.rstrip("\n") + "\n\n" + add.rstrip("\n") + "\n", encoding="utf-8"); print("added", add.count("### E"))
