#!/usr/bin/env python3
"""FM65-C: file ten of the twelve rows of fm65c_entries.txt into ../ciphertext.txt (Cipher No. 1) as E525-E532, E534, E535 (10 Oct 2026).
Not filed: F1 5867/0 (holder clear copy, pointer 8511) and F10 5877/1 (holder clear copy, pointer 7702); their ids E524 and E533 stay unused.
Usage: python3 fm65c_file.py [--dry]  Idempotent. Step-0 numbers are read from fm65c_step0.out."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
rows = {}
for ln in (HERE/"fm65c_step0.out").read_text().splitlines()[1:]:
    f = ln.split("\t"); rows.setdefault(f[0], {})[f[2]] = f
def s0(F):
    a, b = rows[F]["no1"], rows[F]["no1shuf7"]
    return (f"Step 0 (fm65c_step0.py, information only on mssEC 25 under the Wave 2 ruling; the page transcription of the row is its own cipher copy): No. 1 (a) {a[4]} ({a[5]}) vs (b) p95 {a[6]}, {'HIT' if a[7]=='HIT' else 'no hit'}; "
            f"under one meaning-shuffled No. 1 copy (seed 7) (a) {b[4]} vs {b[6]}, {'HIT' if b[7]=='HIT' else 'no hit'}; (c) key-dependent words: {a[9]}. ")
BASE = "FM65-C (10 Oct 2026, account 1, for LANE LEDGER-13): book No. 1 per BOOK-FM65 (header features and month; no row-level book test beyond the share table). "
SPEC = {
 "F2": ("E525", "Page 324", "mssEC 25 (obj 5952, pointer 5868), 7 Jan 1865 Baltimore, received at Ft Monroe (header 'Geo D. Sheldon Ft Monroe Va.'): the Baltic left for Monroe before the order given from Washington could be countermanded; coal her there and return her to Annapolis for troops; it is impossible for her to come up here; reads as signed R. M. Newport, Colonel and Quartermaster (FM65-C; row 5868/0)",
  "Plain words that are also key rows misfire: 'baltic' decodes [Chattahoochee], 'Sampson' decodes [Ferry] (the E313-type slip; M). 'Webster' is the book's word for 'signature' (key row), so 'Are see Webster' reads 'for [Colonel] Are see [signature]': the addressee is the two plain words 'Are see' (initials; M). 'are M new port' read as R. M. Newport is M by context only: OR I/46 pt 2 (IA warofrebellion014602rootrich, scratch djvu) prints Newport's Baltimore telegram of 7 Jan 1865 6 PM 'The Baltic left for Fort Monroe last night' (a different telegram; this row's wording is not in that volume). Not in print as such; no holder clear copy (CISOSEARCHALL 'Annapolis coal Sampson impossible': own page only)."),
 "F3": ("E526", "Page 323", "mssEC 25 (obj 5952, pointer 5867), 9 Jan 1865 Ft Monroe, Sheldon to J. H. Emerick, City Point: 'Add to [Ingalls'] message' (plain 'ring galls'): no other vessels of forage here; no troops arrived nor sailed; has not seen General Abbott; by direction of the Quartermaster, signed William L. James, Captain and A.Q.M. (M for the signature) (FM65-C; row 5867/2; short, 34 tokens)",
  "Short: two clauses with code meanings (forage, troops; 'shade' = Forage is the same value as in the sibling 5870/0, 'whiskey' = Troops as in E465), so a weak H reading; the shuffled copies give nonsense. 'ring galls' is left as written by the decoder (plain, Ingalls: BOOK-FM65 read the same plain form in 5849/0). Not in print: be-api and OR I/46-47 window search none; holder CISOSEARCHALL 'Emerick Abbott' found pointer 9142, a different telegram (18-19 Dec 1864, Eckert to Emerick)."),
 "F4": ("E527", "Page 325", "mssEC 25 (obj 5952, pointer 5869), 12 Jan 1865 Ft Monroe, Sheldon to Maj. Eckert, Washington: 'The following is forwarded to the War Department for approval': a telegram from Eastville, January 11, to Major George J. Carney, Supt. of Negro affairs, Norfolk: [Butler] is relieved, I think I will resign, what are you going to do; signed Frank J. White, Lieut. [Colonel] and A.A.G. (FM65-C; row 5869/1)",
  "'Knox' decodes [Maj Gen B. F. Butler] (H key row); OR I/46 pt 2 prints Grant's request of 4 Jan 1865 for Butler's removal, so the value fits the week (the date of the relief itself not checked here; the row's text is not printed). 'White' decodes [Report] (plain name misfire, M); 'Janeway' is left as written (plain name; Lt Col H. H. Janeway is in OR I/46, not tied to this row, M). 'July August and finis' is ledger filler after the signature. Carney: Maj. George J. Carney, Supt. of Negro Affairs, Norfolk district, is in the print as a person (OR I/33 order of 16 Mar 1864; Butler Corr. V index 664 'Carney, Maj. George C', not this telegram). Holder CISOSEARCHALL 'Carney Tappan Janeway': own page only."),
 "F5": ("E528", "Page 326", "mssEC 25 (obj 5952, pointer 5870), 12 Jan 1865 Ft Monroe, Sheldon to S. H. Beckwith, City Point, for [Brig. Gen.] Ingalls (plain 'Ring galls'): no forage vessels since Captain James telegraphed of today; the Ariel and General Sedgwick have arrived from Baltimore with troops; I do not know what others are to come nor any reason for delay; signed by a Colonel and Quartermaster (name not in the row) (FM65-C; row 5870/0)",
  "BOOK-FM65's share guess for this row was No. 2 (.405/.432/.27); under No. 1 the decode is coherent and its vocabulary matches 5867/2 and 5871/1 (Ingalls, Forage, Troops, Baltimore, Rawlins), so No. 1. Context in print, not this telegram: OR I/46 pt 2 prints Fort Monroe 12 Jan 1865 'Two steamers - the Ariel (973 men) and the Sedgwick (496 men) - have arrived' (letter to Rawlins, a different text) and Newport 7 Jan 'Ariel, Illinois, Victor, General Sedgwick now here'. This row's text not located in print. No holder clear copy (CISOSEARCHALL 'Beckwith Ariel Sedgwick arrived': pointers 5870, 5871 only, both this ledger's cipher copies)."),
 "F6": ("E529", "Page 327", "mssEC 25 (obj 5952, pointer 5871), 12 Jan 1865 Ft Monroe, Sheldon to Maj. Eckert, Washington, for the Secretary of the Navy: Mr. Ericsson writes he has the Department's approbation for the Puritan's shaft being put in here; shall I get ours out; the blockade runner arrived 4 PM; Niagara and a second vessel to leave Beaufort Wednesday night; buoys lighted; weather favourable; signed John Rodgers (plain 'John Rod jars'; the decoder prints [Maj Genl U.S. Grant] for 'John', a misfire) (FM65-C; row 5871/0)",
  "Same Wilmington/Fort Fisher naval strand and same signature as the holder clear copy at pointer 8511 (7 Jan 1865 Ft Monroe 8 PM 'for Sec Navy ... Jno Rodgers'), which is a clear copy of 5867/0, not of this row. C-type checks on key rows from that pair (5867/0 vs its clear copy 8511): Buxton = Secretary of the Navy, Hamlet = Wilmington, flood = 12, quaker = danger. 'Niagara' decodes [D. D. Porter] (a ship name also a key row: M). Not located in print (OR I/46-47 exact and window search none; ORN I/11-12 be-api 'Ericsson': one irrelevant snippet). No holder clear copy (CISOSEARCHALL 'Ericsson approbation puritans': own page only)."),
 "F7": ("E530", "Page 327", "mssEC 25 (obj 5952, pointer 5871), 13 Jan 1865 Ft Monroe, Sheldon to S. H. Beckwith, City Point, for [Brig. Gen.] Rawlins, Chief of Staff: the Sedgwick (500 and 1 men), Ariel (900 and 73 men) and Ashland (200 and ... men) have sailed in perfect order, Mr. Morgan (FM65-C; row 5871/1)",
  "Step 0 here is a MISS (a .484 is under the script's 0.5 floor, though over p95 .226); the reading stands on the clause. External number check: OR I/46 pt 2 prints the Ariel with 973 men (12 Jan 1865 letter, Fort Monroe to Rawlins), and 900 + 73 = 973; the Sedgwick prints 496 against the decode's 500 + 1 (M, the numeral combination is uncertain). 'Ashland' decodes [Alabama] (plain ship name misfire, M). Mr. Morgan = Lt Col M. R. Morgan, Chief Commissary, whom OR I/46 pt 2 (7 Jan) sends to Fort Monroe to load vessels (M). Telegram not located in print; no holder clear copy (CISOSEARCHALL 'Sedgwick Ariel sailed perfect order': own page only; be-api quoted 'sailed in perfect order': three irrelevant hits rejected, 1884 journal, 1862 newspaper, 1940s book)."),
 "F8": ("E531", "Page 329", "mssEC 25 (obj 5952, pointer 5873), 15 Jan 1865 Ft Monroe, Sheldon to S. H. Beckwith, City Point, for [General] Rawlins [Chief of Staff]: the Oriental (700 and 78 men) has sailed; the Suwo Nada (900 and 30 men) will start in half an hour; this makes 6 vessels, 5100 and 9 men, all as ordered; Mr. Morgan, [Colonel], &c. (FM65-C; row 5873/1)",
  "Vessel names are plain in the row ('weasler Oriental', 'Survo Nada' for Suwo Nada, as printed in OR I/46 pt 2: Newport/Van Vliet telegrams of 3-12 Jan 1865 name the Suwo Nada, Ashland and Oriental as Baltimore transports; the Oriental 'can carry 1,000 men'): context, not this telegram. The sum 5100 + 9 for six vessels is the reader's arithmetic on the decode (M). Not located in print; no holder clear copy (CISOSEARCHALL 'Oriental Morgan half hour': own page only)."),
 "F9": ("E532", "Page 333", "mssEC 25 (obj 5952, pointer 5877), 16 Jan 1865 City Point, S. H. Beckwith to Sheldon at Ft Monroe: [to the Chief Quartermaster, Colonel Webster (the row's 'webb Stir', M)] transportation for 4000 men, 50 six-mule teams complete, with 15 days' rations, water and coal; what time can this transportation be here, answer; signed G. W. Bradley, Colonel and Chief Quartermaster; S. H. Beckwith (FM65-C; row 5877/0)",
  "Same order as the printed Rawlins to Col. H. C. Webster, Chief Quartermaster, Fort Monroe, City Point 16 Jan 1865 (OR I/46 pt 2: 'Vessels sufficient to carry 4,000 men and 50 six-mule teams are required', fifteen days' rations, coal, water), in different words, with a request for the arrival time: a sibling, so this telegram's own text is not located in print. The decoder's [Reinforcements] for 'webb' is a key row on what is likely 'Webster' split in the transcription (M). Quoted whole-collection be-api 'mule teams complete': 10 hits, all 1909 newspaper advertisements and one auction catalogue, rejected. No holder clear copy (CISOSEARCHALL 'Bradley mule teams complete': own page only)."),
 "F11": ("E534", "Page 333", "mssEC 25 (obj 5952, pointer 5877), 16 Jan 1865, two messages in one row: (1) Ft Monroe, Sheldon to S. H. Beckwith, City Point, for Colonel G. W. Bradley: the Dupont, Thames, Haze and Sentinel are all we have; these are sufficient for [1300] men and the teams; cannot say when I can obtain the remainder; have you nothing at City Point; signed a Colonel and Quartermaster; (2) City Point, Beckwith to Sheldon, for Colonel M. P. Small, C.S., Monroe: General Grant directs that you put 15 days' rations on such vessels as the Quartermaster designates; the Quartermaster will inform you how many men each vessel will carry; ditto me as each vessel is rationed and the number of men; Mr. Morgan, Lieut. [Colonel]; S. H. Beckwith (FM65-C; row 5877/2)",
  "'Dupont', 'Thames', 'Haze' and 'Sentinel' are plain vessel names (OR I/46 pt 2 names the Commodore Du Pont and Thames in the Fort Fisher fleet list and 'the steamer Haze at Bermuda Hundred' on 30 Jan 1865); the decoder's reading of 'Dupont' etc. leaves them as written. Message 2 is the telegraphic form of the printed Grant order of 16 Jan to Webster (see E532): the row's wording ('put fifteen days rations on such vessels as the Quartermaster designates') is not that text. Step 0 is a MISS (a .281, under the script's 0.5 floor, over p95 .141); the 64-word body holds two messages. Not located in print; no holder clear copy (CISOSEARCHALL 'Haze Sentinel Thames Dupont': own page only). The row's first message may be the answer to E532."),
 "F12": ("E535", "Page 334", "mssEC 25 (obj 5952, pointer 5878), 17 Jan 1865 Ft Monroe, Sheldon to S. H. Beckwith, City Point, for [Brig. Gen.] J. A. Rawlins: 3 of the vessels returned from the expedition disabled; enough are here to carry 3500 men, 50 wagons and animals; more expected; every effort will be made to have all the vessels ready by tomorrow noon; the Quartermaster at City Point will be telegraphed when each vessel leaves here; will the Fort Fisher news change your instructions in regard to mortars, troops or ammunition; signature block as filed 'Horace Porter Lieut [Colonel] and A.D.C.' (who speaks the clause is M) (FM65-C; row 5878/1; BOOK-FM65 test row: clause reused, not re-derived)",
  "BOOK-FM65 verdict for this row: No. 1, clause '[3] vessels returned [from the] [expedition] disabled ... enough are here to carry [3500] [men] [50] wagons and [100] and [50] ...' with the same tokens nonsense under its shuffled copies. 'Monroe' decodes where the page has plain 'mandate animals' (M). The last two lines ('City Point Jan. / 65 Geo. D. Sheldon Ft Monroe') are the header of the next message (5878/2), kept as transcribed. Not located in print (exact-phrase grep of 183 volumes, window search of OR I/46-47, ORN I/11-12 and Butler Corr. V be-api); no holder clear copy (CISOSEARCHALL 'disabled wagons mortars Fisher': own page only)."),
}
txt = (HERE.parent/"ciphertext.txt").read_text(encoding="utf-8")
body = {}; cur = None
for ln in (HERE/"fm65c_entries.txt").read_text(encoding="utf-8").splitlines():
    if ln.startswith("### "): cur = ln.split("|")[0][4:].strip(); body[cur] = []; continue
    if cur and ln.strip(): body[cur].append(ln)
add = ""
for F, (eid, page, desc, note) in SPEC.items():
    if f"### {eid} |" in txt: continue
    ptr = re.search(r"pointer (\d+)", desc).group(1)
    add += f"### {eid} | {page} | {ptr} | {desc}\n" + "\n".join(body[F] + ["note: " + BASE + s0(F) + note]) + "\n\n"
if not add: print("already present")
elif "--dry" in sys.argv: print("would add\n" + add)
else: (HERE.parent/"ciphertext.txt").write_text(txt.rstrip("\n") + "\n\n" + add.rstrip("\n") + "\n", encoding="utf-8"); print("added", add.count("### E"))
