#!/usr/bin/env python3
"""FM65-D: file twelve of the sixteen rows of fm65d_entries.txt into ../ciphertext.txt (Cipher No. 1) as E536 E537 E539 E541-E546 E548-E550 and E521
(10 Oct 2026). Not filed: F3 5885/0 (second message has holder clear copy 8531), F5 5886/0 (holder clear copy 8538), F12 5891/1 (plain), so E538,
E540, E547 stay unused. E521 is the second message of 5861/2 only (FM65-B held it; the first message is the holder clear copy 8508).
Usage: python3 fm65d_file.py [--dry]  Idempotent. Step-0 numbers are read from fm65d_step0.out."""
import re, sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
rows = {}
for ln in (HERE/"fm65d_step0.out").read_text().splitlines()[1:]:
    f = ln.split("\t"); rows.setdefault(f[0], {})[f[2]] = f
def s0(F, whole=""):
    a, b = rows[F]["no1"], rows[F]["no1shuf7"]
    return (f"Step 0 (fm65d_step0.py{whole}, information only on mssEC 25 under the Wave 2 ruling; the page transcription of the row is its own cipher copy): No. 1 (a) {a[4]} ({a[5]}) vs (b) p95 {a[6]}, {'HIT' if a[7]=='HIT' else 'no hit'}; "
            f"under one meaning-shuffled No. 1 copy (seed 7) (a) {b[4]} vs {b[6]}, {'HIT' if b[7]=='HIT' else 'no hit'}; (c) key-dependent words: {a[9]}. ")
BASE = "FM65-D (10 Oct 2026, account 1, for LANE LEDGER-13): book No. 1 per BOOK-FM65 (month and header; the share table and a No. 1 / No. 2 / No. 9 decode of the row in fm65d.out). "
SPEC = {
 "F1": ("E536", "Page 335", "mssEC 25 (obj 5952, pointer 5879), 17 Jan 1865 12.30 Ft Monroe, Sheldon to Maj. Eckert, for C. A. Dana (Asst. Secretary of War): forwards the Tribune special correspondent's dispatch from the Wilmington expedition: Fort Fisher is ours with the adjacent defences of New Inlet; surrendered to the troops under General Terry after a well sustained assault of 4 hours, ending 9.30 PM Sunday 15 (Jan); garrison 2000 picked South and North Carolina troops; General [Whiting, the row's 'Report'ing, M] had expressed the belief that it was impregnable; between 1200 and 1500 prisoners; loss 'not exceed 6 ditto and 50' (numbers M); among the killed Colonels Bell and Pennypacker; at 7.30 AM Monday as the Vanderbilt was leaving, a bright flash and a stunning report, believed the explosion of the rebel powder magazine just outside the fort, anxiety for the men within; signed E H Hall (FM65-D; row 5879/0; 140 tokens)",
  "Longest row of the batch, 53 H tokens, with the shuffled copies reading the same plain words (a non-test, as above). 'Whiting' is the decoder's [General] [Report]ing (the plain name 'Shelby Whiting' misfires on 'Shelby' = General and 'Whiting' = Report; M). 'Day neigh' = Dana (plain). Numbers: '4 hours', '2000', '1200 and 1500' are H key rows; the loss figure is M. Print: Porter's Fort Fisher telegram (to Gideon Welles, 'Fort Fisher is ours. I send a bearer of despatches ... with all the contiguous works commanding New Inlet') is in the 18 Jan 1865 newspapers (IA be-api: The Press 18 Jan p.1 and The Pittsburgh Commercial 18 Jan, 'FORTRESS MONROE, Jan. 17'), a different dispatch with different wording, rejected as the text of this row; the Tribune correspondent's dispatch itself was not located (be-api whole-collection, 6 phrases, and exact phrases in 177 cached volumes: none). No holder clear copy (CISOSEARCHALL 'Tribune Special Correspondent Vanderbilt garrison': own page only)."),
 "F2": ("E537", "Page 339", "mssEC 25 (obj 5952, pointer 5883), 20 Jan 1865, Hd Qrs A. J. (operator R. O'Brien) 6 PM, to Ft Monroe (operator Geo. D. Sheldon), for Maj. Gen. [Ord]: 'Please notify Colonel Mulford (plain 'mule ford') on the flag-of-truce boat (the row's 'weasler' plus a code word that the decoder prints [New York], M) to remain at Varina until Mr. Blair arrives and is passed through the lines'; signed Grant ('Japan' read [Maj Genl U.S. Grant]); 'quite pleasant this evening' follows the signature (FM65-D; row 5883/0; short, 29 tokens)",
  "Book check (the share table put this row at No. 2 by .003): No. 1 reads 'Ord', 'Grant', 'Colonel'; No. 2 reads [Hunter D], [Casualties], [Jeff Davis], [Fire]ed: nonsense, so No. 1. Only 7 H tokens; the clause is mostly plain words, the code words giving addressee, signer and rank (graded M for the clause as a whole). External check (description, not text): O'Brien, Telegraphing in Battle (IA cu31924030909315 / telegraphinginba00obri, printed p.187, diary of Friday 20 January 1865): 'General Grant has gone to Washington; General Ord to Fort Monroe ... Grant telegraphed in cipher to hold the flag of truce boat until Mr. Blair arrives. This is significant, Blair going as a possible peace commissioner a second time to Richmond.' The diarist is the R. O'Brien who signs the row; the book paraphrases this telegram, it does not print it. The row's own wording not located in print (be-api whole-collection exact phrases 'until Mr. Blair arrives' and 'passed through the lines' Varina: only the O'Brien paraphrase and unrelated Blair biographies). No holder clear copy (CISOSEARCHALL 'Varina Blair passed lines': own page only)."),
 "F4": ("E539", "Page 341", "mssEC 25 (obj 5952, pointer 5885), Hd. Qrs. A. J. 23 Jan 1865 to Geo. D. Sheldon at Ft Monroe (operator R. O'Brien), to Captain Lynch commanding the ordnance ship St. Lawrence near Norfolk: send immediately by the Phlox the large torpedoes of 900 pounds each with insulating wire; I have immediate use for them; signed Parker, Commander, 5th Division (the row has 'William ah Parker' and 'Diversion' for Division, M), etc. (FM65-D; row 5885/1)",
  "Chain: this is Parker's order (23 Jan); the next day Lynch asks Washington for twelve 900-pound torpedoes 'required by Comdr Parker Comdg 5th Divn James river' -- holder clear copy at pointer 8538 (24 Jan 9.20 AM, Norfolk, 'for Comdr H A Wise Chf Bu Ord Washn', signed D Lynch Comdr & Inspector of Ord), which is the clear copy of 5886/0 (not filed, see NOTES), not of this row. 'Saint' decodes [Force] in 'Ship [Force] Lawrence' (plain word, key-row misfire, M); 'farmer' = Norfolk (same code as in 5886/0 and 5887/1). Not located in print (OR I/46 pt 2 window search and be-api whole-collection 'insulating wire' 'nine hundred pounds': none). No holder clear copy at another pointer (CISOSEARCHALL 'Phlox torpedoes Lawrence Lynch' and 'torpedoes insulating wire Parker': 5886 and 8538 only, neither this message)."),
 "F6": ("E541", "Page 343", "mssEC 25 (obj 5952, pointer 5887), Washington 24 Jan 1865 1 PM to Geo D. Sheldon at Ft Monroe, two messages: (1) for Colonel Webster, Quartermaster at Monroe: the steamer Nevada will be at Monroe in a day or two with recruits; please order her to City Point immediately after they have landed, also all other sea-going steam vessels that may reach Monroe during the next 5 or 6 days; signed Rucker; (2) another for Commander Lynch, ship St. Lawrence, Norfolk: telegram received; no torpedoes of the kind you name are available, it would take months to prepare them, and the Bureau does not know for what purpose these are intended; will not the rebel torpedoes on hand, or those on board the Stromboli, or those sent from the ordnance yard answer; signed H. A. Wise, Chief of Bureau; T. T. Eckert (FM65-D; row 5887/0; 85 tokens)",
  "Replies to the Lynch order of E539 / the clear copy 8538 (24 Jan). A second cipher copy of the same telegram sits at pointer 9943 (page 277, the Washington telegram book, 'GD Sheldon Washn Jany 24th 1865 Harriet Paradise Webster Vincent ...' with the identical cipher words, signed H A Wise chf Bureau): a witness for the transcription, not a clear copy; its next message (Halleck to Grant, 8.30 PM, ocean transports for sixteen thousand men) is a different telegram. M for [Rapidan] (a key row that misfires on the cipher word before 'will take months'). Not located in print (OR I/46 pt 2 window search, be-api whole-collection 'torpedoes of the kind you name' 'Nevada' Rucker: none). No holder clear copy (CISOSEARCHALL 'Nevada Rucker Lynch torpedoes': 5887 and 9943 only)."),
 "F7": ("E542", "Page 343", "mssEC 25 (obj 5952, pointer 5887), Ft Monroe 24 Jan 1865, Sheldon from Norfolk ('farmer') to Maj. Eckert, for the Secretary of the Navy ('Buxton'): the Saugus left this morning for Washington; General Grant needs her at once; she must be now half way; no use for me to send for her; will you let a message meet her and turn her back; Berrien (FM65-D; row 5887/1; 33 tokens)",
  "Short but the clause is specific; shuffled copies read the same plain words. 'John' = Grant in the row ([Maj Genl U.S. Grant]), 'Buxton' = Secretary of the Navy (C-checked in FM65-C against the holder clear copy 8511 of 5867/0). Not located in print (cached volumes: only a loose Saugus/Monroe/Fox hit in officialrecordso0009unse, a Fox telegram on monitors for the Gulf, unrelated, rejected; be-api whole-collection 'The Saugus left this morning': none). No holder clear copy (CISOSEARCHALL 'Saugus Berrien turn': none)."),
 "F8": ("E543", "Page 344", "mssEC 25 (obj 5952, pointer 5888), City Point 25 Jan 1865 to Geo. D. Sheldon at Ft Monroe, for Maj. Gen. [Ord]: 'I shall leave here tomorrow to be absent several days. I wish you to return to your headquarters in the field, see that in case of contingency you will be on hand to take charge of army operations from here. It will answer if you start up in the morning'; signed Grant ('Jersey'), 'thats all' S. H. Beckwith (FM65-D; row 5888/1; 40 tokens)",
  "Follows the 20 Jan telegram of E537 (Ord at Fort Monroe while Grant was in Washington). 'oysters' = Army in 'charge of oysters operations' (a key row, H). Not located in print: loose co-occurrence 'Ord absent several days' matched five volumes, each read in context and rejected (OR I/33 Kilpatrick 'absent several days' 1864, OR 41 pt 4 and OR 43 pt 1 unrelated orders, Baker's history, an unrelated 'absent from the city'); be-api 'take charge of army operations' returned one 1930 periodical. No holder clear copy (CISOSEARCHALL 'Ord absent several days operations': none)."),
 "F9": ("E544", "Page 344", "mssEC 25 (obj 5952, pointer 5888), City Point 26 Jan 1865 to Geo. D. Sheldon at Ft Monroe, for 'I N Palmer' (as transcribed) at Newbern: 'All asked for has been ordered; not less than 6000 men will report to you; prepare accordingly'; signed Grant, Beckwith (FM65-D; row 5888/2; short, 28 tokens)",
  "Short (13 H). The numeral '6000' and 'Newbern' are key rows. The addressee is the plain 'I N Palmer' (initials as transcribed; not identified here, M). The 6000 men may relate to the Schofield move (E545, E549; M). Not located in print (be-api whole-collection 'prepare accordingly' Newbern Palmer: index hits only; 'prepare accordingly' alone also hits OR I/42 and I/45, generic, rejected). No holder clear copy (CISOSEARCHALL 'Palmer Newbern prepare accordingly': none)."),
 "F10": ("E545", "Page 345", "mssEC 25 (obj 5952, pointer 5889), Ft Monroe 27 Jan 1865, Sheldon to Maj. Eckert, two messages: (1) Monroe to Lieut. Colonel G. W. Schofield (as written), Willards, Washington: send one battery with each division and let the others follow when convenient; signed Maj. Gen. J. M. Schofield; (2) another to Lieut. Colonel Boyd, Quartermaster, Willards, Washington: it will be necessary to bring transportation from Washington to follow the troops; if good mules cannot be obtained in Washington ask authority to bring those from Kentucky; signed Schofield (FM65-D; row 5889/2; 51 tokens)",
  "24 H of 51; both messages read in No. 1 and not under the shuffled copies. The addressee 'Lieut. Colonel G. W. Schofield' is plain as transcribed (M); the signer is decoded [Maj Genl J. M. Schofield]. Not located in print (cached volumes and be-api: 'one battery with each division' returns unrelated 1857-1862 regimental histories, rejected; 'bring those from Kentucky' mules: none). No holder clear copy (CISOSEARCHALL 'Schofield Willards Boyd batteries Kentucky mules': none)."),
 "F11": ("E546", "Page 346", "mssEC 25 (obj 5952, pointer 5890), Ft Monroe 29 Jan 1865, Sheldon to Maj. Eckert, for Senator L. F. S. Faster (as transcribed), Willards Hotel, Washington: 'Ship ordered to Portsmouth, New Hampshire. I do not wish to go. Have me detached here by telegraph. My executive officer Lieut. Commander Parker can take ship'; signed Joseph Land Man (as transcribed) (FM65-D; row 5890/2; 36 tokens)",
  "Book check (the share table put this row at No. 2): No. 1 reads Monroe, Washington, New Hampshire ('Hotel' misfires as [Longstreet], M); No. 2 reads [Tennessee], [Weldon], [Alabama], [Valley]: nonsense, so No. 1. The sender's name as transcribed is not decoded (M); the clause names no vessel. Not located in print (be-api whole-collection 'ordered to Portsmouth' 'New Hampshire' 'do not wish to go' hits only the 1860 Covode investigation, a different 'ordered to Portsmouth, New Hampshire' event, rejected). No holder clear copy except its own page (CISOSEARCHALL 'Portsmouth detached executive Parker': 5890 only)."),
 "F13": ("E548", "Page 351", "mssEC 25 (obj 5952, pointer 5895), Ft Monroe 2 Feb 1865 2.30 PM, Sheldon to Maj. Eckert, for Bates: 'ascertain immediately by what boat the President (the row's 'bologna') left Annapolis and the time of leaving and telegraph me in cipher; also the time the boat passes Point Lookout'; signed Eckert (FM65-D; row 5895/2; short, 29 tokens)",
  "Short (7 H, the rest plain). 'bologna' decodes [President U.S.] (key row, H); 'Annie police' is plain Annapolis; the addressee 'Bates' is plain (David Homer Bates, War Department telegraph office manager, M). Not located in print (be-api whole-collection 'what boat the President left Annapolis': none; loose co-occurrence of Bates, President, Annapolis, Point Lookout in the cached volumes: none). No holder clear copy (CISOSEARCHALL 'Bates President Annapolis Point Lookout boat': none)."),
 "F14": ("E549", "Page 352", "mssEC 25 (obj 5952, pointer 5896), Washington 2 Feb 1865, Geo. D. Sheldon at Ft Monroe, 'for Eckert': Maj. Gen. [Schofield] has called on Colonel Stager for a cipher operator to go with him tomorrow to North Carolina, and says he will in a short time need a construction corps and some operators; the Colonel refers the matter to you and has informed General Schofield of the fact; can you have the party selected to meet General Schofield at Monroe to accompany him, and shall I have Mack and party get ready to leave together with the material; answer; T. T. Eckert (FM65-D; row 5896/2; 50 tokens)",
  "Direction is not settled (M): the header is Washington to Sheldon and 'for Eckert', yet the body asks 'can you have the party selected' and is signed T. T. Eckert. 'Kingdom' decodes [Maj Genl J. M. Schofield] and 'abacus' [North Carolina] (key rows, H); 'stagers' and 'Mack' are plain names. Not located in print (be-api whole-collection 'cipher operator' Stager Schofield 'construction corps' returns O'Brien/Bates books on the telegraph corps, no Schofield telegram; cached volumes: none). No holder clear copy (CISOSEARCHALL 'Stager Schofield cipher operator construction': none)."),
 "F15": ("E550", "Page 353", "mssEC 25 (obj 5952, pointer 5897), Ft Monroe 2 Feb 1865, Sheldon to Maj. Eckert, for Captain Blodget, Quartermaster, Annapolis (2 AM): please inform General Schofield, should he arrive in Annapolis tonight, that I will be at (Annapolis) Friday morning with important despatches for him from General Sherman; signed Jay F. Anderson, Major and A.D.C. (FM65-D; row 5897/0; 35 tokens)",
  "Book check (the share table put No. 2 .003 ahead of No. 1 on this row): No. 2 reads [Tennessee], [Walker], [Pemberton], [McLamores Cove]: nonsense, so No. 1 ([Schofield], [Sherman], [Sumter] for 'An apple is' = Annapolis misfire, M). The sender is Major Jay F. Anderson (plain name). Not located in print (be-api whole-collection 'important despatches' Schofield Sherman Annapolis: the Bates and Lincoln telegraph books on other dates, rejected; cached volumes: none). No holder clear copy (CISOSEARCHALL 'Blodget Anderson Schofield Sherman despatches': none)."),
}
txt = (HERE.parent/"ciphertext.txt").read_text(encoding="utf-8")
body = {}; cur = None
for ln in (HERE/"fm65d_entries.txt").read_text(encoding="utf-8").splitlines():
    if ln.startswith("### "): cur = ln.split("|")[0][4:].strip(); body[cur] = []; continue
    if cur and ln.strip(): body[cur].append(ln)
add = ""
for F, (eid, page, desc, note) in SPEC.items():
    if f"### {eid} |" in txt: continue
    ptr = re.search(r"pointer (\d+)", desc).group(1)
    add += f"### {eid} | {page} | {ptr} | {desc}\n" + "\n".join(body[F] + ["note: " + BASE + s0(F) + note]) + "\n\n"
# E521: second message of 5861/2 only (FM65-B's decode, held for the clear copy of the first message)
if "### E521 |" not in txt:
    b = body["F16"]; i = [k for k, l in enumerate(b) if l.startswith("City Point")][0]
    note = ("note: " + BASE.replace("book No. 1 per BOOK-FM65", "book No. 1 per BOOK-FM65 and FM65-B's decode of this row") + s0("F16", " on the whole row, both messages") +
            "Only the second message is filed: the first message (Sheldon to Maj. Eckert, 'Mrs Ellen H. Stanton ... arrived here safely ... start for Savannah', 6 Jan 1865) is the holder clear copy at pointer 8508 (FM65-B) and stays unfiled. "
            "This message has no clear copy: CISOSEARCHALL 'Butler left Monroe Beckwith enquired' (FM65-D) and FM65-B's queries found none; 'Knox' decodes [Maj Gen B. F. Butler] (H key row, as in E527) and 'stomach animal' [Left] [Monroe]. "
            "Not located in print (exact phrases 'if General Butler has left Monroe', 'keep me posted' in 177 cached volumes: the second is generic and hits many volumes, rejected; be-api whole-collection 'if General Butler has left Monroe': none; loose co-occurrence Beckwith, Butler, left Monroe: none). "
            "Context only (M): FM65-C's note on E527 cites Grant's 4 Jan 1865 request for Butler's removal in OR I/46 pt 2; the row does not say why Beckwith, at City Point, is asking.")
    desc = ("mssEC 25 (obj 5952, pointer 5861), City Point 6 Jan 1865 to Geo. D. Sheldon at Ft Monroe: 'please ascertain immediately if [Butler] has left Monroe, and if so when and when bound; don't mention that I enquired; keep me posted'; S. H. Beckwith "
            "(FM65-D, from FM65-B's decode of row 5861/2, second message only; short, about 24 tokens)")
    add += "### E521 | Page 317 | 5861 | " + desc + "\n" + "\n".join(b[i:] + [note]) + "\n\n"
if not add: print("already present")
elif "--dry" in sys.argv: print("would add\n" + add)
else: (HERE.parent/"ciphertext.txt").write_text(txt.rstrip("\n") + "\n\n" + add.rstrip("\n") + "\n", encoding="utf-8"); print("added", add.count("### E"))
