#!/usr/bin/env python3
"""FM65-A: file the nine Fort Monroe 1865 rows of fm65a_entries.txt that the LEDGER-13 wave-2 ruling files (E500 E502 E504-E509 E511) into ../ciphertext.txt.
Not filed: F2 5849/0 (holder clear copy 7681), F4 5850/1 (in print OR I/46 pt 2 p.21), F11 5854/1 (holder clear copy 7682). IDs follow the brief's fixed block
(E500 = F1 ... E511 = F12); E501 E503 E510 stay unused. Usage: python3 fm65a_file.py [--dry]  Idempotent."""
import sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
S0 = "FM65-A step 0 (fm65a_step0.py, a/lcs-n/b p95): "
ROWS = {
 "F1": ("E500", "Page 303", 5847, "mssEC 25 (obj 5952, pointer 5847), 3 Jan 1865 Ft Monroe 2.30 PM, Sheldon (operator J. W. Sampson) to Col. Newport, chief quartermaster, Baltimore: as the anchor and chain cannot be furnished in time for the steamer Baltic she will not be sent on the expedition, so Newport need not send to New York for them; signed Wm L. James, Capt. AQM (FM65-A; row 5847/2; read from the transcription, no image)",
        S0 + "0.333 (8/24) / b 0.250 MISS. M by hand: the decoder's 'Donelson' for the plain 'anchor' and 'Chattahoochee' for the plain steamer name Baltic are key rows misfiring on plain words (the siblings 5858 and 5865 write 'Baltic' and 'anchor' plain, and 5865, Baltimore 6 Jan, is the reply about the Baltic's anchor and chain); 'france' = New York is H and fits 5865 ('she can go to france, coal and get her anchor and return to Annapolis'). Antecedent/answer: 5865 (6 Jan, J. W. Sampson to Sheldon). Not a clear copy, not in print (OR I/46 pts 1-3 and I/47 pt 1, I/51 pts 1-2 on disk, 183-volume grep, CISOSEARCHALL 'anchor chain Baltic Sampson' -> 5847 itself and 5865 only)."),
 "F3": ("E502", "Page 305", 5849, "mssEC 25 (obj 5952, pointer 5849), 3 Jan 1865 City Point 4.35 PM, S. H. Beckwith to Sheldon at Ft Monroe, for Gen. Rawlins by direction of Gen. Grant: the steamers coaled and watered under Gen. Ingalls's instructions are ready for service; turn them over to Col. Morgan, chief commissary, to be loaded with the required rations and tell him when the vessels are ready to receive them; Rawlins wishes to know what number of troops each steamer will carry (FM65-A; row 5849/1; transcription only)",
        S0 + "0.667 (4/6) / b 0.667 - (window of 6 words, no information). 'whisky' = Troops is S (KEY-TW; the decoder reads it so). 'cooling and watering' = coaling and watering (a plain slip the decoder leaves; M). Context in print: Rawlins to Morgan 10.30 a.m. 3 Jan and Morgan to Rawlins 11.30 a.m. 1 p.m. 5.30 p.m. 6.30 p.m. (OR I/46 pt 2 pp.21-22, the dates there read '5 January' by OCR) -- the same fleet, not this message. Not a clear copy (CISOSEARCHALL 'Morgan commissary coaling watering Rawlins' 0 hits), not in print on the phrases searched."),
 "F5": ("E504", "Page 307", 5851, "mssEC 25 (obj 5952, pointer 5851), 3 Jan 1865 Ft Monroe 6.30 PM, Sheldon to Beckwith at City Point, for Capt. Howell, AQM: the steamers ordered to report to Col. Bradley are the Euterpe, H. Livingston, Gen. Lyon, Varuna, A. Dupont, Prometheus, Thames, Idaho, DeMolay, McClellan, Champion, Weybossett and Towanda; the Atlantic, rationed for 1400 troops, is ready but draws too much water to go up; by direction of the chief quartermaster, Wm L. James (FM65-A; row 5851/0; transcription only)",
        S0 + "0.696 (32/46) / b 0.217 HIT (a non-test on this ledger, rule 3; BOOK-FM65's three shuffled-key copies hit the same row 36/59 /58/62 words). C check: 'the Atlantic, 1,400 men, cannot go up to City Point' is Morgan's 5.30 p.m. 3 Jan telegram (OR I/46 pt 2 p.22, 'January 6' by OCR) -- 1400 and 'draws too much water to go up' agree (numbers from the key: M for which code gives 1400). Col. Bradley, AQM at City Point, appears in OR I/46 pt 3 (March 1865, a different message). Fleet list not located: CISOSEARCHALL 'Euterpe Livingston Varuna Prometheus' -> 5851 only; phrase grep none."),
 "F6": ("E505", "Page 307", 5851, "mssEC 25 (obj 5952, pointer 5851), two telegrams, 3 Jan 1865: (1) Ft Monroe 7 PM, Sheldon to Beckwith for Capt. Howell, AQM, from Col. R. C. Webster: steamers all ready coaled and loaded with proper rations, the list stating capacity of each will be handed you; (2) City Point 9.30 PM, Beckwith to Sheldon: Gen. Rawlins wishes one of the going steamers sent to this place for other service, with a good supply of coal, no rations required (FM65-A; row 5851/1; transcription only)",
        S0 + "0.810 (47/58) / b 0.241 HIT (non-test). C: message (1) is printed OR I/46 pt 2 p.21: 'Fort Monroe, January 5 [3, OCR], 1865 -- 7 p. m. Capt. William T. Howell, Assistant Quartermaster: Steamers all ready coaled and loaded with proper rations. The list will be handed you, stating capacity, &c., of each. R. C. WEBSTER, Colonel.' -- word for word, time 7 PM agrees with the header, Are See = R. C. (Webster; H). Message (2) is not located (no clear copy: CISOSEARCHALL 'Webster Howell coaled loaded' 0 hits; phrase grep none): it is the only unprinted reading here. Filed with message (1) as C; the row is half in print, a verifier should class it so."),
 "F7": ("E506", "Page 308", 5852, "mssEC 25 (obj 5952, pointer 5852), 4 Jan 1865 City Point 1 PM, S. H. Beckwith to Sheldon at Ft Monroe, from Gen. Rawlins: wishes to know if the steamers named in your dispatch have started for this point yet; they have not been reported from Jamestown (FM65-A; row 5852/1; transcription only; about 25 words)",
        S0 + "1.000 (5/5) / b 0.800 HIT (window of 5 words, non-test). Short and mostly plain: clause = General Rawlins wishes to know if the steamers named in your dispatch have started yet for this point, they have not yet been reported from Jamestown; code meanings General, Steam, Report, signed (H); 'ran lines' = Rawlins is a plain misspelling the decoder leaves (M). Not a clear copy (CISOSEARCHALL 'Jamestown dispatch steamers Rawlins' 0 hits); not in print on the phrases searched. Kept because its sense fits the fleet of 5849-5851 and 5855; thin."),
 "F8": ("E507", "Page 308", 5852, "mssEC 25 (obj 5952, pointer 5852), two telegrams, 4 Jan 1865: (1) Ft Monroe 3 PM, Sheldon to Beckwith for Howell: all the steamers named had left here before 9 AM today, signed R. C. Webster, Col. QM; (2) Hd. Qrs. Army of the James 5 PM, R. O'Brien to Sheldon for Col. Webster: if the steamer Russia is at Monroe please send her here in time for a flag ship, by direction of Gen. Butler (FM65-A; row 5852/2; transcription only)",
        S0 + "0.594 (19/32) / b 0.250 HIT (non-test). M by hand: 'Dodge' decoded [McMinnville] and 'flag' decoded [11] are key rows misfiring on plain words (Col. Dodge, Butler's chief quartermaster, is in OR I/46 pt 2 p.24 on 3 Jan; the 'flag ship' reading is the sense of 'time for a flag ship'); Knave = Gen. Butler is H. Russia and Monroe: CISOSEARCHALL 'Russia flag ship' -> 5852 only; not in print on the phrases searched."),
 "F9": ("E508", "Page 309", 5853, "mssEC 25 (obj 5952, pointer 5853), 4 Jan 1865 Ft Monroe, Sheldon to Beckwith for Capt. Howell, AQM, from Webster: the C. C. Leary is just in and leaves immediately for City Point, she answers the description you required and has ten days' coal; if you can spare the Montauk we need her here (FM65-A; row 5853/1; transcription only; about 28 words)",
        S0 + "0.731 (19/26) / b 0.308 HIT (non-test). Codes read: City Point (blubber), ten (feeble), the signature; the rest is plain. The C. C. Leary is also in 5849/0, 5858 and 5854/0 (O'Brien: 'ordered to send the C. C. Leary and she has gone'), which fixes the ship and the date. CISOSEARCHALL 'Leary Montauk' -> 5853, 5854 (the sibling); not a clear copy; not in print on the phrases searched."),
 "F10": ("E509", "Page 310", 5854, "mssEC 25 (obj 5952, pointer 5854), 4 Jan 1865 Hd Qrs. Army of the James 5 PM, R. O'Brien to Sheldon for Col. Dodge: the Bendford is not here, the full list was sent to Gen. Butler this morning and Ainsworth has a copy; since then I have been ordered to send the C. C. Leary and she has gone; the Montauk is there, and if you need her telegraph Bradley at once; no other vessel here except the Alliance and the hospital boat Metropolis; the boats sent thus far fully comply with the orders of [Grant]; signed Sheldon (FM65-A; row 5854/0; transcription only)",
        S0 + "0.772 (44/57) / b 0.228 HIT (non-test). M by hand: 'Dodge' decoded [McMinnville] (plain name misfire, as E507); 'win Metropolis' and 'Wicoff' after 'hospital boat' unresolved ('[West]' is the decoder's); 'John Orcey' = Grant's orders (John = Grant is a key row, Orcey not read, M). Bradley = Col. Bradley, AQM at City Point (E504). The Leary sailing is stated in E508. CISOSEARCHALL 'Bendford Ainsworth Alliance' 0 hits; not in print on the phrases searched."),
 "F12": ("E511", "Page 311", 5855, "mssEC 25 (obj 5952, pointer 5855), 4 Jan 1865 City Point 5.30 PM, S. H. Beckwith to Sheldon at Ft Monroe, from Gen. Rawlins: two light-draft steamers, not over five feet, suitable for going with the other vessels and standing rough weather, will be required, to be held in readiness at Monroe, boats like the Eliza Hancox and the Winants will answer; a good supply of coal only is required; inform me whether these vessels [are available]; signed Howell (FM65-A; row 5855/2; transcription only)",
        S0 + "1.000 (4/4) / b 1.000 - (window of 4 words, no information; BOOK-FM65's wider window 0.862 / 0.231 HIT). The Eliza Hancox and the Winants are the dispatch boats named in 5856 (O'Brien/Sheldon, 4 Jan: 'The Eliza Hancox has already been sent ... The winants is hardly capable of going'). The Eliza Hancox appears in the Fisher expedition order (OR I/46 pt 2, p.90 index, the landing order text), not this telegram. CISOSEARCHALL 'Hancox Winants' -> 5855, 5856; not a clear copy; not in print on the phrases searched."),
}
txt = (HERE.parent/"ciphertext.txt").read_text(encoding="utf-8")
body = {}; cur = None
for ln in (HERE/"fm65a_entries.txt").read_text(encoding="utf-8").splitlines():
    if ln.startswith("### "): cur = ln.split()[1]; body[cur] = []; continue
    if cur and ln.strip(): body[cur].append(ln)
add = ""
for f, (eid, page, ptr, desc, note) in ROWS.items():
    if f"### {eid} |" in txt: continue
    add += f"### {eid} | {page} | {ptr} | {desc}\n" + "\n".join(body[f] + ["note: FM65-A: " + note + " Image not read (transcription only, rule 2); the BOOK (No. 1) is by sense and BOOK-FM65; not novelty-classified (rule 10)."]) + "\n\n"
if not add: print("already present")
elif "--dry" in sys.argv: print(add)
else: (HERE.parent/"ciphertext.txt").write_text(txt.rstrip("\n") + "\n\n" + add.rstrip("\n") + "\n", encoding="utf-8"); print("added", add.count("### E"))
