#!/usr/bin/env python3
"""FM-F1 (10 Oct 2026): file 11 of the 15 Fort Monroe rows that waves 1 decoded but held as step-0 skips (ruling for mssEC 25: a step-0 hit is a non-test)
into ../ciphertext.txt (Cipher No. 1): E441-E443, E445-E448, E466, E468-E470. Not filed: 5752/0 (in print), 5799/0, 5632/2, 5822/2 (too short for a clause).
Cipher lines come from fm_f1_entries.txt (copied unchanged from fm_r9/fm_s1/fm_s2_entries.txt). Transcription only (no image check). Usage: fm_f1_file.py [--dry]. Idempotent."""
import sys
from pathlib import Path
HERE = Path(__file__).resolve().parent; T = HERE.parent
def blocks():
    cur = None; out = {}
    for ln in (HERE/"fm_f1_entries.txt").read_text(encoding="utf-8").splitlines():
        if ln.startswith("### "): cur = ln.split("|")[0].replace("###", "").strip(); out[cur] = []; continue
        if cur and ln.strip(): out[cur].append(ln)
    return out
B = blocks()
S0 = "FM-F1 Step 0 (fm_f1_step0.py, run under No. 1; as information, a hit on mssEC 25 is a non-test): "
NP = " Transcription only (no image check). "
J = [
 ("E441", "Page 155 | 5699 | mssEC 25 (obj 5952, pointer 5699), 27 May 1864 Washington, T. T. Eckert to Sheldon at Ft Monroe (received): the operators should have reached Monroe, left Alexandria yesterday, boat probably delayed; your cipher received, suggestions good, will adopt the route after the General-in-Chief's opinion; how wide is the river at Yorktown, can a No. 14 wire be stretched across at that point or will it need cable; also how wide at West Point; dread the necessity of cables; chance for poles on the route (FM-F1, filed from FM-R9; row 5699/1)",
  S0 + "(a) 0.787 (48/61), (b) p95 0.213, HIT (shuffled-key copy 0.750 HIT). No. 1 H16: Monroe, Left, Alexandria, Cipher, General-in-Chief, River, Yorktown, 14, West Point, Point. The second width question ('how wide is [7 PM] [9] it [West Point]') is garbled by the decoder's time and number rows: M for 'how wide is it at West Point'. The clause is Eckert's cable-or-pole question for the Yorktown to West Point line; sense is the check (late May 1864 York River line). Holder CISOSEARCHALL (FM-F1, p16003coll11, all pointers, control 9678 returned): no clear copy, only its own pointer. Print: 177 cached volumes, four phrases, none; be-api whole-collection 'how wide is' Yorktown West Point: 10 hits, all Yorktown/West Point noise in OR vol. 27 (rejected, different text). Not located in print."),
 ("E442", "Page 163 | 5707 | mssEC 25 (obj 5952, pointer 5707), 27 May 1864 11.30 PM, Hd Qrs Genl Butler, R. O'Brien to Maj. Eckert (received): Butler must have an office at his Head Quarters, one at Gillmore's and one at the [Bermuda] landing, and wants City Point connected by cable; construction party to start tomorrow with Homan and Collings; party goes to Williamsburg via Jamestown Island; about one mile of cable to connect City Point (FM-F1, filed from FM-R9; row 5707/0)",
  S0 + "(a) 0.785 (51/65), (b) p95 0.215, HIT (shuffled-key copy 0.773 HIT). No. 1 H9: Maj Gen B. F. Butler, Head Quarters, Gen Q. A. Gillmore, City Point, Williamsburg. 'White River landing' is the decoder's slip for the Bermuda landing (the E313 type, M: the cipher word reads White River in the key but Bermuda Hundred is the place); 'Williamsburg' for the party's destination is M (single occurrence). Same day and subject as E441 (5699/1, Eckert's question). Holder CISOSEARCHALL (FM-F1): no clear copy. Print: 177 cached volumes, four phrases, none; be-api whole-collection (O'Brien, Gillmore, Jamestown island, one mile of cable): 0. Not located in print."),
 ("E443", "Page 241 | 5785 | mssEC 25 (obj 5952, pointer 5785), 1 Oct 1864 Ft Monroe, Sheldon to John Horner, New York, for Surgeon Charles McDougall: yellow fever is prevailing to considerable extent at Newbern, N.C.; I have thought best to notify you at once; E. McClellan (FM-F1, filed from FM-S1; row 5785/1; image-read at 2400 px by FM-S1)",
  S0 + "(a) 0.741 (20/27), (b) p95 0.370, HIT (shuffled-key copy 0.731 HIT). No. 1 H8: the address Maj Genl Grant (an address-line artefact, M), Monroe, 11 AM, 1, New York, 13, Newbern. flora = Newbern is the same key word as E280 (30 Sept, sibling on the page); 'Yell oh [13]' is yellow fever with 13 for fever (M for the sense). Page image of 5785 read by FM-S1: lines match the transcription. Holder CISOSEARCHALL (FM-S1, all pointers): only 5785. Print: 177 cached volumes none; be-api whole-collection (FM-S1 and FM-F1 queries): one phrase hit, 'yellow fever is prevailing to considerable extent in Vera Cruz', Illinois State Register 1846 (different text and year, rejected). Not located in print."),
 ("E445", "Page 272 | 5816 | mssEC 25 (obj 5952, pointer 5816), 6 Dec 1864 Butler's Hd Qrs, R. O'Brien to Sheldon at Ft Monroe (received), 6 PM, for D. D. Porter: Mr Baird will arrive tomorrow morning on the City of Hendron; please have him sent here with his instruments (FM-F1, filed from FM-S1; row 5816/2; image-read at 2400 px by FM-S1)",
  S0 + "(a) 0.783 (18/23), (b) p95 0.348, HIT (shuffled-key copy 0.818 HIT). No. 1 H7: 6 PM, D. D. Porter, Tomorrow, Maj Gen B. F. Butler (sign-off position, M), 'furies' unread, 'sly will arrive at appear whelp' unread. Baird with instruments reads as a telegraph operator; the address to Porter and the ship name are M. Page image of 5816 read by FM-S1: lines match. Holder CISOSEARCHALL (FM-S1): only 5816. Print: 177 cached volumes none; be-api whole-collection: 0. Not located in print."),
 ("E446", "Page 39 | 5583 | mssEC 25 (obj 5952, pointer 5583), 12 Mar 1864 Ft Monroe, Sheldon to Maj. Eckert: General Butler desires to know if the operator at Cherrystone is the same W. A. Dunn formerly employed in the American office at Baltimore; answer quick; I don't know the reason (FM-F1, filed from FM-S1; row 5583/2)",
  S0 + "(a) 0.846 (22/26), (b) p95 0.385, HIT (shuffled-key copy 0.786 HIT). No. 1 H4: Maj Gen B. F. Butler, Humboldt (M: the decoder reads the plain place name Cherry as Humboldt; Cherrystone is meant, sibling pointers 11330 and 14048 write Cherrystone), Baltimore. 'Wrangler' for operator is plain on the page. Probably the same Dunn as 5638/0 (E466, 29 Apr: Butler returns the inquiry; M). Holder CISOSEARCHALL (FM-S1, all pointers): siblings only (11330, 14048, 12487), no clear copy of this telegram. Print: 'Cherry Stone' occurs in cached volumes, none with this telegram; be-api whole-collection: 0. Not located in print." + NP),
 ("E447", "Page 283 | 5827 | mssEC 25 (obj 5952, pointer 5827), 10 Dec 1864 City Point, S. H. Beckwith to Sheldon at Ft Monroe (received), for D. D. Porter: U.S.S. Saugus, six miles above City Point; telegram just received, will start down at [daylight?] tomorrow; E. R. Cole, Commander; 11 PM (FM-F1, filed from FM-S1; row 5827/0)",
  S0 + "(a) 0.667 (14/21), (b) p95 0.333, HIT (shuffled-key copy 0.667 HIT). No. 1 H11: Saugus line 6 miles above City Point, D. D. Porter, Telegraph (-ed), Tomorrow, 9.30 PM, 11 PM, Commander. 'early delight' is unread (M; 'at early [light]' is the sense); the signature 'E. R. Cole' and 'hound' for Commander are M. Sibling 5813 (antecedent). Holder CISOSEARCHALL (FM-S1): only 5827. Print: 'U S S Saugus' in OR ser. I vol. 10 ORN, not this telegram; be-api whole-collection (Saugus, above City Point, will start down): 0. Not located in print." + NP),
 ("E448", "Page 249 | 5793 | mssEC 25 (obj 5952, pointer 5793), 15 Oct 1864 Washington, T. T. Eckert to Dealy at Ft Monroe (received): don't fail to be at the wharf when the Manhattan arrives from Washington with the Secretary of War on board; don't mention his coming to anyone; presume Bates has posted you fully (FM-F1, filed from FM-S1; row 5793/1)",
  S0 + "(a) 0.810 (17/21), (b) p95 0.429, HIT (shuffled-key copy 0.850 HIT). No. 1 H3: Washington, Secretary of War (two code meanings), Today (M: the decoder reads the word before 'when the man hattan' as Today; 'at the wharf' is the sense and is not a key row). Thin: one connected clause with two code meanings, no sibling to test the sense (Stanton's movements of 15 Oct 1864 not read). Holder CISOSEARCHALL (FM-S1, all pointers): no clear copy. Print: 177 cached volumes none; be-api whole-collection (Manhattan, Secretary of War, wharf, Dealy): 0. Not located in print." + NP),
 ("E466", "Page 94 | 5638 | mssEC 25 (obj 5952, pointer 5638), 29 Apr 1864 Ft Monroe, Sheldon to Maj. Eckert: I referred your telegram about Dunn to General Butler; he returns it endorsed 'I know of none and do not believe a word against him'; appears settled (FM-F1, filed from FM-S2; row 5638/0)",
  S0 + "(a) 0.800 (16/20), (b) p95 0.400, HIT (shuffled-key copy 0.762 HIT). No. 1 H4: Telegraph (-ed) for wrangle, Maj Gen B. F. Butler for Knox, the quotation marks for violet and virgin. The clause is mostly plain; the key supplies who and what was referred (M for the identity of Dunn, the operator of E446). Holder CISOSEARCHALL (FM-S2, all pointers): no clear copy. Print: 164 cached volumes none; be-api whole-collection (FM-S2 and FM-F1): 0. Not located in print." + NP),
 ("E468", "Page 266 | 5810 | mssEC 25 (obj 5952, pointer 5810), 28 Nov 1864 City Point, S. H. Beckwith to Sheldon at Ft Monroe (received), for Butler: [if so] I will meet you [at Monroe] tomorrow at 10.30 AM and the Admiral there at 3 PM; about (FM-F1, filed from FM-S2; row 5810/1)",
  S0 + "(a) 0.667 (10/15), (b) p95 0.400, HIT (shuffled-key copy 0.588 HIT). No. 1 H8: Maj Gen B. F. Butler, 10.30 AM, Monroe, Tomorrow, 3 PM, Maj Genl Grant (sign-off position, M). WEAK: the clause turns on 'beat' = Monroe and 'Alday' = Tomorrow (single occurrences), 'Monday miller' and 'Elizabeth' unread; 'the admire' is read as the admiral by sense only (M). Holder CISOSEARCHALL (FM-S2): no clear copy. Print: 164 cached volumes none; be-api whole-collection: 0. Not located in print." + NP),
 ("E469", "Page 176 | 5720 | mssEC 25 (obj 5952, pointer 5720), 30 May 1864 7.30 PM, Gen Butler's Hd Qrs, R. O'Brien to Maj. Eckert (received): private; I hear heavy and continuous firing about 15 miles from here in the direction of the battery; it may be that Grant has reached there (FM-F1, filed from FM-S2; row 5720/0)",
  S0 + "(a) 0.684 (13/19), (b) p95 0.368, HIT (shuffled-key copy 0.684 HIT). No. 1 H6: 7.30 PM, 20 (M, unplaced), 15 (miles), Bridge (-ed) (M: the decoder prints the word after 'battery' as a verb ending; the place is not read), Maj Genl Grant (H, M for the sense: Grant at the front on 30 May 1864 reads, but the single occurrence has no corroboration here). Holder CISOSEARCHALL (FM-S2): no clear copy (siblings on 5720 are other telegrams). Print: 'heavy and continuous firing' in OR vols 32 and 43 cached text, other telegrams; be-api whole-collection: 0. Not located in print." + NP),
 ("E470", "Page 270 | 5814 | mssEC 25 (obj 5952, pointer 5814), 1 Dec 1864 8 AM, Butler's Hd Qrs, R. O'Brien to Sheldon at Ft Monroe (received), for D. D. Porter: your telegram received; the three monitors Mahopac, Canonicus and Saugus are ready for service; Commander Parker (FM-F1, filed from FM-S2; row 5814/0)",
  S0 + "(a) 0.800 (12/15), (b) p95 0.467, HIT (shuffled-key copy 0.800 HIT). No. 1 H8: 8 AM, D. D. Porter, Telegraph (-ed), 3, Commander. The monitor names are plain on the page; the signature 'Commander Parker' is M. Antecedent: pointer 5813 (cipher copy, not a clear copy); sibling E474 (13 Dec) concerns the same fleet. Holder CISOSEARCHALL (FM-S2): no clear copy. Print: be-api whole-collection returned Porter's 28 Nov 1864 'Move the Saugus and Canonicus up to Dutch Gap' (ORN ser. I vol. 11) and a modern monitor history, both different texts (rejected); this telegram not located." + NP),
]
dry = "--dry" in sys.argv; fn = T/"ciphertext.txt"; txt = fn.read_text(encoding="utf-8")
row = {"E441":"5699/1","E442":"5707/0","E443":"5785/1","E445":"5816/2","E446":"5583/2","E447":"5827/0","E448":"5793/1","E466":"5638/0","E468":"5810/1","E469":"5720/0","E470":"5814/0"}
for eid, desc, note in J:
    if f"### {eid} |" in txt: print("already present", eid); continue
    add = f"### {eid} | {desc}\n" + "\n".join(B[eid] + ["note: " + note]) + "\n"
    txt = txt.rstrip("\n") + "\n\n" + add; print(("would add " if dry else "added ") + eid)
if not dry: fn.write_text(txt, encoding="utf-8")
