#!/usr/bin/env python3
"""FM-S65A: file the six Fort Monroe 1865 rows of fms65a_entries.txt that carry a clause (E581 E582 E583 E585 E586 E587) into ../ciphertext.txt.
Not filed: F1 5845/2 (E578, too short), F2 5857/2 (E579, in print OR I/46 pt 2 p.38), F3 5858/2 (E580, too short), F7 5872/1 (E584, plain),
F11 5892/0 (E588, holder clear copy 8558 and in print OR I/46 pt 2 p.510). IDs follow the brief's fixed block (E578 = F1 ... E588 = F11).
Usage: python3 fms65a_file.py [--dry]  Idempotent."""
import sys
from pathlib import Path
HERE = Path(__file__).resolve().parent
S0 = "FM-S65A step 0 (fms65a_step0.py; information only, a non-test on this ledger per the wave-2 RULING and BOOK-FM65): "
CTL = " Shuffled-key control (fms65a_ctl.out, BOOK-FM65 seeds 1-3): "
ROWS = {
 "F4": ("E581", "Page 318", 5862, "mssEC 25 (obj 5952, pointer 5862), 6 Jan 1865 Ft Monroe, Sheldon to S. H. Beckwith at City Point: the River Queen left about 11 AM today with Gen. Butler on board; the Colonel told me he had gone up the James and that he himself was going the same way immediately; signed Geo. D. Sheldon (FM-S65A; row 5862/0; read from the transcription, no image)",
        S0 + "0.720 (18/25) / b 0.280 HIT. 'River queen left about', 'told me he had gown up', 'that himself was going same way' are plain; 'Knave' = Gen. Butler, 'pandora' = Colonel, 'Bergen' = James, 'wedge' = today are code readings (H); 'Fanny' (before 'wedge') and 'gown' (sic, gone) are M." + CTL + "the three shuffled copies give 'with [Heavy] on board', 'told me he had gown up [Attack]' / '[C. A. Dana]' / '[Pontoon]': the Butler / James clause does not survive any of them. Holder: CISOSEARCHALL 'River Queen Sheldon himself same way' -> 5862 itself only, two other queries 0 hits; not a clear copy. Print: phrase grep of 211 volumes none; Grant Papers 14 (be-api) 0 hits."),
 "F5": ("E582", "Page 318", 5862, "mssEC 25 (obj 5952, pointer 5862), 6 Jan 1865 City Point 8.30 PM, S. H. Beckwith to Sheldon at Ft Monroe, from Grant for the Secretary of War at Monroe: [a name, unread 'Melan'] or Ord either will be good [men] to relieve Gen. Foster (FM-S65A; row 5862/2; read from the transcription, no image)",
        S0 + "0.565 (13/23) / b 0.304 HIT. Key words (H): Secretary of War, Monroe, Ord, Foster, Grant, two, six; 'Melan', 'wilby', 'spit' (read [Men]) and 'peach' are M or unread. Thin: one clause, with a garbled middle." + CTL + "'for [Monroe] [Help]. Melan or [Repulsed] either wilby good', 'relieve [South]' (s1), '[Fortifications] ... relieve [Kingsport]' (s2), '[Parke] ... relieve [Surprise]' (s3): the Ord / Foster clause does not survive. Context in print (not this message): Halleck to Grant 6 Feb 1865, OR I/46 pt 2: 'General Ord is assigned, as requested ... General Gillmore had been sent South to relieve General Foster'. Holder: CISOSEARCHALL three queries (Ord Foster relieve ...) 0 hits; Grant Papers 14 (be-api) 0 hits; phrase grep 'to relieve General Foster' hits only that Feb 6 telegram and older volumes."),
 "F6": ("E583", "Page 328", 5872, "mssEC 25 (obj 5952, pointer 5872), 13 Jan 1865 Ft Monroe 8 PM, Sheldon to S. H. Beckwith at City Point, for Brig. Gen. Rawlins, Chief of Staff: [an unread word 'weasler'] the Illinois goes to sea at 11 o'clock with 1200 and 87 [men]; all right; signed Morgan (FM-S65A; row 5872/0; read from the transcription, no image)",
        S0 + "0.542 (13/24) / b 0.292 HIT. Thin: the clause is mostly plain ('Illinois goes to see at ... o'clock with ... all right') and the three numbers (11, 1200, 87) read the same under every shuffled copy, so the control does not separate the book here; only 'Brigadier General', 'Chief of Staff' and 'Men' are key words (H, and sense-checked: the numbers are followed by a plural noun). 'weasler' and 'forbid William and Mother postpone' (the cipher words read as numbers) are M." + CTL + "'for [Rome] Rawlins [Galveston]', 'with 1200 and 87 [Fortifications]' (s1), '[Roddy]' (s2), '[Detach]' (s3). Print context (not this message): the Illinois, Victor and Ashland loaded and under orders to sail, Newport to Thomas 12 Jan 11.30 a.m., OR I/46 pt 2. Holder: three queries (Illinois Morgan Rawlins 1200 ...) 0 hits; Grant Papers 14, whole-collection be-api 0 hits."),
 "F8": ("E585", "Page 328", 5872, "mssEC 25 (obj 5952, pointer 5872), 15 Jan 1865 Ft Monroe 9.30 AM, Sheldon to S. H. Beckwith at City Point, for Brig. Gen. Rawlins, Chief of Staff, from Hd. Qrs. 2nd Division, 19th Corps: the division has but 40 rounds of ammunition, shall I take more; C. Grover, Bvt. Maj. Gen., commanding (FM-S65A; row 5872/2; read from the transcription, no image)",
        S0 + "0.423 (11/26) / b 0.231 MISS (a window of 2 blocks; information only). Key words (H): Head Quarters, 2, Division, 19, Corps, Brigadier General, Chief of Staff, 40, Ammunition, Major, General; 'Grover' and 'Shall I take more' are plain; 'polking' (commanding) is M; 'Eugenia Snake' and the unread 'quitman hope pelton' are the cipher words for the headquarters line." + CTL + "'[Ammunition] [2] [Marmaduke] [19] [Tuscaloosa] for [D. D. Porter] ... [Maj Gen B. M. Prentiss] has but 40 rounds of [Louisville]' (s1) and the other two: the headquarters / division / corps / ammunition clause does not survive; only the numbers 2, 19 and 40 do. Answer: E586 (the same afternoon). Holder: three queries (Grover rounds ammunition ...) 0 hits; print: phrase grep of 211 volumes and be-api (whole collection, Grant Papers 14) 0 hits."),
 "F9": ("E586", "Page 330", 5874, "mssEC 25 (obj 5952, pointer 5874), 15 Jan 1865 City Point 3.30 PM, S. H. Beckwith to Sheldon at Ft Monroe, from Rawlins: Bvt. Maj. Gen. Grover's 40 rounds of ammunition will answer, you need not wait to get more (FM-S65A; row 5874/1; read from the transcription, no image; about 16 words)",
        S0 + "0.733 (11/15) / b 0.400 HIT (window of 1 block, thin). Key words (H): Major, General, 40, Ammunition; the rest is plain. Thin, filed with E585, whose question it answers ('Shall I take more' / 'you needn't wait to get more')." + CTL + "'Brevet [Defense] [Schofield] Grovers 40 rounds of [Louisville]' (s1) and the other two: the ammunition clause does not survive. Holder: three queries 0 hits; print: none."),
 "F10": ("E587", "Page 339", 5883, "mssEC 25 (obj 5952, pointer 5883), 21 Jan 1865 Washington 3 PM, T. T. Eckert to Sheldon at Ft Monroe, for Gen. Palmer: wait at Monroe until I get there; I will leave [a place unread] at 5 AM tomorrow; signed Eckert (FM-S65A; row 5883/2; read from the transcription, no image; answers Palmer's own 1 PM telegram of 21 Jan from Ft Monroe, holder pointer 7718, p.60)",
        S0 + "0.474 (9/19) / b 0.316 MISS (window of 3 blocks; information only). Key words (H): Washington, 21, Monroe, Tomorrow, Grant; 'Gen J. M. Palmer' is the key's reading (the antecedent at 7718 is signed J. W. Palmer, Br Gen Comdg Dist of NC: M for the initial); 'Sumter' for the plain-word slot after 'will lave an' and 'Cora whelp John' are M. Support (C): 7718 (Palmer at Ft Monroe 1 pm 21 Jan, come from Newbern to consult Gen Grant; 'As the Lieut Genl is in Washn I would beg you to enquire whether he desires to see me and whether I had better wait here until his return') reads as the telegram this row answers." + CTL + "'for [Maj Gen Geo. H. Thomas] wait at [Help] until I get there' (s1), '[Hill] ... wait at [Pearl]' (s2), '[Maj Gen B. F. Butler] wait at [Maj Genl U.S. Grant]' (s3): the Palmer / Monroe clause does not survive. Holder: CISOSEARCHALL 'Eckert wait Monroe Palmer tomorrow' -> 7718 (the antecedent) only, two other queries 0 hits: not a clear copy of this reply; print: none (OR I/46 pt 2 and 3, Grant Papers 14 via be-api 0 hits)."),
}
txt = (HERE.parent/"ciphertext.txt").read_text(encoding="utf-8")
body = {}; cur = None
for ln in (HERE/"fms65a_entries.txt").read_text(encoding="utf-8").splitlines():
    if ln.startswith("### "): cur = ln.split()[1]; body[cur] = []; continue
    if cur and ln.strip(): body[cur].append(ln)
add = ""
for f, (eid, page, ptr, desc, note) in ROWS.items():
    if f"### {eid} |" in txt: continue
    add += f"### {eid} | {page} | {ptr} | {desc}\n" + "\n".join(body[f] + ["note: FM-S65A: " + note + " Image not read (transcription only, rule 2); the BOOK (No. 1) is by sense and BOOK-FM65; not novelty-classified (rule 10)."]) + "\n\n"
if not add: print("already present")
elif "--dry" in sys.argv: print(add)
else: (HERE.parent/"ciphertext.txt").write_text(txt.rstrip("\n") + "\n\n" + add.rstrip("\n") + "\n", encoding="utf-8"); print("added", add.count("### E"))
