#!/usr/bin/env python3
"""Worklist for the image check of the --split-check hits (SPLIT-matignon-mayenne-1586, 2 Oct 2026, account-4).

Reads this target's rows from ciphers/_triage/split-check-1-Oct-2026.tsv and key.tsv, classifies every flagged
token, and writes split_worklist.tsv (one row per token label), ranked as the brief ranks them: tokens whose every
part is a key code first (a real split candidate), then tokens with one keyed part (a compound label), then labels
absent from the key with no split at all. `image_on_disk` is whether any of the token's leaves has an image under
images/ (2 Oct 2026: only fr.3974 f.24, fr.15572 f.78v/79r and fr.15571 f.179 are on disk, none of the 13 Cipher-1
leaves). Report only: it writes no reading, no correction and changes nothing in key.tsv or ciphertext.txt.

    python3 ciphers/matignon-mayenne-1586/split_worklist.py            # writes split_worklist.tsv beside it
    python3 ciphers/matignon-mayenne-1586/split_worklist.py --check    # exit 1 if the committed TSV is stale
"""
import csv, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
TRIAGE = os.path.join(ROOT, "ciphers", "_triage", "split-check-1-Oct-2026.tsv")
TARGET = "matignon-mayenne-1586"
LEAVES_IMAGED = set()  # none of f110, f123r, f123v, f124r, f124v, f143r, f143v, f150, f154, f173, f196, f201, fr15571-f177

def load_key():
    key = {}
    with open(os.path.join(HERE, "key.tsv"), encoding="utf-8") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            key[row["code"]] = (row["value"], row.get("grade") or "H")
    return key

def splits(tok, key):
    """Every cut of tok into 2 or 3 consecutive key codes (exact strings)."""
    out = []
    n = len(tok)
    for i in range(1, n):
        a, b = tok[:i], tok[i:]
        if a in key and b in key:
            out.append((a, b))
        for j in range(i + 1, n):
            a, b, c = tok[:i], tok[i:j], tok[j:]
            if a in key and b in key and c in key:
                out.append((a, b, c))
    return out

def partial_splits(tok, key):
    """Two-way cuts where exactly one side is a key code (a compound label, half keyed)."""
    out = []
    for i in range(1, len(tok)):
        a, b = tok[:i], tok[i:]
        if (a in key) != (b in key):
            other = b if a in key else a
            if len(other) <= 2 or other.isdigit():   # the unkeyed side must itself look like a label (BOX|2, not B|OX2)
                out.append((a, b))
    return out

def fmt(parts, key):
    return ";".join("|".join(parts) + "=" + " ".join(key[p][0] if p in key else "?" for p in parts) for parts in parts)

def build():
    key = load_key()
    rows = []
    with open(TRIAGE, encoding="utf-8") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            if r["target"] != TARGET:
                continue
            tok = r["token"]; n = int(r["n"]); pos = r["positions"].split(",")
            leaves = sorted({p.rsplit("-", 1)[0] for p in pos})
            full = splits(tok, key); part = partial_splits(tok, key)
            if full:
                kind, rank = "digit-split" if tok.isdigit() else "sign-split", 1
                parts = fmt(full, key)
            elif part:
                kind, rank, parts = "compound-label", 2, fmt(part, key)
            else:
                kind, rank, parts = "absent-label", 3, "-"
            imaged = "yes" if any(l in LEAVES_IMAGED for l in leaves) else "no"
            rows.append(dict(rank=rank, token=tok, n=n, kind=kind, parts=parts, leaves=" ".join(leaves),
                             first_positions=" ".join(pos[:3]), image_on_disk=imaged,
                             verdict="not reached: no image on disk" if imaged == "no" else "unchecked"))
    rows.sort(key=lambda d: (d["rank"], -d["n"], d["token"]))
    return rows

def render(rows):
    cols = ["rank", "token", "n", "kind", "parts", "leaves", "first_positions", "image_on_disk", "verdict"]
    lines = ["# split_worklist.tsv -- SPLIT-matignon-mayenne-1586, 2 Oct 2026 (account-4); regenerated by split_worklist.py from "
             "ciphers/_triage/split-check-1-Oct-2026.tsv + key.tsv; a report, not a reading (rule 7 --check applies to staleness only)",
             "\t".join(cols)]
    for d in rows:
        lines.append("\t".join(str(d[c]) for c in cols))
    return "\n".join(lines) + "\n"

if __name__ == "__main__":
    out = os.path.join(HERE, "split_worklist.tsv")
    text = render(build())
    if "--check" in sys.argv:
        old = open(out, encoding="utf-8").read() if os.path.exists(out) else ""
        print("split_worklist.tsv", "current" if old == text else "STALE")
        sys.exit(0 if old == text else 1)
    open(out, "w", encoding="utf-8").write(text)
    rows = build()
    from collections import Counter
    print(f"{len(rows)} token labels, {sum(r['n'] for r in rows)} occurrences;", dict(Counter(r['kind'] for r in rows)),
          "; image on disk:", dict(Counter(r['image_on_disk'] for r in rows)))
