#!/usr/bin/env python3
"""Render mssDE 68's OWN contemporary ink decipherment as a plain-text transcription (NOT a solve: every
group on this leaf already carries its own interlinear French gloss in ink, per NOTES.md 'R6 progress').

  python3 build_reading_68.py           write reading_68.txt
  python3 build_reading_68.py --check   exit 1 if the committed file differs from a regeneration (rule 7)

Reads pairs_contemporary.tsv (item, page, line, pos, group, gloss, hand, struck, grade), filters to item mssDE68,
and joins each line's glosses in group order: a struck gloss in [x: ...], 'nul' kept as [nul] (the decipherer's own
null marker), a doubtful gloss keeps its '?'. Grade counts (C/M) are reported in the header, matching key.tsv's
grading rule (an ink gloss without doubt is C, known plaintext; struck/doubtful/'?' is M).
"""
import csv, sys, os, io
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
P = lambda f: os.path.join(HERE, f)


def build():
    lines = OrderedDict()
    counts = {'C': 0, 'M': 0}
    with open(P('pairs_contemporary.tsv')) as f:
        for r in csv.DictReader(f, delimiter='\t'):
            if r['item'] != 'mssDE68':
                continue
            key = (r['page'], r['line'])
            lines.setdefault(key, []).append(r)
            counts[r['grade']] = counts.get(r['grade'], 0) + 1
    out = io.StringIO()
    total = sum(counts.values())
    out.write(f'# mssDE 68 (31 Jan 1781), transcription of its own contemporary ink interlinear decipherment.\n')
    out.write(f'# Not a solve: the archive already carries this reading beside the cipher (NOTES.md, R6 progress).\n')
    out.write(f'# Generated by build_reading_68.py from pairs_contemporary.tsv; do not edit.\n')
    out.write(f'# tokens {total}: C {counts.get("C", 0)}, M {counts.get("M", 0)}\n')
    for (page, ln), rows in lines.items():
        toks = []
        for r in rows:
            g = r['gloss']
            if r['struck'] == '1':
                g = f'[x:{g}]'
            toks.append(g)
        out.write(f'{page} {ln}\t' + ' '.join(toks) + '\n')
    return out.getvalue()


def main():
    s = build()
    target = P('reading_68.txt')
    if '--check' in sys.argv:
        if not os.path.exists(target) or open(target).read() != s:
            print('stale: reading_68.txt', file=sys.stderr)
            sys.exit(1)
        print('ok: reading_68.txt up to date')
        return
    open(target, 'w').write(s)
    print('wrote reading_68.txt')


if __name__ == '__main__':
    main()
