#!/usr/bin/env python3
"""Per-line crops for the plain-Italian boxes only (SALV-PLAIN1, 26 Sept 2026): usage crop_plain_leaf.py <leaf>.

Sibling of crop_passC_leaf.py, but reads only line/pos/code from ciphertext_<leaf>.tsv (never the passA/passB
code column for a sign box, since this job never decodes signs) and coordinates from <leaf>_boxes.tsv. Unlike
crop_passC_leaf.py (one crop per disagreement, at box-crop resolution from glyphs/crops/<leaf>.png, which no
longer exists on disk -- deleted by bSALS), this crops one image per manuscript line, full line width, from the
high-resolution renders regenerated by regen_images.sh + the 2400px fetches (U0 of the SALV-PLAIN1 brief):
  f54r: images/src_ark_12148_btv1b90600674_f55_4085_0_4086_5513.jpg, box (x,y) -> source pixel (x+250, y+650), scale 1
  f54v/f55r/f55v: images/<leaf>_ref2400.jpg, box (x,y) -> source pixel ((x+80)*1.5, (y+80)*1.5), scale 1.5
A split pos like 8.5 shares its integer parent box (crop_passC_leaf.py's convention): grouped under the parent's
coordinates here since this script marks boxes, not signs.

Under each PLAIN box only (code == '_' in ciphertext_<leaf>.tsv), in the margin below the ink, draws a thin
underline and its pos number; sign boxes (code != '_') get no mark, so a pass never sees which box the
solver's own transcription assigned a sign to. Downscales to at most 2400 px wide, uniformly, if a line's
native crop is wider (never draws over the ink -- the annotation band is a separate strip below the crop).

Output: plain_crops/<leaf>/L<nn>.png (one per manuscript line) + plain_crops/<leaf>/manifest.tsv
  (line, file, plain_pos_list, render, scale)

  python3 crop_plain_leaf.py f54r

Per-box mode (LANE SALV2, 27 Sept 2026, for the blind code+mark passes on SALV-SPLIT's confirmed boxes):
  python3 crop_plain_leaf.py f56r --boxes LIST.tsv --out DIR --seed N [--leaf-col]
LIST.tsv has header columns line, pos (and leaf, if --leaf-col: then one crop set may span several leaves, e.g.
f56r+f56v). For each listed box, cuts from the same render and transform one crop with about one box-width of
context left/right and 1.5 box-heights above (marks sit above the sign) and 0.6 below, draws a thin blue rectangle
round the target box only, upscales so the crop is about 400 px high, never wider than 2500 px, and saves it as
DIR/cNNN.png in an order shuffled by --seed. The opaque id -> (leaf, line, pos) map goes to DIR/../<basename>_key.tsv,
outside DIR, so a subagent given DIR never sees it. No plain/sign annotation is drawn.

  python3 crop_plain_leaf.py f56v --boxes LIST.tsv --out DIR --seed N [--leaf-col] --neighbors K
SALV-F56V, 27 Sept 2026: same as above, but widens the crop to span K whole neighbouring boxes each side of the
target (same manuscript line only, clipped at the line's own ends), not just the default box-width padding. Each
neighbour box gets the line-crop-mode underline + pos-number label (main()'s own convention) so the reader can
tell target from context; the target keeps its blue rectangle and no number label (already unambiguous by being
the only rectangle). Written because SALV2-J3's own U1 asked for "the two neighbouring boxes each side" on
harder single-box calls, and the plain default context (about one box-width) is not that.
"""
import csv, os, sys
from PIL import Image, ImageDraw, ImageFont

LEAF = sys.argv[1] if len(sys.argv) > 1 and not sys.argv[1].startswith("-") else None
if LEAF is None or "-h" in sys.argv or "--help" in sys.argv:
    print(__doc__); sys.exit(0)
OUT = f"plain_crops/{LEAF}"
MAX_W = 2400
FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

SOURCES = {
    "f54r": ("images/src_ark_12148_btv1b90600674_f55_4085_0_4086_5513.jpg", 250, 650, 1.0),
    "f54v": ("images/f54v_ref2400.jpg", 80, 80, 1.5),
    "f55r": ("images/f55r_ref2400.jpg", 80, 80, 1.5),
    "f55v": ("images/f55v_ref2400.jpg", 80, 80, 1.5),
    "f56r": ("images/f56r_ref2400.jpg", 80, 80, 1.5),
    "f56v": ("images/f56v_ref2400.jpg", 80, 80, 1.5),
    "f57r": ("images/f57r_ref2400.jpg", 80, 80, 1.5),
    "f57v": ("images/f57v_ref2400.jpg", 80, 80, 1.5),
}


def load_boxes(leaf):
    boxes = {}  # (line, int_pos) -> (x, y, w, h)
    with open(f"{leaf}_boxes.tsv") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            line = int(r["line"])
            pos = int(float(r["pos"]))
            boxes[(line, pos)] = (int(r["x"]), int(r["y"]), int(r["w"]), int(r["h"]))
    return boxes


def load_codes(leaf):
    # line -> list of (pos_float, code) in reading order
    rows = {}
    with open(f"ciphertext_{leaf}.tsv") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            line = int(r["line"])
            rows.setdefault(line, []).append((float(r["pos"]), r["code"]))
    for line in rows:
        rows[line].sort(key=lambda t: t[0])
    return rows


def main():
    src_path, off_x, off_y, scale = SOURCES[LEAF]
    im = Image.open(src_path)
    W, H = im.size
    boxes = load_boxes(LEAF)
    codes = load_codes(LEAF)
    font = ImageFont.truetype(FONT_PATH, 34)

    os.makedirs(OUT, exist_ok=True)
    manifest = []
    for line in sorted(codes):
        entries = codes[line]  # (pos_float, code)
        int_positions = sorted(set(int(p) for p, _ in entries))
        # native-frame bbox across every box on this line (plain + sign, so context words aren't cropped away)
        xs0, ys0, xs1, ys1 = [], [], [], []
        for ip in int_positions:
            if (line, ip) not in boxes:
                continue
            x, y, w, h = boxes[(line, ip)]
            sx0, sy0 = (x + off_x) * scale, (y + off_y) * scale
            sx1, sy1 = (x + w + off_x) * scale, (y + h + off_y) * scale
            xs0.append(sx0); ys0.append(sy0); xs1.append(sx1); ys1.append(sy1)
        if not xs0:
            continue
        pad_x, pad_y = 20 * scale, 10 * scale
        band_h = 45 * scale  # annotation strip below the ink, in native crop pixels
        x0 = max(0, int(min(xs0) - pad_x))
        y0 = max(0, int(min(ys0) - pad_y))
        x1 = min(W, int(max(xs1) + pad_x))
        y1 = min(H, int(max(ys1) + pad_y + band_h))
        crop = im.crop((x0, y0, x1, y1)).convert("RGB")
        draw = ImageDraw.Draw(crop)

        plain_pos = []
        for pos_f, code in entries:
            ip = int(pos_f)
            if code != "_":
                continue
            if pos_f != ip:
                continue  # split positions share the parent box's single mark
            if (line, ip) not in boxes:
                continue
            plain_pos.append(ip)
            x, y, w, h = boxes[(line, ip)]
            sx0, sy0 = (x + off_x) * scale - x0, (y + off_y) * scale - y0
            sx1 = (x + w + off_x) * scale - x0
            box_bottom = (y + h + off_y) * scale - y0
            bottom = box_bottom + 8 * scale  # hug this box's own bottom edge, not the line's lowest box
            draw.line([(sx0, bottom), (sx1, bottom)], fill=(200, 0, 0), width=max(2, int(3 * scale)))
            label = str(ip)
            tw = draw.textlength(label, font=font)
            draw.text((max(x0 and 0, (sx0 + sx1) / 2 - tw / 2), bottom + 6 * scale), label, fill=(200, 0, 0), font=font)

        if crop.width > MAX_W:
            r = MAX_W / crop.width
            crop = crop.resize((MAX_W, int(crop.height * r)), Image.LANCZOS)
            out_scale = scale * r
        else:
            out_scale = scale

        fname = f"{OUT}/L{line:02d}.png"
        crop.save(fname)
        manifest.append((line, fname, ",".join(str(p) for p in plain_pos), os.path.basename(src_path), f"{out_scale:.4f}"))

    with open(f"{OUT}/manifest.tsv", "w") as f:
        f.write("line\tfile\tplain_pos\trender\tscale\n")
        for row in manifest:
            f.write("\t".join(str(c) for c in row) + "\n")

    total_plain = sum(len(r[2].split(",")) for r in manifest if r[2])
    print(f"{LEAF}: {len(manifest)} line crops -> {OUT}/, manifest {OUT}/manifest.tsv, {total_plain} plain boxes marked")


def boxes_mode(list_path, out_dir, seed, leaf_col, neighbors=0):
    import random
    items = []
    with open(list_path) as f:
        for r in csv.DictReader(f, delimiter="\t"):
            leaf = r["leaf"] if leaf_col else LEAF
            items.append((leaf, int(r["line"]), float(r["pos"])))
    random.Random(seed).shuffle(items)
    os.makedirs(out_dir, exist_ok=True)
    renders, boxcache = {}, {}
    font = ImageFont.truetype(FONT_PATH, 30) if neighbors else None
    key_rows = []
    for i, (leaf, line, pos) in enumerate(items, 1):
        if leaf not in renders:
            src_path, off_x, off_y, scale = SOURCES[leaf]
            renders[leaf] = (Image.open(src_path).convert("RGB"), off_x, off_y, scale, src_path)
            boxcache[leaf] = load_boxes(leaf)
        im, off_x, off_y, scale, src_path = renders[leaf]
        b = boxcache[leaf].get((line, int(pos)))
        if b is None:
            print(f"WARNING: no box for {leaf} line {line} pos {pos}", file=sys.stderr)
            continue
        x, y, w, h = b
        sx0, sy0 = (x + off_x) * scale, (y + off_y) * scale
        sw, sh = w * scale, h * scale
        W, H = im.size

        if neighbors:
            target_ip = int(pos)
            line_ips = sorted(ip for (ln, ip) in boxcache[leaf] if ln == line)
            idx = line_ips.index(target_ip)
            span_ips = line_ips[max(0, idx - neighbors): idx + 1 + neighbors]
            xs0, ys0, xs1, ys1 = [], [], [], []
            for ip in span_ips:
                nx, ny, nw, nh = boxcache[leaf][(line, ip)]
                nsx0, nsy0 = (nx + off_x) * scale, (ny + off_y) * scale
                xs0.append(nsx0); ys0.append(nsy0)
                xs1.append(nsx0 + nw * scale); ys1.append(nsy0 + nh * scale)
            pad = 25 * scale
            band_h = 40 * scale
            cx0 = max(0, int(min(xs0) - pad))
            cx1 = min(W, int(max(xs1) + pad))
            cy0 = max(0, int(min(ys0) - 1.5 * max(sh, 30 * scale)))
            cy1 = min(H, int(max(ys1) + 0.6 * max(sh, 30 * scale) + band_h))
        else:
            cx0 = max(0, int(sx0 - max(sw, 30 * scale)))
            cx1 = min(W, int(sx0 + sw + max(sw, 30 * scale)))
            cy0 = max(0, int(sy0 - 1.5 * max(sh, 30 * scale)))
            cy1 = min(H, int(sy0 + sh + 0.6 * max(sh, 30 * scale)))

        crop = im.crop((cx0, cy0, cx1, cy1))
        d = ImageDraw.Draw(crop)
        d.rectangle([sx0 - cx0 - 3, sy0 - cy0 - 3, sx0 - cx0 + sw + 3, sy0 - cy0 + sh + 3], outline=(0, 60, 220),
                    width=max(2, int(2 * scale)))

        if neighbors:
            for ip in span_ips:
                if ip == target_ip:
                    continue
                nx, ny, nw, nh = boxcache[leaf][(line, ip)]
                nsx0, nsy0 = (nx + off_x) * scale - cx0, (ny + off_y) * scale - cy0
                nsx1 = nsx0 + nw * scale
                nbottom = nsy0 + nh * scale + 8 * scale
                d.line([(nsx0, nbottom), (nsx1, nbottom)], fill=(200, 0, 0), width=max(2, int(2 * scale)))
                label = str(ip)
                tw = d.textlength(label, font=font)
                d.text(((nsx0 + nsx1) / 2 - tw / 2, nbottom + 4 * scale), label, fill=(200, 0, 0), font=font)

        r = 400 / crop.height
        if crop.width * r > 2500:
            r = 2500 / crop.width
        crop = crop.resize((max(1, int(crop.width * r)), max(1, int(crop.height * r))), Image.LANCZOS)
        cid = f"c{i:03d}"
        crop.save(f"{out_dir}/{cid}.png")
        key_rows.append((cid, leaf, line, pos, os.path.basename(src_path)))
    key_path = os.path.join(os.path.dirname(os.path.normpath(out_dir)) or ".", os.path.basename(os.path.normpath(out_dir)) + "_key.tsv")
    with open(key_path, "w") as f:
        f.write("id\tleaf\tline\tpos\trender\n")
        for row in key_rows:
            f.write("\t".join(str(c) for c in row) + "\n")
    print(f"{len(key_rows)} box crops -> {out_dir}/ (seed {seed}), key {key_path}")


if __name__ == "__main__":
    if "--boxes" in sys.argv:
        a = sys.argv
        boxes_mode(a[a.index("--boxes") + 1], a[a.index("--out") + 1], int(a[a.index("--seed") + 1]) if "--seed" in a else 0,
                   "--leaf-col" in a, int(a[a.index("--neighbors") + 1]) if "--neighbors" in a else 0)
    else:
        main()
