#!/usr/bin/env python3
"""Per-line crops for the plain-Italian boxes only (SALV-PLAIN1, 26 Sept 2026): usage crop_plain_leaf.py <leaf>.

Sibling of crop_passC_leaf.py, but reads only line/pos/code from ciphertext_<leaf>.tsv (never the passA/passB
code column for a sign box, since this job never decodes signs) and coordinates from <leaf>_boxes.tsv. Unlike
crop_passC_leaf.py (one crop per disagreement, at box-crop resolution from glyphs/crops/<leaf>.png, which no
longer exists on disk -- deleted by bSALS), this crops one image per manuscript line, full line width, from the
high-resolution renders regenerated by regen_images.sh + the 2400px fetches (U0 of the SALV-PLAIN1 brief):
  f54r: images/src_ark_12148_btv1b90600674_f55_4085_0_4086_5513.jpg, box (x,y) -> source pixel (x+250, y+650), scale 1
  f54v/f55r/f55v: images/<leaf>_ref2400.jpg, box (x,y) -> source pixel ((x+80)*1.5, (y+80)*1.5), scale 1.5
A split pos like 8.5 shares its integer parent box (crop_passC_leaf.py's convention): grouped under the parent's
coordinates here since this script marks boxes, not signs.

Under each PLAIN box only (code == '_' in ciphertext_<leaf>.tsv), in the margin below the ink, draws a thin
underline and its pos number; sign boxes (code != '_') get no mark, so a pass never sees which box the
solver's own transcription assigned a sign to. Downscales to at most 2400 px wide, uniformly, if a line's
native crop is wider (never draws over the ink -- the annotation band is a separate strip below the crop).

Output: plain_crops/<leaf>/L<nn>.png (one per manuscript line) + plain_crops/<leaf>/manifest.tsv
  (line, file, plain_pos_list, render, scale)

  python3 crop_plain_leaf.py f54r
"""
import csv, os, sys
from PIL import Image, ImageDraw, ImageFont

LEAF = sys.argv[1]
OUT = f"plain_crops/{LEAF}"
MAX_W = 2400
FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

SOURCES = {
    "f54r": ("images/src_ark_12148_btv1b90600674_f55_4085_0_4086_5513.jpg", 250, 650, 1.0),
    "f54v": ("images/f54v_ref2400.jpg", 80, 80, 1.5),
    "f55r": ("images/f55r_ref2400.jpg", 80, 80, 1.5),
    "f55v": ("images/f55v_ref2400.jpg", 80, 80, 1.5),
    "f56r": ("images/f56r_ref2400.jpg", 80, 80, 1.5),
    "f56v": ("images/f56v_ref2400.jpg", 80, 80, 1.5),
    "f57r": ("images/f57r_ref2400.jpg", 80, 80, 1.5),
    "f57v": ("images/f57v_ref2400.jpg", 80, 80, 1.5),
}


def load_boxes(leaf):
    boxes = {}  # (line, int_pos) -> (x, y, w, h)
    with open(f"{leaf}_boxes.tsv") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            line = int(r["line"])
            pos = int(float(r["pos"]))
            boxes[(line, pos)] = (int(r["x"]), int(r["y"]), int(r["w"]), int(r["h"]))
    return boxes


def load_codes(leaf):
    # line -> list of (pos_float, code) in reading order
    rows = {}
    with open(f"ciphertext_{leaf}.tsv") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            line = int(r["line"])
            rows.setdefault(line, []).append((float(r["pos"]), r["code"]))
    for line in rows:
        rows[line].sort(key=lambda t: t[0])
    return rows


def main():
    src_path, off_x, off_y, scale = SOURCES[LEAF]
    im = Image.open(src_path)
    W, H = im.size
    boxes = load_boxes(LEAF)
    codes = load_codes(LEAF)
    font = ImageFont.truetype(FONT_PATH, 34)

    os.makedirs(OUT, exist_ok=True)
    manifest = []
    for line in sorted(codes):
        entries = codes[line]  # (pos_float, code)
        int_positions = sorted(set(int(p) for p, _ in entries))
        # native-frame bbox across every box on this line (plain + sign, so context words aren't cropped away)
        xs0, ys0, xs1, ys1 = [], [], [], []
        for ip in int_positions:
            if (line, ip) not in boxes:
                continue
            x, y, w, h = boxes[(line, ip)]
            sx0, sy0 = (x + off_x) * scale, (y + off_y) * scale
            sx1, sy1 = (x + w + off_x) * scale, (y + h + off_y) * scale
            xs0.append(sx0); ys0.append(sy0); xs1.append(sx1); ys1.append(sy1)
        if not xs0:
            continue
        pad_x, pad_y = 20 * scale, 10 * scale
        band_h = 45 * scale  # annotation strip below the ink, in native crop pixels
        x0 = max(0, int(min(xs0) - pad_x))
        y0 = max(0, int(min(ys0) - pad_y))
        x1 = min(W, int(max(xs1) + pad_x))
        y1 = min(H, int(max(ys1) + pad_y + band_h))
        crop = im.crop((x0, y0, x1, y1)).convert("RGB")
        draw = ImageDraw.Draw(crop)

        plain_pos = []
        for pos_f, code in entries:
            ip = int(pos_f)
            if code != "_":
                continue
            if pos_f != ip:
                continue  # split positions share the parent box's single mark
            if (line, ip) not in boxes:
                continue
            plain_pos.append(ip)
            x, y, w, h = boxes[(line, ip)]
            sx0, sy0 = (x + off_x) * scale - x0, (y + off_y) * scale - y0
            sx1 = (x + w + off_x) * scale - x0
            box_bottom = (y + h + off_y) * scale - y0
            bottom = box_bottom + 8 * scale  # hug this box's own bottom edge, not the line's lowest box
            draw.line([(sx0, bottom), (sx1, bottom)], fill=(200, 0, 0), width=max(2, int(3 * scale)))
            label = str(ip)
            tw = draw.textlength(label, font=font)
            draw.text((max(x0 and 0, (sx0 + sx1) / 2 - tw / 2), bottom + 6 * scale), label, fill=(200, 0, 0), font=font)

        if crop.width > MAX_W:
            r = MAX_W / crop.width
            crop = crop.resize((MAX_W, int(crop.height * r)), Image.LANCZOS)
            out_scale = scale * r
        else:
            out_scale = scale

        fname = f"{OUT}/L{line:02d}.png"
        crop.save(fname)
        manifest.append((line, fname, ",".join(str(p) for p in plain_pos), os.path.basename(src_path), f"{out_scale:.4f}"))

    with open(f"{OUT}/manifest.tsv", "w") as f:
        f.write("line\tfile\tplain_pos\trender\tscale\n")
        for row in manifest:
            f.write("\t".join(str(c) for c in row) + "\n")

    total_plain = sum(len(r[2].split(",")) for r in manifest if r[2])
    print(f"{LEAF}: {len(manifest)} line crops -> {OUT}/, manifest {OUT}/manifest.tsv, {total_plain} plain boxes marked")


if __name__ == "__main__":
    main()
