#!/usr/bin/env python3
"""H199 (runner 8 session_011Taenrv3JSdk7VjpiBjids, 29 Sept 2026): H193's bowl question on fr.3983 f.108v's 4-family signs (f.61's hand).
Written before the call.
 tiles SCRATCH: targets = every column of the H59 f.108v draft (passes/f108v3z_recon_task.tsv, 315 columns) that pass A read, where the
   reconciled code (passes/f108v3z_draft_reconciled.tsv), pass A's code or pass B's code is a 4-family code (4TRI, C43, 4STEM, 4PI). The k-th
   column of a line that pass A read is pass A's k-th row of that line (checked: 45/42/43/48/42/45/46 on both sides), so each target has pass A's
   (segment, x_px) on the 3x crops (sheets/f108v3z_L0{1,2}_s1.jpg for L01/L02 segment 1, else sheets/f108v3y_Lxx_sN.jpg). Each target is a
   250 x 106 native-px window of images/3983_f108v.jpg (box of its crop from the bands json, x = box x0 + x_px/3; 20 px below the box top to 30 px
   below its bottom, because the 3x crops clip the bowl), scaled 1.44 (the H193 strips' 300 native px at 1.2 is similar) with a red triangle under the sign, shuffled (seed 199), numbered
   R01.., 20 per sheet in <scratch>/h199/. Key h199_items.tsv (item, line, column, reconciled code, A code, B code, segment, x_px), committed
   before the call. The repeat control is H193's 60 strips (<scratch>/h193/sheet_01..03, regenerated by h193_attr.py tiles; h193_items.tsv
   reproduced byte-identical 29 Sept 2026).
 score: GATE repeat control >= 17 of the 20 f.176v anchors in their group's direction (CP yes, AN no), else CONTROL FAIL, targets not scored.
   Then bowl yes / no / n by reconciled code (and by pass A / pass B code). Pre-stated reading: "the readers' split follows the bowl on f.108v"
   if >= 0.8 of reconciled 4TRI answer yes AND >= 0.8 of reconciled C43 answer no (answers n left out); otherwise "does not follow". Every
   target's answer goes to h199_bowl_positions.tsv for a later sequence step. Descriptive, for the verifier; no key change.
  python3 h199_bowl_108v.py tiles SCRATCH | score [--check]"""
import csv, os, random, sys
from collections import Counter, defaultdict
HERE = os.path.dirname(os.path.abspath(__file__)); P = f"{HERE}/passes"
FAM = ("4TRI", "C43", "4STEM", "4PI")
def rd(f): return [r for r in csv.DictReader((l for l in open(f) if not l.startswith("#")), delimiter="\t")]
def targets():
    A = defaultdict(list)
    for r in rd(f"{P}/f108v3z_signsA.tsv"): A[r["line"]].append(r)
    rec = {(r["line"], r["position"]): r["sign"] for r in rd(f"{P}/f108v3z_draft_reconciled.tsv")}
    out = []
    for l in sorted(A):
        cols = [r for r in rd(f"{P}/f108v3z_recon_task.tsv") if r["line"] == l]; k = 0
        assert sum(1 for c in cols if not c["alt"].startswith("A:-")) == len(A[l]), l
        for c in cols:
            if c["alt"].startswith("A:-"): continue
            a = A[l][k]; k += 1
            b = c["alt"][2:] if c["alt"].startswith("B:") else a["sign"]   # empty alt = both passes agree
            r_ = rec.get((l, c["position"]), "dropped")
            if r_ in FAM or a["sign"] in FAM or b in FAM:
                out.append(dict(line=l, column=c["position"], rec=r_, A=a["sign"], B=b, segment=a["segment"], x_px=a["x_px"]))
    return out
def crop(l, sg):
    z = f"{HERE}/sheets/f108v3z_{l}_s1.jpg"
    return z if (sg == "s1" and os.path.exists(z)) else f"{HERE}/sheets/f108v3y_{l}_{sg}.jpg"
def tiles(scratch):
    from PIL import Image, ImageDraw
    ts = targets(); rng = random.Random(199); rng.shuffle(ts); os.makedirs(f"{scratch}/h199", exist_ok=True); ims = []
    key = ["item\tline\tcolumn\trec\tA\tB\tsegment\tx_px"]
    import json
    nat = Image.open(f"{HERE}/images/3983_f108v.jpg").convert("RGB"); B = {}
    for j in ("f108v3y_bands.json", "f108v3z_bands.json"): B.update(json.load(open(f"{HERE}/sheets/{j}"))["boxes"])
    for n, t in enumerate(ts, 1):   # cut from the native (the 3x crops stop 34 native px below the centre and clip the bowl); 3x crop px / 3 = native px
        bx = B[os.path.basename(crop(t["line"], t["segment"]))]; x = bx[0] + int(t["x_px"]) // 3; y0, y1 = bx[1] + 20, bx[3] + 30
        s = 1.44; w = nat.crop((x - 125, y0, x + 125, y1)); w = w.resize((360, int((y1 - y0) * s)))
        # marker ABOVE the strip, pointing down (under it would sit below f.108v's interlinear gloss): prompt part 2 says so
        c = Image.new("RGB", (370, 190), "white"); c.paste(w, (5, 20)); d = ImageDraw.Draw(c); mx = 5 + int(125 * s)
        d.polygon([(mx - 9, 2), (mx + 9, 2), (mx, 17)], fill=(220, 0, 0)); d.text((6, 20 + w.height + 3), f"R{n:02d}", fill=(0, 0, 0))
        ims.append(c); key.append(f"R{n:02d}\t{t['line']}\t{t['column']}\t{t['rec']}\t{t['A']}\t{t['B']}\t{t['segment']}\t{t['x_px']}")
    for s in range(0, len(ims), 20):
        sh = Image.new("RGB", (4 * 370, 5 * 190), "white")
        for k, c in enumerate(ims[s:s + 20]): sh.paste(c, ((k % 4) * 370, (k // 4) * 190))
        sh.save(f"{scratch}/h199/sheet_{s // 20 + 1:02d}.jpg", quality=88)
    open(f"{HERE}/h199_items.tsv", "w").write("\n".join(key) + "\n"); print(len(ts), "targets;", Counter(t["rec"] for t in ts))
def score():
    ctl_key = {r["item"]: r for r in rd(f"{HERE}/h193_items.tsv")}; rep = rd(f"{P}/h199_reply.tsv")
    ans = {r["id"]: r["answer"].strip().lower() for r in rep}
    hit = sum((ans.get(m) == "yes") == (r["group"] == "CP") and ans.get(m) in ("yes", "no") for m, r in ctl_key.items() if r["group"] in ("CP", "AN"))
    out = [f"repeat control: {hit} of 20 f.176v anchors in their group's direction (gate >= 17): {'PASS' if hit >= 17 else 'CONTROL FAIL'}"]
    if hit >= 17:
        items = rd(f"{HERE}/h199_items.tsv"); pos = ["item\tline\tcolumn\trec\tA\tB\tbowl"]
        for which in ("rec", "A", "B"):
            t = defaultdict(Counter)
            for r in items: t[r[which]][ans.get(r["item"], "missing")] += 1
            out.append(f"by {which} code: " + "; ".join(f"{c} yes {t[c]['yes']} no {t[c]['no']} n {t[c]['n']}" + (f" missing {t[c]['missing']}" if t[c]['missing'] else "") for c in sorted(t)))
        for r in items: pos.append(f"{r['item']}\t{r['line']}\t{r['column']}\t{r['rec']}\t{r['A']}\t{r['B']}\t{ans.get(r['item'], 'missing')}")
        t = defaultdict(Counter)
        for r in items: t[r["rec"]][ans.get(r["item"], "missing")] += 1
        sh = lambda c, a: t[c][a] / max(1, t[c]["yes"] + t[c]["no"])
        fol = sh("4TRI", "yes") >= 0.8 and sh("C43", "no") >= 0.8
        out.append(f"reconciled 4TRI yes share {sh('4TRI', 'yes'):.2f}, C43 no share {sh('C43', 'no'):.2f} -> the readers' split "
                   + ("follows the bowl on f.108v" if fol else "does not follow the bowl on f.108v"))
        allb = Counter(ans.get(r["item"], "missing") for r in items)
        out.append(f"all {len(items)} f.108v 4-family targets: bowl yes {allb['yes']}, no {allb['no']}, n {allb['n']}")
        pp = f"{HERE}/h199_bowl_positions.tsv"; ptxt = "\n".join(pos) + "\n"
        if "--check" not in sys.argv: open(pp, "w").write(ptxt)
        elif not (os.path.exists(pp) and open(pp).read() == ptxt): print("check STALE (positions)"); sys.exit(1)
    txt = "\n".join(out) + "\n"; res = f"{HERE}/h199_bowl_108v_result.txt"
    if "--check" in sys.argv:
        ok = os.path.exists(res) and open(res).read() == txt; print("check", "OK" if ok else "STALE"); sys.exit(0 if ok else 1)
    open(res, "w").write(txt); print(txt, end="")
if __name__ == "__main__":
    tiles(sys.argv[2]) if sys.argv[1] == "tiles" else score()
