#!/usr/bin/env python3
"""H214 (runner 8 session_011Taenrv3JSdk7VjpiBjids, 29 Sept 2026): H212's looped-hash form tested against period letters on H195's unchanged strips
(h195_items.tsv; regenerated by h195_hash_attr.py tiles, key byte-identical). Written before the call. The question is H212's group-B attribute, fixed
before any look at these strips: "does the sign carry two small loops sitting on the hash?" Direction fixed now: yes = group I (the DP pairs it with i).
 score: GATE >= 17 of the 20 f.176v anchors in the pre-stated direction (I yes, DQ no), else CONTROL FAIL and targets not scored. Then the 40 f.176r
 targets split by the answer, counted {i} vs {d,q} under fol. 177r (h183 alignment letters in the key), Fisher exact. Descriptive.
  python3 h214_loops.py [--check]"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import h193_attr as H, h190_4fam as h190
g = H.g
def main():
    key = {r["item"]: r for r in g.rd(f"{HERE}/h195_items.tsv")}; ans = {r["item"]: r["answer"].strip().lower() for r in g.rd(f"{HERE}/passes/h214_attribute.tsv")}
    anc = [m for m, r in key.items() if r["group"] in ("I", "DQ")]
    hit = sum((ans.get(m) == "yes") == (key[m]["group"] == "I") and ans.get(m) in ("yes", "no") for m in anc)
    out = [f"anchors: {hit} of {len(anc)} answer in the pre-stated direction (looped = i; gate >= 17): {'PASS' if hit >= 17 else 'CONTROL FAIL'}",
           "anchor answers: I " + " ".join(ans.get(m, "-") for m in anc if key[m]["group"] == "I") + " | DQ " + " ".join(ans.get(m, "-") for m in anc if key[m]["group"] == "DQ")]
    if hit >= 17:
        c = {"yes": [0, 0], "no": [0, 0]}
        for m, r in key.items():
            if r["group"] == "T" and ans.get(m) in c and r["letter"] in "idq": c[ans[m]][0 if r["letter"] == "i" else 1] += 1
        p = h190.fisher(c["yes"][0], c["yes"][1], c["no"][0], c["no"][1])
        out.append(f"f.176r targets: looped yes -> i {c['yes'][0]} d/q {c['yes'][1]}; looped no -> i {c['no'][0]} d/q {c['no'][1]}; Fisher p {p:.2g}")
    txt = "\n".join(out) + "\n"; rp = f"{HERE}/h214_loops_result.txt"
    if "--check" in sys.argv:
        ok = os.path.exists(rp) and open(rp).read() == txt; print("check", "OK" if ok else "STALE"); sys.exit(0 if ok else 1)
    open(rp, "w").write(txt); print(txt, end="")
if __name__ == "__main__": main()
