#!/usr/bin/env python3
"""H230 (runner 9 session_012NTadgrCBftz3oRtgw5jFu, 29 Sept 2026): does H199 reproduce? Written before the call. H199's own sheets (h199_bowl_108v.py
tiles; h199_items.tsv regenerated byte-identical) and H193's 60 control strips (h193_attr.py tiles from fresh natives f327/f328 cut by cut_bands.py per
sheets/f176r_full and f176v_full README; h193_items.tsv byte-identical) in one fresh blind Opus call with H199's verbatim prompt (PROMPTS_f176_f175.md
H199), reply passes/h230_reply.tsv. Pre-stated: "H199 reproduces" iff control >= 17/20 AND R-item agreement with H199 >= 0.85 over items answered yes/no
both times AND >= 0.7 of H199's yes answers are yes again; else "H199 does not reproduce". Also reported: H199's bowl-by-code table recomputed from this
reply.  python3 h230_h199_repro.py [--check]"""
import csv, os, sys
from collections import Counter, defaultdict
HERE = os.path.dirname(os.path.abspath(__file__)); P = f"{HERE}/passes"
def rd(f): return [r for r in csv.DictReader((l for l in open(f) if not l.startswith("#")), delimiter="\t")]
def main():
    new = {r["id"]: r["answer"].strip().lower() for r in rd(f"{P}/h230_reply.tsv")}; old = {r["id"]: r["answer"].strip().lower() for r in rd(f"{P}/h199_reply.tsv")}
    ctl = {r["item"]: r for r in rd(f"{HERE}/h193_items.tsv")}
    hit = sum((new.get(m) == "yes") == (r["group"] == "CP") and new.get(m) in ("yes", "no") for m, r in ctl.items() if r["group"] in ("CP", "AN"))
    R = [m for m in old if m.startswith("R")]; both = [m for m in R if old[m] in ("yes", "no") and new.get(m) in ("yes", "no")]
    agree = sum(old[m] == new[m] for m in both); oy = [m for m in R if old[m] == "yes"]; yy = sum(new.get(m) == "yes" for m in oy)
    Q = [m for m in old if m.startswith("Q")]; qa = sum(old[m] == new.get(m) for m in Q)
    items = rd(f"{HERE}/h199_items.tsv"); t = defaultdict(Counter)
    for r in items: t[r["rec"]][new.get(r["item"], "missing")] += 1
    out = [f"control: {hit} of 20 f.176v anchors in their group's direction (gate >= 17): {'PASS' if hit >= 17 else 'CONTROL FAIL'}",
           f"Q items agree with H199's own Q answers: {qa}/{len(Q)}",
           f"R items: agreement with H199 {agree}/{len(both)} = {agree / max(1, len(both)):.2f} (answered yes/no both times); H199 yes {len(oy)}, yes again {yy} = {yy / max(1, len(oy)):.2f}",
           "this reply by reconciled code: " + "; ".join(f"{c} " + " ".join(f"{k} {v}" for k, v in sorted(t[c].items())) for c in sorted(t)),
           "H199's own: " + "; ".join(f"{c} " + " ".join(f"{k} {v}" for k, v in sorted(Counter(old.get(r['item']) for r in items if r['rec'] == c).items())) for c in sorted(t))]
    ok = hit >= 17 and agree / max(1, len(both)) >= 0.85 and yy / max(1, len(oy)) >= 0.7
    out.append("read-out: " + ("H199 reproduces" if ok else "H199 does not reproduce"))
    txt = "\n".join(out) + "\n"; p = f"{HERE}/h230_h199_repro_result.txt"
    if "--check" in sys.argv:
        ok2 = os.path.exists(p) and open(p).read() == txt; print("check", "OK" if ok2 else "STALE"); sys.exit(0 if ok2 else 1)
    open(p, "w").write(txt); print(txt, end="")
if __name__ == "__main__": main()
