#!/usr/bin/env python3
"""H405 (runner 15 session_01BDhspZ38TdrrXYSvLPTpjc, 29 Sept 2026), script-only: the f.61 meter's two-way band against the published table's design.
Per f.61 token in the two-way band (key v8 as merged = verify_v11/meter_v11 baseline, f.61 4TRI bowl 6/6): class, cell, whether Tomokiyo's table
(keys/key_mayenne_1592.tsv) draws that letter pair as ONE shared symbol (polyphony by design: no shape test can narrow it) or TWO (e/r, a/n), the
shape instruments already run on that pair, and Tomokiyo's letter where his spans cover the position (scripts/f61_skeleton.txt). Writes F61_FLOOR.md.
python3 h405_meter_floor.py [--check]"""
import csv, os, sys
from collections import Counter
HERE = os.path.dirname(os.path.abspath(__file__)); T = os.path.abspath(f"{HERE}/.."); sys.path.insert(0, f"{T}/verify_v9"); sys.path.insert(0, HERE)
import meter_v9 as m
TWO = {"a/n", "e/r"}
COLS = {"a/n", "b/o", "c/p", "d/q", "e/r", "f/s", "g/t", "h/u", "i/x", "l/y", "m/z"}   # the table's eleven columns
def design(cell): return "two symbols" if cell in TWO else "one shared symbol" if cell in COLS else "cross-column (fitted set spans two table symbols)"
TRIED = {"e/r": "H23 (counts), H71 free sort FAIL, H401 forced-choice look: no attribute (f.61's hand)",
         "a/n": "H23 (counts), H24/H24b free sort FAIL/non-test, H73 FAIL; the 4TRI bowl split (H193-H396) separates the c/p sign from the a/n sign, not a from n",
         "c/p": "bowl split made (c/p sign vs a/n sign); within c/p: shared symbol", "g/t": "H80 control FAIL as expected (shared)", "d/q": "H75 control FAIL as expected (shared)"}
def main():
    import h401_er_attr as h
    d = list(csv.DictReader(open(f"{m.F}/f61_decode_period_v4_frac0.1_sbs.tsv"), delimiter="\t")); k6 = m.bk.load_key_v6(ebr="B", f61=True)
    def v8(r):
        c = r["class"]
        if c == "4PI": return "a/n" if r["line"] == "L11" else "-"
        if c in ("VBAR_A", "EBR", "SBS"): return {"VBAR_A": "g/t", "EBR": "l/y", "SBS": "b/o"}[c]
        if c in ("ZHOOK", "HASH4", "4TRI", "4STEM"): return "/".join(k6[c])
        return r["period_letters"]
    lets = h.f61_letters(); rows = []; bands = Counter()
    for r in d:
        cell = v8(r); b = m.band(cell, r["class"], False, True); bands[b] += 1
        if b != "two-way": continue
        c2, L = lets.get((r["line"], r["pos"]), ("?", ""))
        rows.append((r["line"], r["pos"], r["class"], cell, design(cell), L, TRIED.get(cell, "")))
    n = len(rows); two = [x for x in rows if x[4] == "two symbols"]; xc = [x for x in rows if x[4].startswith("cross")]; sp = [x for x in rows if x[5]]
    by = Counter((x[2], x[3], x[4]) for x in rows)
    out = ["# f.61 meter floor (H405, runner 15, 29 Sept 2026; generated by family/h405_meter_floor.py, do not hand-edit)", "",
           f"Meter under key v8 as merged (f.61 4TRI bowl 6/6): firm {bands['firm']} / two-way {bands['two-way']} / wider {bands['wider']} / "
           f"unread-or-null {bands['null'] + bands['unread']} of {len(d)}.", "",
           f"Of the {n} two-way tokens, **{n - len(two) - len(xc)} sit in a pair the published table draws as ONE shared symbol** (polyphony by design: "
           f"no shape test can narrow them; only a reading can), **{len(xc)} carry a fitted set that is not a table column** (BETA m/s, LOOPSTEM1 q/s, "
           f"CH e/m: the set spans two table symbols, so a single-cell test could correct the cell -- but to a table column, which is still two-way "
           f"unless it lands in e/r or a/n), and **{len(two)} in the two pairs it draws as two symbols (e/r, a/n)**, where no shape "
           f"instrument has separated the letters (in f.61's hand: H23, H24b, H401; on other hands: H71, H73). {len(sp)} of the {n} lie inside "
           f"Tomokiyo's five spans (his letter known, published); {n - len(sp)} lie outside them.", "",
           "| class | cell | table design | tokens | inside spans | instruments on the pair |", "|---|---|---|---|---|---|"]
    for (c, cell, des), k in sorted(by.items(), key=lambda x: -x[1]):
        ins = sum(1 for x in rows if x[2] == c and x[5]); out.append(f"| {c} | {cell} | {des} | {k} | {ins} | {TRIED.get(cell, '')} |")
    out += ["", "Per token (line, position, class, cell, design, Tomokiyo's letter if in a span):", ""]
    out += [f"- {a} {b} {c} {e} ({f}){' T:' + g if g else ''}" for a, b, c, e, f, g, _ in rows]
    out += ["", "Reading of this table: the two-way band cannot move by any further shape test on f.61 as the design stands; it moves only by (a) a reading "
            "of a position with a control, which H125 found impossible at the length of f.61's out-of-span material alone, or (b) new lettered material "
            "in f.61's hand (ASKS 88/89 f.108r/v gloss, ASKS 93 f.211r; fr.4699 ff.37/41 by reproduction request), or (c) a verifier grading "
            "Tomokiyo's in-span letters, which are published (N0/N1 as readings)."]
    txt = "\n".join(out) + "\n"; p = f"{HERE}/F61_FLOOR.md"
    if "--check" in sys.argv:
        ok = os.path.exists(p) and open(p).read() == txt; print("check", "OK" if ok else "STALE"); sys.exit(0 if ok else 1)
    open(p, "w").write(txt); print("\n".join(out[:12]))
if __name__ == "__main__":
    sys.argv = [sys.argv[0]] + [a for a in sys.argv[1:]]; main()
