#!/usr/bin/env python3
"""FIX-L17c (10 Oct 2026, account 1, for LANE LEDGER-17): apply s.5 of AUDIT (FV-L17a) for E582 E583 E586 E587, of AUDIT (FV-L17b) s.4-s.6 for E589 E590
E592 E593, and of AUDIT (FV-L17c) s.5 for E624, plus the lane ruling (E582 E587 E624 stay filed with N1 header notes; E583 E586 E589 E590 E592 E593 stay filed at
D1), to ciphertext.txt as header edits, decoder directive lines and one 'note: FIX-L17c' line per entry. Same method as fixl17a_apply.py / fixl17b_apply.py
(reused run()); reading*.md only by decode.py --write. Idempotent: skips a block that already has a 'FIX-L17c' note. E581 E585 (AUD2-LEDGER17-1), E591 E594
(-2) and E622 E623 (-3) are not touched: their s.5 waits for the second audits. key.md is not edited."""
import fixl15_apply as base
base.MARK = 'FIX-L17c (10 Oct 2026'
base.E.clear(); base.LF.clear()
E = base.E; LF = base.LF
def S(e, h=(), d=(), n=''): E[e] = dict(h=list(h), d=list(d), n=n)
def N(src, body): return "FIX-L17c (10 Oct 2026, account 1, for LANE LEDGER-17; %s): %s" % (src, body)
D1 = "stays filed at D1 under the lane ruling of 10 Oct 2026: too short for a clause above the authentication distance (FV-L17a/b); no entry removed"

# ---- FV-L17a ----
S('E582', h=[("[a name, unread 'Melan'] or Ord either will be good [men] to relieve Gen. Foster", "General Logan ('Melan', C by print) or Ord either will be good men to relieve Gen. Foster (peach = 2 = 'to', the print's 'to relieve')"),
             ("from Grant for the Secretary of War at Monroe", "from Grant for the Secretary of War (Stanton) at Monroe"),
             ("(FM-S65A; row 5862/2; read from the transcription, no image)", "(FM-S65A; row 5862/2; image-read by FV-L17a, matches the transcription; N1: plaintext printed OR I/47 pt 2 p.18, Grant to Stanton, 6 Jan 1865 8.30 p.m.; the reading is the printed text; stays filed with this note under the lane ruling of 10 Oct 2026)")],
  d=['gloss: melan=Logan:C', 'gloss: peach=to:C'],
  n=N('AUDIT FV-L17a s.5', "'Melan' = Logan (C from OR I/47 pt 2 p.18, 'Logan or Ord either will be good men to relieve Gen. Foster'); 'peach' = 2 = 'to' (the print's 'to relieve'), not '[2]'; 'wilby' = will be (plain-phonetic); 'spit' = Men (H). With the print H 11 + C 1 of 12 (FV-L17a). Class N1: the plaintext is in print; under the Wave 2 RULING (ii) this row would not be filed, and the lane ruling keeps it filed with this header note. No status.json or second-opinion row exists for it and none is to be written."))
S('E583', h=[("[an unread word 'weasler'] the Illinois goes to sea at 11 o'clock with 1200 and 87 [men]", "[an unread word 'weasler', M] the Illinois goes to sea at 11 o'clock with 1,287 men (12 / 100 / 80 / 7 / Men: 'forbid William and Mother postpone spit')"),
             ("(FM-S65A; row 5872/0; read from the transcription, no image)", "(FM-S65A; row 5872/0; image-read by FV-L17a, matches the transcription; D1, N3 plaintext not located; " + D1 + ")")],
  d=['graded: weasler:M'],
  n=N('AUDIT FV-L17a s.5 and s.4, RULING (iii)', "numerals read 12 / 100 / 80 / 7 + Men = 1,287 men (twelve hundred and eighty-seven), not '[1200] and [87]'; 'see' = sea (plain-phonetic); 'weasler' unread, M (also in 5883/0 'on weasler frog' and 5883/2 'Libby weasler Shelly Lyon'; not in key.md). The numerals tie under the shuffled-key control, so the control cannot separate the book here; only 'palsy' (Brigadier General), 'borgia' (Chief of Staff) and 'spit' (Men) are separable. FV-L17a recommended not filed (RULING iii); " + D1 + "."))
S('E586', h=[("(FM-S65A; row 5874/1; read from the transcription, no image; about 16 words)", "(FM-S65A; row 5874/1; image-read by FV-L17a, matches the transcription; about 16 words; D1, N3 plaintext not located; " + D1 + "; the answer to E585)")],
  n=N('AUDIT FV-L17a s.5 and s.4, RULING (iii)', "no decoder change (H 5, no two adjacent: Brevet [Major] [General] Grovers [40] rounds of [Ammunition] will answer; the rest is plain); the clause is plain English and corroborated only as the answer to E585. FV-L17a recommended not filed (RULING iii); " + D1 + "."))
S('E587', h=[("21 Jan 1865 Washington 3 PM, T. T. Eckert to Sheldon at Ft Monroe, for Gen. Palmer: wait at Monroe until I get there; I will leave [a place unread] at 5 AM tomorrow; signed Eckert", "21 Jan 1865 Washington 3 PM, Lieut. Gen. U. S. Grant (the Washington office, T. T. Eckert, closes the row) to Sheldon at Ft Monroe, for Brig. Gen. I. N. Palmer, commanding the District of North Carolina: wait at Monroe until I get there; I will leave Annapolis at 5 AM tomorrow; signed U. S. Grant ('John')"),
             ("(FM-S65A; row 5883/2; read from the transcription, no image;", "(FM-S65A; row 5883/2; image-read by FV-L17a, matches the transcription; N1: plaintext printed OR I/46 pt 2 p.198, Grant to I. N. Palmer, 21 Jan 1865, received 3 p.m.; stays filed with this note under the lane ruling of 10 Oct 2026;")],
  d=['merge: an+apple+is', 'gloss: anappleis=Annapolis:C', 'gloss: mock=Brig._Gen._I._N._Palmer:H'],
  n=N('AUDIT FV-L17a s.5', "'an Apple is' = Annapolis ('an Apple is', plain-phonetic; C from OR I/46 pt 2 p.198), not '[Sumter] is'; the sender is U. S. Grant ('John', H), not Eckert, whose name closes the row as the Washington office; 'mock' = Brig. Gen. I. N. Palmer (the key sheet's label 'Gen J. M. Palmer' is the sheet's, the referent is I. N. Palmer, the print; holder 7718 signs 'J. W.'). H 11 + C 1 of 12. Class N1: plaintext printed; the reading is the printed text; under the Wave 2 RULING (ii) this row would not be filed, and the lane ruling keeps it filed with this header note. Unsafe: any sentence naming Eckert as the sender or implying the plaintext was unknown. No status.json or second-opinion row exists for it and none is to be written."))
# ---- FV-L17b ----
S('E589', h=[("(FM-S65B; row 5892/1; short, 15 tokens)", "(FM-S65B; row 5892/1; short, 15 tokens; image-read by FV-L17b; D1, N3 plaintext not located; " + D1 + ")")],
  n=N('AUDIT FV-L17b s.4-s.6, RULING (iii)', "no decoder change: reading stands ('euta meat' = you to meet, plain-phonetic); Animal = Monroe, Ann = 1 AM, Taunton = Major, H 3 of 3. FV-L17b recommended not filed (RULING iii, too short); " + D1 + "."))
S('E590', h=[("addressed to the Secretary of State (the decoder's reading of the address group 'Byron', M)", "addressed to the Secretary of State (address group 'Byron', a key row, H; Seward at Fort Monroe, OR I/46 pt 2 pp.352-353)"),
             ("signed (Grant, decoded from the closing groups 'walrus Juno', M)", "signed Grant ('Juno', a key row, H, after 'walrus' = Signature)"),
             ("(FM-S65B; row 5896/0; 22 tokens)", "(FM-S65B; row 5896/0; 22 tokens; image-read by FV-L17b; D1, N3 plaintext not located; " + D1 + ")")],
  d=['graded: fit:M'],
  n=N('AUDIT FV-L17b s.4/s.6, RULING (iii)', "the M on the addressee (Byron = Secretary of State) and on the signer (Juno = Grant) is lifted to H: both are key rows and fit OR I/46 pt 2 pp.352-353 (Seward at Fort Monroe; Grant telegraphing the Secretary of State there that day); Jennie = 3.30 PM, Walrus = Signature, H 4 of 4; 'inure dispatch' = in our dispatch (plain-phonetic); 'fit' is unread (a null or a slip, M). The body is plain English. FV-L17b recommended not filed (RULING iii, plain, no book reads a clause); " + D1 + "."))
S('E592', h=[("from Monroe, 20 (units not given) for Camman and Company", "from [Monroe] [20], most likely the dateline of the private telegram (Fort Monroe, the 20th; M as to its role), for Camman and Company"),
             ("(FM-S65B; row 5910/1; short, 18 tokens)", "(FM-S65B; row 5910/1; short, 18 tokens; image-read by FV-L17b; D1, N3 plaintext not located; " + D1 + ")")],
  n=N('AUDIT FV-L17b s.4/s.6, RULING (iii)', "header corrected: 'Animal harsh' = [Monroe] [20], most likely the private telegram's dateline (Fort Monroe, the 20th, the row's own date; M as to role), not '20 (units not given)'; 'frog unity' = [New York] [.]; 'yoke' = Signature; 'sell gold to fall (below?)' stays as read. Content: for approval, Fort Monroe, 20th, for Camman and Company, New York: sell gold to fall; W. Cooper (he is naval officer). H 5. FV-L17b recommended not filed (RULING iii, too short); " + D1 + "."))
S('E593', h=[("for (Captain James, as the decoder reads the address groups, M): 'The ponchos are not on hand at present but Canby is shipped on (Sheridan's?) arrival here if that will suffice; Ingalls'", "for Captain James ('princess Bergen' = Captain, James: a person or 'Captain, James River' stays M): 'The ponchos are not on hand at present but can be issued on [Sheridan]'s arrival here if that will be satisfactory; Ingalls' ('Canby is Shoed on' = can be issued on and 'Wilby Sausage factory' = will be satisfactory, plain sound-alikes, I; not General Canby)"),
             ("(FM-S65B; row 5936/2; 21 tokens)", "(FM-S65B; row 5936/2; 21 tokens; image-read by FV-L17b; D1, N3 plaintext not located; " + D1 + ")")],
  d=['graded: canby:I', 'graded: shoed:I', 'graded: wilby:I', 'graded: sausage:I', 'graded: factory:I'],
  n=N('AUDIT FV-L17b s.4/s.6, RULING (iii)', "'Canby is Shoed on' = 'can be issued on' (a plain sound-alike, I; not General Canby and not 'shipped') and 'Wilby Sausage factory' = 'will be satisfactory' (I; not 'sufficient'), so the header's 'Canby is shipped on ... if that will suffice' is superseded. Minnie = 7.30 PM, Princess = Captain, Bergen = James, Nabobs = P. H. Sheridan: H 4; 'princess Bergen' as an addressee ('Captain James', a person, or 'Captain, James River') stays M; 'Stop' plain. FV-L17b recommended not filed (RULING iii); " + D1 + "."))
# ---- FV-L17c ----
S('E624', h=[("I left General Butler's headquarters 5 miles from Bermuda Landing, all quiet", "I left General Butler's headquarters 5 miles from White River Landing at 9 PM (as deciphered at the time, C by the clear copy 10308; the place meant was very probably Bermuda Landing, I), all quiet"),
             ("[cavalry expedition crossing] at Harrison's Landing", "West's [Cavalry] [Expedition] [crossing] at Harrison's Landing"),
             ("transcription only, page image not eye-checked)", "transcription only, page image not eye-checked by FM-UND2; N1: holder clear copy 10308 (Page 166), which FM-UND2 and FM-UND did not find; stays filed with this note under the lane ruling of 10 Oct 2026, FV-L17c)")],
  d=['gloss: rosaile=9_PM:C'],
  n=N('AUDIT FV-L17c s.5', "FM-UND2's `plain: Bermuda` is withdrawn (that line is replaced by the rosaile gloss): the holder clear copy 10308 (Page 166) reads 'five miles from White River Landing 9 PM' and 'West's Cavalry Expedition', so the key row Bermuda = White River (p.10 l.16) is the period decipherment's value (C) and the referent Bermuda Landing (E164) is an inference (I); rosaile = 9 PM (C); wests = West's (plain name, C); Knox = Butler, person = 5, pacific = Cavalry, roman = Expedition, pluming = crossing (H, the clear copy agrees). Class N1 (holder clear copy 10308): under the Wave 2 RULING (i) this telegram would not be filed, and the lane ruling keeps it filed with this header note. FM-UND2's 'no clear copy' for this telegram and FM-UND's '3 holder queries hit 5658, 9734 only' are superseded. Unsafe: any sentence implying the plaintext was unknown. No status.json or second-opinion row exists for it and none is to be written."))
LF['E624'] = ("plain: Bermuda", "gloss: rosaile=9_PM:C\nvariant: bermuda=Bermuda:C")
E['E624']['d'] = []
if __name__ == '__main__': base.run('ciphertext.txt')
