#!/usr/bin/env python3
"""H52 (28 Sept 2026): the cipher lines of espagnol142-mercy-1648 under key.tsv, and beside each changed line the same
line with the crib CANDIDATES of candidates.tsv applied, every candidate token in braces. Writes
reading_candidates.txt; --check exits 1 if the committed file is stale (CLAUDE.md rule 7 shape). These are candidates
with the tests listed in candidates.tsv, some passed and some not; reading.txt and key.tsv are unchanged, and nothing
here is a reading or a grade.
  python3 ciphers/espagnol142-mercy-1648/candidates/make_candidates.py [--check]"""
import csv, os, sys
D = os.path.dirname(os.path.abspath(__file__)); T = os.path.dirname(D)
key = {r['code']: r['letter'] for r in csv.DictReader(open(os.path.join(T, 'key.tsv')), delimiter='\t')}
cand = list(csv.DictReader(open(os.path.join(D, 'candidates.tsv')), delimiter='\t'))
rows = list(csv.DictReader(open(os.path.join(T, 'cipher_codes_522.tsv')), delimiter='\t'))
lines, order = {}, []
for r in rows:
    if r['line'] not in lines:
        lines[r['line']] = []; order.append(r['line'])
    lines[r['line']].append(r)
def value(r):
    loc = f"{r['line']}:{r['position']}"
    for c in cand:
        if c['code'] == r['sign'] and (c['where'].startswith('all') or loc in c['where']):
            return '{' + c['candidate'] + '}'
    return None
out = ["# espagnol142-mercy-1648: cipher lines under key.tsv (K) and with crib candidates applied (C, candidates in braces).",
       "# CANDIDATES ONLY -- see candidates.tsv for each value's step, test and result (some tests were not met).",
       "# Generated by candidates/make_candidates.py; reading.txt and key.tsv are unchanged; not a reading, not a grade.", ""]
for ln in order:
    k = ''.join((key.get(r['sign'], '?') if key.get(r['sign'], '_') != '_' else '_').upper() for r in lines[ln])
    c = ''.join((value(r) or (key.get(r['sign'], '?') if key.get(r['sign'], '_') != '_' else '_').upper()) for r in lines[ln])
    out.append(f"{ln} K  {k}")
    if c != k:
        out.append(f"{ln} C  {c}")
text = '\n'.join(out) + '\n'
path = os.path.join(D, 'reading_candidates.txt')
if '--check' in sys.argv:
    ok = os.path.exists(path) and open(path).read() == text
    print('reading_candidates.txt', 'current' if ok else 'STALE'); sys.exit(0 if ok else 1)
open(path, 'w').write(text); print('wrote', path)
