#!/usr/bin/env python3
"""Group-level frame concordance for the sub-1100 groups of R9558/R9559/R9560/R9587 (A2-CAS, 2 Oct 2026).

Companion to lowrange_concordance.py (value-level frames). Here a frame is the identical neighbouring
*groups* (keyed or not; '?' groups never match): (L1,_,R1). A target occurrence of unkeyed sub-1100 group t
in frame (a,_,b) is paired with every occurrence anywhere in the corpus of a *different* group x in the same
frame. If x is keyed, x's value is a vote for t (homophone substitution in a repeated formula). t gets a
candidate when one value wins votes from >= 2 distinct occurrences of t, or from one occurrence of t whose
frame recurs with that value in >= 2 records (the two-context bar). Every frame pairing (keyed or not) is
listed so unkeyed-for-unkeyed homophone pairs are visible too.

Statistic: number of target occurrences that share an identical group frame with a different group anywhere
(order-dependent, so the controls can differ: C1 shuffles token order in the four target records, C2 in every
record). Known-answer: each keyed sub-1100 group is unkeyed in turn and asked for its value.
Usage: python3 group_frames.py [--shuffles 200] [--seed 1] [--out group_frames.tsv]
"""
import argparse, collections, os, random
from lowrange_concordance import load, TARGETS, HERE


def index(recs):
    idx = collections.defaultdict(list)
    for r, s in recs.items():
        for i in range(1, len(s) - 1):
            a, b = s[i - 1], s[i + 1]
            if "?" in a or "?" in b or "?" in s[i]:
                continue
            idx[(a, b)].append((r, i, s[i]))
    return idx


def pairs(recs, idx, groups, where):
    out = collections.defaultdict(list)  # t -> [(rid,i,x,xrid)]
    for r in where:
        s = recs[r]
        for i in range(1, len(s) - 1):
            t = s[i]
            if t not in groups:
                continue
            for (r2, j, x) in idx.get((s[i - 1], s[i + 1]), []):
                if x != t:
                    out[t].append((r, i, x, r2))
    return out


def vote(prs, key):
    res = {}
    for t, lst in prs.items():
        byv = collections.defaultdict(list)
        for r, i, x, r2 in lst:
            if x in key:
                byv[key[x]].append((r, i, x, r2))
        best = None
        for v, h in byv.items():
            occ = {(r, i) for r, i, _, _ in h}
            rec2 = {r2 for _, _, _, r2 in h}
            if len(occ) >= 2 or len(rec2) >= 2:
                cand = (len(occ), len(rec2), v, h)
                best = max(best, cand) if best else cand
        if best:
            res[t] = best
    return res


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--shuffles", type=int, default=200)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--out", default=os.path.join(HERE, "group_frames.tsv"))
    a = ap.parse_args()
    recs, key = load()
    low = lambda g: g.isdigit() and int(g) < 1100
    T = {g for r in TARGETS for g in recs[r] if low(g) and g not in key}
    idx = index(recs)
    prs = pairs(recs, idx, T, TARGETS)
    st = lambda p: sum(len({(r, i) for r, i, _, _ in l}) for l in p.values())
    real_occ, real_groups = st(prs), len(prs)
    cands = vote(prs, key)
    print(f"REAL: {real_occ} target occurrences ({real_groups} groups) share an identical group frame with a different group; "
          f"{len(cands)} groups get a two-context keyed candidate")
    rng = random.Random(a.seed)
    for name, which in (("C1 target records shuffled", TARGETS), ("C2 every record shuffled", list(recs))):
        o, c = [], []
        for _ in range(a.shuffles):
            sh = {r: list(s) for r, s in recs.items()}
            for r in which:
                rng.shuffle(sh[r])
            p = pairs(sh, index(sh), T, TARGETS)
            o.append(st(p)); c.append(len(vote(p, key)))
        o.sort(); c.sort()
        p95 = lambda xs: xs[int(0.95 * len(xs)) - 1]
        print(f"{name}: occurrences mean {sum(o)/len(o):.2f} p95 {p95(o)} max {o[-1]} (>= real: {sum(x >= real_occ for x in o)}/{a.shuffles}); "
              f"candidates mean {sum(c)/len(c):.2f} p95 {p95(c)} max {c[-1]}")
    kl = sorted({g for s in recs.values() for g in s if low(g) and g in key}, key=int)
    right = wrong = none = 0
    for g in kl:
        k2 = {x: y for x, y in key.items() if x != g}
        v = vote(pairs(recs, idx, {g}, list(recs)), k2)
        if g not in v:
            none += 1
        elif v[g][2] == key[g]:
            right += 1; print(f"  KA {g}: {key[g]!r} recovered")
        else:
            wrong += 1; print(f"  KA {g}: key {key[g]!r} -> {v[g][2]!r}")
    print(f"KNOWN-ANSWER ({len(kl)} keyed sub-1100 groups, leave-one-out): right {right}, wrong {wrong}, no candidate {none}")
    with open(a.out, "w") as fh:
        fh.write("# generated by group_frames.py (A2-CAS, 2 Oct 2026); every identical-group-frame pairing of a target sub-1100 group; grade M at most, nothing merged into key.tsv\n")
        fh.write("group\trecord\tpos\tframe\tother_group\tother_value\tother_record\n")
        for t in sorted(prs, key=int):
            for r, i, x, r2 in prs[t]:
                s = recs[r]
                fh.write(f"{t}\t{r}\t{i}\t{s[i-1]} _ {s[i+1]}\t{x}\t{key.get(x, '')}\t{r2}\n")
    for t, (n, nr, v, h) in sorted(cands.items(), key=lambda z: -z[1][0]):
        print(f"  CAND {t} = {v!r}: {n} occ, {nr} other records, via {sorted({x for _,_,x,_ in h})}")
    print(f"wrote {a.out}")


if __name__ == "__main__":
    main()
