#!/usr/bin/env python3
"""Reconcile the two blind passes (passA.tsv, passB.tsv) of BnF fr.4687 items 1-3 against the reconciler's
native-resolution reading (passC_native.tsv) and write ciphertext.txt and inventory.tsv.

Written 24 Sept 2026. Segmentation rule (NOTES.md, "Segmentation"): the scribe marks no group boundaries, so
the unit of the transcription is the sign (digits 0-9 and y, the ij-shaped sign). Each pass's own grouping is
kept as an alternative, per sign, in the columns a_start / b_start (1 = that pass began a group here).

Confidence per sign: H when every available reading (A, B, native) gives the same sign and there are at least
two of them; M otherwise, with the other readings in `alt`.

  python3 reconcile.py          write ciphertext.txt and inventory.tsv
  python3 reconcile.py --check  exit 1 if the committed files differ from what the passes regenerate
"""
import csv
import difflib
import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))

NOTES = {
    ('f8_L2', 1): 'dotted i right after a struck word; A and B omit it; may belong to the plain text',
    ('f8_L4', 1): 'superscript 24 written over a struck group (2217?): scribal replacement',
    ('f8_L4', 2): 'superscript 24 (replacement)',
    ('f8_L8', 21): 'digit written over / blotted',
    ('f8_L9', 27): 'interlinear insertion y20, placed at a colon-like caret after 17',
    ('f8_L9', 28): 'interlinear insertion y20',
    ('f8_L9', 29): 'interlinear insertion y20',
    ('f8_L11', 9): 'digit overwritten (heavy ink)',
    ('f8_L11', 24): 'digit overwritten (heavy ink)',
    ('f9_L6', 3): 'thin 7-like stroke; A and B omit it',
    ('f9_L6', 34): 'superscript 17 over a blotted group: scribal replacement',
    ('f9_L6', 35): 'superscript 17 (replacement)',
    ('f10_L7', 27): 'superscript 2 over a blotted digit: scribal correction',
}


def pass_signs(path):
    """Per line: list of (sign, group_start) from a pass file; PLAIN and flagged rows skipped."""
    out = {}
    for r in csv.DictReader(open(path), delimiter='\t'):
        g = r['group']
        if g.startswith('['):
            continue
        g = g.split(' ')[0].replace('11~', 'y').replace('~', '').replace('(?)', '').replace('.', '')
        for i, ch in enumerate(g):
            out.setdefault(r['line'], []).append((ch, i == 0))
    return out


def native():
    out = {}
    for line in open(os.path.join(HERE, 'passC_native.tsv')):
        if line.startswith('#') or line.startswith('line\t'):
            continue
        k, s = line.rstrip('\n').split('\t')
        out[k] = s.split()
    return out


def align(ref, other):
    """For each ref position, the aligned (sign, start) of `other`, or None."""
    res = [None] * len(ref)
    sm = difflib.SequenceMatcher(None, ref, [c for c, _ in other], autojunk=False)
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag in ('equal', 'replace'):
            for k in range(min(i2 - i1, j2 - j1)):
                res[i1 + k] = other[j1 + k]
    return res


def build():
    A = pass_signs(os.path.join(HERE, 'passA.tsv'))
    B = pass_signs(os.path.join(HERE, 'passB.tsv'))
    C = native()
    rows = []
    for line, ref in C.items():
        a = align(ref, A.get(line, []))
        b = align(ref, B.get(line, []))
        for i, s in enumerate(ref):
            reads = [x[0] for x in (a[i], b[i]) if x] + [s]
            conf = 'H' if len(reads) >= 2 and len(set(reads)) == 1 else 'M'
            alt = []
            for tag, x in (('A', a[i]), ('B', b[i])):
                if x is None:
                    alt.append(tag + ':-')
                elif x[0] != s:
                    alt.append(tag + ':' + x[0])
            rows.append([line, str(i + 1), s, conf, ','.join(alt),
                         '1' if a[i] and a[i][1] else ('0' if a[i] else '-'),
                         '1' if b[i] and b[i][1] else ('0' if b[i] else '-'),
                         NOTES.get((line, i + 1), '')])
    return rows


def render(rows):
    head = ['# BnF fr.4687 items 1-3, cipher passages on Gallica canvases 8, 9, 10 (ark:/12148/btv1b90075058).',
            '# Generated by reconcile.py from passA.tsv, passB.tsv, passC_native.tsv. Do not edit by hand.',
            '# Unit = sign (0-9, y = the ij-shaped sign). The scribe marks no group boundaries (NOTES.md, Segmentation).',
            '# conf: H = A, B and the native reading agree (>=2 readings); M = otherwise. alt: other readings (- = no sign there).',
            '# a_start/b_start: 1 = that pass began a group at this sign, 0 = mid-group, - = pass has no aligned sign.',
            '# Covers the 16 lines both passes read plus f8_L11 (pass B only). Untranscribed cipher lines: NOTES.md.',
            'line\tpos\tsign\tconf\talt\ta_start\tb_start\tnote']
    ct = '\n'.join(head + ['\t'.join(r) for r in rows]) + '\n'
    signs = Counter(r[2] for r in rows)
    conf = Counter((r[2], r[3]) for r in rows)
    inv = ['sign\tcount\tH\tM']
    for s, n in sorted(signs.items(), key=lambda x: (-x[1], x[0])):
        inv.append(f'{s}\t{n}\t{conf[(s, "H")]}\t{conf[(s, "M")]}')
    inv.append(f'TOTAL\t{sum(signs.values())}\t{sum(v for (s, c), v in conf.items() if c == "H")}\t'
               f'{sum(v for (s, c), v in conf.items() if c == "M")}')
    return ct, '\n'.join(inv) + '\n'


def main():
    ct, inv = render(build())
    targets = {'ciphertext.txt': ct, 'inventory.tsv': inv}
    if '--check' in sys.argv:
        stale = [f for f, t in targets.items()
                 if not os.path.exists(os.path.join(HERE, f)) or open(os.path.join(HERE, f)).read() != t]
        if stale:
            print('stale:', ', '.join(stale))
            sys.exit(1)
        print('ok: ciphertext.txt and inventory.tsv match the passes')
        return
    for f, t in targets.items():
        open(os.path.join(HERE, f), 'w').write(t)
    print('wrote', ', '.join(targets))


if __name__ == '__main__':
    main()
