#!/usr/bin/env python3
"""Decode f.268 with only key v3's high-confidence cells; every other token is [MARK]. R12D-VILL, 6 Oct 2026.

Pre-registration: PREREG-R12D-VILL.md (committed before the scored run). Set "primary": key_f275_v3.tsv rows flagged
confirmed / confirmed-unclear with count >= 2; set "secondary": primary plus rows with unclear=0 and count >= 2.

  python3 decode_restricted.py              write reading_restricted.txt (both transcriptions, both sets)
  python3 decode_restricted.py --check      exit 1 if reading_restricted.txt is stale (rule 7)
  python3 decode_restricted.py --control    200 class-shuffled restricted keys vs the real one, fr16 and fr17
  python3 decode_restricted.py --runs F     write the primary-set run text (ciphertext.txt) to F for judge_plaintext.py

Grades per decoded token (rule 4): H = cell agree >= 0.6 and transcription agree AB; M = any other decoded token;
U = [MARK]. Score: length-weighted mean log10 4-gram/letter over runs of >= 4 letters (tools/judge_plaintext.py
NgramModel). The class shuffle permutes values within kind among the set's own signs, so coverage and run positions
are fixed and only run letters change.
"""
import argparse
import importlib.util
import random
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
KEY = HERE / "keys" / "key_f275_v3.tsv"
CIPHERS = {"v1": HERE / "ciphertext.txt", "v2": HERE / "ciphertext_v2.txt"}
OUT = HERE / "reading_restricted.txt"
SEED, NSHUF, MINRUN = 20261006, 200, 4


def load_key():
    rows = {}
    for line in open(KEY, encoding="utf-8"):
        if line.startswith("#") or line.startswith("sign\t"):
            continue
        f = line.rstrip("\n").split("\t")
        rows[f[0]] = dict(value=f[1], kind=f[2], unclear=f[5], count=int(f[7] or 0), agree=float(f[8] or 0), flag=f[10])
    return rows


def restricted(rows, which):
    out = {}
    for s, r in rows.items():
        if r["count"] < 2 or r["kind"] not in ("letter", "word") or not r["value"] or r["value"] == "?":
            continue
        if r["flag"] in ("confirmed", "confirmed-unclear") or (which == "secondary" and r["unclear"] == "0"):
            out[s] = r
    return out


def load_cipher(path):
    lines = {}
    for line in open(path, encoding="utf-8"):
        if line.startswith("#") or line.startswith("side\t"):
            continue
        f = line.rstrip("\n").split("\t")
        lines.setdefault((f[0], int(f[1])), []).append((f[3], f[4] if len(f) > 4 else ""))
    return [(k, lines[k]) for k in sorted(lines, key=lambda k: (k[0] != "r", k[1]))]


def decode(toks, key):
    """-> (display string, list of runs, grade counts)"""
    disp, runs, run, g = [], [], "", {"H": 0, "M": 0, "U": 0}
    def flush():
        nonlocal run
        if run:
            disp.append(run); runs.append(run); run = ""
    for t, agr in toks:
        r = key.get(t)
        if r is None:
            flush(); g["U"] += 1
            if not disp or disp[-1] != "[MARK]":
                disp.append("[MARK]")
            continue
        g["H" if (r["agree"] >= 0.6 and agr == "AB") else "M"] += 1
        if r["kind"] == "letter":
            run += r["value"]
        else:
            flush(); disp.append(r["value"].upper()); runs.append(r["value"])
    flush()
    return " ".join(disp), runs, g


def shuffled(key, rnd):
    new = {k: dict(v) for k, v in key.items()}
    for kind in ("letter", "word"):
        signs = [k for k, v in key.items() if v["kind"] == kind]
        vals = [key[k]["value"] for k in signs]
        rnd.shuffle(vals)
        for k, v in zip(signs, vals):
            new[k]["value"] = v
    return new


def render():
    rows = load_key()
    out = ["# reading_restricted.txt -- generated by decode_restricted.py (R12D-VILL, 6 Oct 2026). NOT a reading: a",
           "# mechanical decode with only key v3's high-confidence cells; [MARK] = sign outside the set; word codes in",
           "# capitals. Grades H/M/U per PREREG-R12D-VILL.md. Lines: <transcription> <set> <side><line> <decode>."]
    for cname, path in CIPHERS.items():
        for which in ("primary", "secondary"):
            key = restricted(rows, which)
            tot = {"H": 0, "M": 0, "U": 0}
            body = []
            for (s, n), toks in load_cipher(path):
                d, _, g = decode(toks, key)
                for k in tot:
                    tot[k] += g[k]
                body.append(f"{cname}\t{which}\t{s}{n}\t{d}")
            used = [key[t] for _, toks in load_cipher(path) for t, _ in toks if t in key]
            prec = sum(r["agree"] for r in used) / len(used) if used else 0
            n = sum(tot.values())
            out.append(f"## {cname} {which}: {len(key)} cells; tokens {n}: H {tot['H']} M {tot['M']} U {tot['U']} "
                       f"(decoded {100 * (tot['H'] + tot['M']) / n:.1f}%); expected clerk precision of decoded tokens {prec:.3f}")
            out += body
    return "\n".join(out) + "\n"


def models():
    spec = importlib.util.spec_from_file_location("jp", ROOT / "tools" / "judge_plaintext.py")
    jp = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(jp)
    return {c: jp.NgramModel([jp.read_corpus(p) for p in jp.LANG_CORPORA[c]]) for c in ("fr", "fr17")}


def runscore(m, runs):
    rs = [r for r in runs if len(r) >= MINRUN]
    w = sum(len(r) - 3 for r in rs)
    return sum(m.score(r) * (len(r) - 3) for r in rs) / w if w else float("nan"), len(rs), sum(map(len, rs))


def control():
    rows, ms = load_key(), models()
    for cname, path in CIPHERS.items():
        cipher = load_cipher(path)
        for which in ("primary", "secondary"):
            key = restricted(rows, which)
            allruns = lambda k: [r for _, t in cipher for r in decode(t, k)[1]]
            rnd = random.Random(SEED)
            shuf = [shuffled(key, rnd) for _ in range(NSHUF)]
            for c, m in ms.items():
                real, nr, nl = runscore(m, allruns(key))
                sl = [runscore(m, allruns(k))[0] for k in shuf]
                mu, sd = statistics.mean(sl), statistics.pstdev(sl)
                rank = 1 + sum(x > real for x in sl)
                print(f"{cname} {which:9s} {c:4s}: runs>={MINRUN} {nr} letters {nl}; real {real:.4f}; {NSHUF} shuffled "
                      f"mean {mu:.4f} sd {sd:.4f} max {max(sl):.4f}; z {(real - mu) / sd:.2f}; rank {rank} of {NSHUF + 1}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--control", action="store_true")
    ap.add_argument("--runs")
    a = ap.parse_args()
    if a.control:
        return control()
    if a.runs:
        key = restricted(load_key(), "primary")
        runs = [" ".join(decode(t, key)[1]) for _, t in load_cipher(CIPHERS["v1"])]
        Path(a.runs).write_text("\n".join(runs) + "\n")
        return
    text = render()
    if a.check:
        if not OUT.exists() or OUT.read_text() != text:
            print("reading_restricted.txt is stale; rerun decode_restricted.py", file=sys.stderr)
            sys.exit(1)
        print("reading_restricted.txt current")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.name}")


if __name__ == "__main__":
    main()
