#!/usr/bin/env python3
"""GAPS6-moray-wood-1568 (2 Oct 2026): judge Aymeloglu's reading (key.tsv on ciphertext.tsv) with tools/judge_plaintext.py
under each corpus, beside 20 letter-shuffled nulls of the candidate and 20 shuffled-target decodes (ciphertext sign order
shuffled within the postscript, gaps kept, same key, same rendering) -- rule 3; ARM-C1: a PASS on a shuffled-target
decode voids the judge for this key at this N. Rendering: word-signs U/o2 expanded (the/and), person-signs 4b/Eb dropped
(not letters). Writes judge_candidate.txt and judge_controls.tsv; deterministic (seeds 1-20).
  python3 ciphers/moray-wood-1568/judge_controls.py
"""
import json, random, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent; ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from judge_plaintext import judge, fold, NgramModel, read_corpus, pct, LANG_CORPORA  # noqa: E402

DROP = {"4b", "Eb"}
key = {r[0]: r[1] for r in (l.rstrip("\n").split("\t") for l in open(HERE / "key.tsv") if not l.startswith("#")) if r[0] != "code"}
rows = [l.rstrip("\n").split("\t") for l in open(HERE / "ciphertext.tsv") if not l.startswith("#")][1:]
lines = {}
for r in rows:
    lines.setdefault(r[0], []).append(r[2])


def render(seq_by_line):
    out = []
    for ln, seq in seq_by_line.items():
        words, w = [], ""
        for s in seq:
            if s == "|":
                words.append(w); w = ""
            elif s not in DROP:
                w += key[s]
        words.append(w)
        out.append(" ".join(x for x in words if x))
    return "\n".join(out) + "\n"


cand = render(lines)
(HERE / "judge_candidate.txt").write_text(cand)
signs = [s for v in lines.values() for s in v if s != "|"]
spec = json.load(open(ROOT / "specs" / "moray-wood-1568.json"))
en16 = dict(spec, judge=dict(spec["judge"], language=None, corpora=sorted(str(p) for p in (ROOT / "tools/data/en16_repo").glob("*.txt"))))
en16["judge"].pop("language")
rows_out = [("corpus", "kind", "seed", "letters", "score", "null_p99", "real_p05", "real_median", "verdict")]
for name, sp in (("sco16", spec), ("en16_repo", en16)):
    # judge_plaintext.judge()'s language check with the model built once and controls cached per N (same samples, seed 1)
    model = NgramModel([read_corpus(p) for p in (sp["judge"].get("corpora") or LANG_CORPORA[sp["judge"]["language"]])])
    cache = {}

    def run(kind, seed, text):
        L = fold(text); N = max(len(L), 20)
        if N not in cache:
            real, null, _ = model.controls(N, samples=int(sp["judge"].get("control_samples", 200)))
            cache[N] = (pct(null, 0.99), pct(real, 0.05), pct(real, 0.5))
        n99, r05, rmed = cache[N]; sc = model.score(L)
        ok = sc > n99 and sc > r05 and sp["judge"]["letters_min"] <= len(L) <= sp["judge"]["letters_max"]
        rows_out.append((name, kind, seed, len(L), round(sc, 3), round(n99, 3), round(r05, 3), round(rmed, 3), "PASS" if ok else "FAIL"))
        return rows_out[-1]
    c = run("candidate", 0, cand)
    full = judge(sp, cand)  # cross-check the cached path against the tool itself on the candidate
    assert (full["checks"]["language"]["score"], full["checks"]["language"]["real_p05"]) == (c[4], c[6]), (full, c)
    for sd in range(1, 21):
        L = list(fold(cand)); random.Random(sd).shuffle(L); run("shuffled_null", sd, "".join(L))
        sh = signs[:]; random.Random(sd).shuffle(sh); it = iter(sh)
        run("shuffled_target", sd, render({ln: [s if s == "|" else next(it) for s in seq] for ln, seq in lines.items()}))
with open(HERE / "judge_controls.tsv", "w") as f:
    f.write("# generated by judge_controls.py (GAPS6, 2 Oct 2026); do not edit\n")
    for r in rows_out:
        f.write("\t".join(map(str, r)) + "\n")
for name in ("sco16", "en16_repo"):
    rs = [r for r in rows_out[1:] if r[0] == name]
    c = [r for r in rs if r[1] == "candidate"][0]
    print(f"{name}: candidate score {c[4]} letters {c[3]} null_p99 {c[5]} real_p05 {c[6]} real_median {c[7]} -> {c[8]}")
    for k in ("shuffled_null", "shuffled_target"):
        sc = sorted(r[4] for r in rs if r[1] == k); p = sum(r[8] == "PASS" for r in rs if r[1] == k)
        print(f"  {k}: n=20 min {sc[0]} median {(sc[9]+sc[10])/2:.3f} max {sc[-1]} PASS {p}/20; candidate above {sum(x < c[4] for x in sc)}/20")
